### ISSUE TITLE
Deprecated file format Expo

### ISSUE THREAD

**Issue by jgoodhcg** [thheller/shadow-cljs#1001]
It looks like the build process doesn't need to generate files with `*.expo.js` anymore.

Here is output from the newest `expo-cli`

```bash
➜  mobile-app git:(main) ✗ yarn start                     
yarn run v1.22.10
warning ../package.json: No license field
$ expo start
Starting project at /home/justin/projects/din/mobile-app
Developer tools running on http://localhost:19002
Project is using deprecated .expo.* file extensions.
Please refactor the following files accordingly:

- /home/justin/projects/din/mobile-app/build/shadow.expo.js

Dangerously disable this check with EXPO_LEGACY_IMPORTS=1
Learn more: http://expo.fyi/expo-extension-migration

```

**Comment by thheller** [comment]
This isn't at all related to what expo thinks of as `.expo.js` files.

This just happens to be a `shadow.expo` CLJS namespace being compiled to `shadow.expo.js`. This is a regular CLJS namespace like any other where the generated filename is `<ns>.js`. It is unfortunate that expo doesn't like this but it is not at all about what it thinks it is. Since I don't want to break builds of other people using this I cannot rename this namespace.

This namespace is very minimal https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/expo.cljs

So you can take it an make a local copy with a "safe" name and use that instead. Nothing in the system expects the name to be `shadow.expo`. It was just the name I chose. Rename it to whatever and use it in place of the `shadow.expo` require you have in your app.
