### ISSUE TITLE
shadow expects a :host key in nrepl config but it's supposed to be :bind

### ISSUE THREAD

**Issue by nivekuil** [thheller/shadow-cljs#1014]
https://github.com/thheller/shadow-cljs/blob/051b5ecc7d701ef45b3bbc839685ac6ea03d4ad7/src/main/shadow/cljs/devtools/server/nrepl.clj#L127

Was struggling to bind nrepl to something other than 127.0.0.1 and found this. According to nrepl the key should be called `:bind` https://nrepl.org/nrepl/usage/server.html

**Comment by thheller** [comment]
The key is passed as bind here?

https://github.com/thheller/shadow-cljs/blob/051b5ecc7d701ef45b3bbc839685ac6ea03d4ad7/src/main/shadow/cljs/devtools/server/nrepl.clj#L138

I'm using `:host` since it is more consistent with all the other options in shadow-cljs which also use `:host`. Is that causing a problem somewhere?

**Comment by nivekuil** [comment]
It is surprising because shadow reads from nrepl.edn, but does not support its syntax fully, expecting one key to be named differently. Could support both key names?
