### ISSUE TITLE
Weird circular dependency

### ISSUE THREAD

**Issue by JanSuran03** [thheller/shadow-cljs#1027]
Am I doing something wrong or is this a bug?

![image](https://user-images.githubusercontent.com/62071148/177428370-12be7d84-5ae7-45c2-98a1-1eb5c8adf21e.png)
![image](https://user-images.githubusercontent.com/62071148/177428381-5a048765-90e3-472d-82ec-014672682038.png)

**Comment by JanSuran03** [comment]
Restarting Shadow did help. I think I entered one of the namespaces via `in-ns` and required one of the others which created a circular dependency. But recompiling shadow didn't get rid of the circular dependency although it only has been done via REPL.

**Comment by JanSuran03** [comment]
I mean, it's probably not a bug, it's just an edge case which it's hard to do something about. But you don't really want this to happen to you.

**Comment by thheller** [comment]
Yes, invoking stuff in the REPL may affect the build in unexpected ways. This one is particularly nasty since it sticks arround until you actually modify the file that had the `require` added or restart the build. Separating out REPL-sourced state and file-on-disk-state is kinda tricky so this is a somewhat known limitation.
