### ISSUE TITLE
shadow-cljs stop working with java 1.8

### ISSUE THREAD

**Issue by ikappaki** [thheller/shadow-cljs#1050]
Hi,

`shadow-cljs` has stopped working with a recent update on Java 1.8, which adversely affects users stuck with old but proven setups and want be able to get shadow updates/bug fixes anymore

```
shadow-cljs - dependencies updated
Execution error (UnsupportedClassVersionError) at java.lang.ClassLoader/defineClass1 (ClassLoader.java:-2).
com/google/javascript/jscomp/CompilerOptions has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

This is due to a recent commit https://github.com/thheller/shadow-cljs/commit/35edd7df69efbefc3d764315deb3b22ad94ab57a

```
 hard bump to Java11 minimum

the closure compiler already is and we inherit that. might as
well bump ourselves. also the previous commit uses built-in
java11 http client, so we need it now regardless.
```

Does this mean that the clojurescript compiler is also dependent on jdk11 or shadow-cljs uses a more advanced version? Is there a way around it?

Thanks

**Comment by thheller** [comment]
The crux is that the Closure Compiler bumped the minimum to Java11 (ie. the error you are seeing). shadow-cljs heavily uses the Closure Compiler and therefore inherited that bump. Due to its heavy use I update to the latest Closure Compiler version frequently.

ClojureScript has not yet updated to a Closure Compiler version requiring Java11, so they are not there yet. IMHO it is inevitable though and will get there "soon" too.

There is no way arround this other than staying on older versions, which unfortunately due to a lot of breaking changes in the Closure Compiler is not really an option. Unless of course you stay on an older shadow-cljs as well.

I never had an issue upgrading a Java version, so I don't think this is a big deal either way. Java8 is end-of-life in 2 years-ish so its about time to start figuring out an update path. IMHO, YMMV.

**Comment by ikappaki** [comment]
> I never had an issue upgrading a Java version, so I don't think this is a big deal either way. Java8 is end-of-life in 2 years-ish so its about time to start figuring out an update path. IMHO, YMMV.

The difficulty is not so much updating on a computer the user has full access to, it is more to do with companies which have full control of which programs are installed on their workstation and server computers. They are usually inflexible with their policies. If something is stable and working as expected, they tend to stick with it until it goes EoL. Figuring out a path is one thing, forcing them to move is another :)

I care more about the back end in this case, I suppose this only affect the java version shadow is running on while developing, once the js is generated then it does not have any dependencies on the java runtime, right?

Thanks

**Comment by thheller** [comment]
> once the js is generated then it does not have any dependencies on the java runtime, right?

Yes, a `release` build has no dependence on java or shadow-cljs. It is entirely standalone.
