### ISSUE TITLE
Support Chrome Extension manifest v3 content_security_policy key

### ISSUE THREAD

**Issue by viesti** [thheller/shadow-cljs#1051]
Hi!

First off, thanks for this awesome project! :)

I just tried this out for making a Chrome Extension (which isn't documented, but I think there might be a gem hiding here :)) with a really barebones manifest.edn file:

```clojure
{:name             "Chrome Extension"
 :version          "1.0"
 :description      "This example project is using shadow-cljs"
 :manifest-version 3     ;; <--- Tried out v3 off the bat
 :permissions      ["activeTab"]}
```

This then on release generates a `manifest.json` file like this:

```clojure
{"name":"Chrome Extension",
 "version":"1.0",
 "description":"This example project is using shadow-cljs",
 "manifest_version":3,
 "permissions":["activeTab"],
 "content_security_policy":"",
 "content_scripts":
 [{"js":["out/shared.js", "out/content-script.js"],
   "matches":["<all_urls>"],
   "run_at":"document_end"}]}
```

This errors out when loading into Chrome:

> Error
> Invalid value for 'content_security_policy'.
> Could not load manifest.

Reading Chrome Extension documentation, the `content_security_policy` key changed in the [V3 manifest from string to an object](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#content-security-policy):

<img width="754" alt="image" src="https://user-images.githubusercontent.com/57011/193247994-8e26c98e-da49-465e-8b08-5b5367c4e81d.png">

I think the V3 manifest `content_security_policy` key type could be supported with a check that if the value is a map, then don't modify the value and if the key doesn't exist, don't create it, in the code here:

https://github.com/thheller/shadow-cljs/blob/49fb078b834e64f63122e3a8ad3ddcd1f4485969/src/main/shadow/build/targets/chrome_extension.clj#L210

I didn't yet look if there other stuff to worry about with manifest V3.

Cheers!

**Comment by thheller** [comment]
I created [an example repo](https://github.com/thheller/chrome-ext-v3) showing how to create a Chrome Extension using the v3 manifest.

`:target :chrome-extension` is no longer needed and should be considered obsolete as far as I can tell. There is no longer any need for the build to modify the manifest. This was solely done because Chrome couldn't otherwise load additional files. With ESM it can, so the manifest can be manually created as is and not touched by shadow-cljs.

I did not try getting hot-reload or REPL to work since supposedly `eval` is no longer possible. So, changes will only show up if you reload the extension. Other than that it loads fine. I don't know any additional details beyond that since I don't write Chrome Extensions myself and I'm not familiar with the APIs.

**Comment by viesti** [comment]
Nice, thanks! I'm just dabbling here myself, didn't know about `eval` limitation, but found via [a post](https://medium.com/geekculture/how-to-use-eval-in-a-v3-chrome-extension-f21ca8c2160c) that there is this [sandbox](https://developer.chrome.com/docs/extensions/mv3/manifest/sandbox/) thing, but it then might be awkward to arrange code to live in the sandbox, for say a repl to work, hmm.

**Comment by thheller** [comment]
Closing this as I don't think there is anything to be done from the shadow-cljs side. Use the example I created above and consider `:target :chrome-extension` dead and deprecated if you must use v3 manifests.
