### ISSUE TITLE
Dev specific compiler-options / preloads

### ISSUE THREAD

**Issue by sirmspencer** [thheller/shadow-cljs#1053]
We have two different re-frame tools that can be loaded with preloads.  Our team is split on which one should be the default.  I need a way to let each dev set which one to pick.  `.shadow-cljs/config.edn` is already untracked so that could be a good place to stick it.  If I could stick user specific compiler options there, I can create my own preload to read that and select which re-frame tool to load.

**Comment by thheller** [comment]
Sorry, this got lost.

Would [#shadow/env](https://shadow-cljs.github.io/docs/UsersGuide.html#shadow-env) be an option here?
```
:preloads [#shadow/env ["PREF_DEVTOOL" :as :symbol :default re-frame-10x.preload]]
```

By setting PREF_DEVTOOL=some.other.ns in the env this could override the default?

How would `.shadow-cljs/config.edn` look in your idea? I don't want to put too much functionality there since it hurts reproducibility and may lead to lots of "it works on my machine" types of problems :P

**Comment by sirmspencer** [comment]
I also missed closing this.  I created a preload that reads in a local dev file for settings, and then initiates things directly.
