### ISSUE TITLE
any tips to notice to bundle npm packages in release mode?

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#106]
Tried in http://repo.tiye.me/Memkits/smallist/ but got an error:

```
Uncaught TypeError: $module$node_modules$shortid$index$$.$generate$ is not a function
```

Looks like `shortid.generate` is not bundled correctly. Any additional configures required?

**Comment by thheller** [comment]
It is bundled correctly, you are missing `:externs` for the `generate` fn.

Run `shadow-cljs check`, it should tell you.

**Comment by thheller** [comment]
Names like `$generate$`, ie. a name wrapped in `$`, represent names that will be "shortened" in `:advanced` mode. So you need `:externs` to prevent closure from shortening them.

**Comment by jiyinyiyong** [comment]
Fixed. Cool!
```js
/**
 * @externs
 */

var module$node_modules$shortid$index = {};
module$node_modules$shortid$index.generate = function() {};
```

Just, why is the variable name so long...

**Comment by thheller** [comment]
Yeah, do not write it like that.

The example I gave you a few days ago from [here](https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/cljs/npm/externs.js) is a better template.

Just add `X.prototype.generate` at the end. You do not actually want to preserve the `module$node_modules$shortid$index` name, only the `generate` part. This part `module$node_modules$shortid$index` is so long since its a generated name that will usually be shortened, so length does not matter.

**Comment by thheller** [comment]
It is only about keeping the **property**, it does not need to know that `X` refers to `shortid`.

`X.prototype.generate;` basically says that ANY property name `.generate` should never be renamed, regardless which object it is on. Usually this is too general but since CLJS isn't fully typed anyways it does not matter much.

Since we don't use global names anymore preserving the properties is all we need.

It is cheating but I really can't be bothered to write typed externs so this has worked well for me. The externs I linked are all the actual externs I use for the `shadow-cljs` npm script.

**Comment by jiyinyiyong** [comment]
This really unexpecting. Feeling not good, although it works well.

By the way, what's your opinion about https://github.com/indutny/common-shake ?

**Comment by thheller** [comment]
No idea, never heard of `common-shake`. No spare brain power to look at it currently.

**Comment by jiyinyiyong** [comment]
I don't trust CommonJS, but I trust @indutny though... If such ideas brings new solutions to dead code elimination to ClojureScript, it would be nice.

**Comment by thheller** [comment]
I think the Closure Compiler has this pretty much figured out. I don't see the need for new solutions.

The compromise is that you can't do certain "dynamic" programming styles, since they just can't be statically analyzed. I expect that all JS tools will have to make this compromise in some way. You can probably gain a tiny bit more which in turn will make the compiler a whole lot slower. At some point you just have to say "enough".
