### ISSUE TITLE
dev-http server with 'classpath:foo' config no longer defaults to index.html

### ISSUE THREAD

**Issue by henryw374** [thheller/shadow-cljs#1064]
I just upgraded to 2.20.10 and now I have to manually add 'index.html' to the url

**Comment by henryw374** [comment]
Cheers!

**Comment by henryw374** [comment]
Hi. I just had a go with this and it is still not quite right. Given `classpath:foo` I can visit http://host:port and it will default to index.html in foo. 

but, if I go to http://host:port/bar it resolves index.html from foo, not foo/bar. I have to type in http://host:port/bar/index.html to get the foo/bar index.html file

**Comment by thheller** [comment]
Hmm so this is sort of how its meant to work. Since the assumption is that the client does the "routing" internally, ie. page rendered by JS. So, whenever the request at the handler it just checks the root for an index.html and serves that.

Didn't think people used any actual nested index.html files.

You can get the old behavior back by setting `:dev-http {1234 {:root "classpath:foo" :use-index-files true}}` instead of just `:dev-http {1234 "classpath:foo"}`.

**Comment by henryw374** [comment]
Thanks I tried `use-index-files` and couldn't get it to work. This is on 2.20.12. I also searched the shadow code base for that in case I am doing something wrong, but I couldn't find any reference to `use-index-files` .
