### ISSUE TITLE
proxy-url option for dev-http config breaks automatic redirect to index.html

### ISSUE THREAD

**Issue by jkorpelin** [thheller/shadow-cljs#1071]
With version `2.20.12` if you give a proxy-url in the `shadow-cljs.edn` for the dev-http the server doesn't automatically serve the index.html. Everything works as expected with version `2.19.2`.

Here is a minimum repo to reproduce the bug: https://github.com/jkorpelin/shadow-cljs-proxy-bug

node version: 18.12.1
npm version: 8.19.2

OS: macOS Monterey version 12.5, Chip Apple m1 pro

**Comment by jarppe** [comment]
Ran into this too, downgrading to 2.19.2 helps.

**Comment by thheller** [comment]
This is working as expected, and old behavior was sort of the bug.

Another [bug](https://github.com/thheller/shadow-undertow/commit/a64b4afa1ab39931b17742492f06480c38e5911f) however prevented this from working properly, so it served `index.html` locally instead of going to the proxy.

The intent is that `:proxy-url` serves all content that isn't available locally. `/` isn't available, so it is sent to the proxy. `/index.html` would work fine.

You can get the old behavior back by setting `:use-index-files true` in the server config.

```clojure
 :dev-http
 {8280
  {:root "resources/public"
   :proxy-url "http://localhost:8080"
   :use-index-files true}}
```

Requires version `2.20.20` I just released, since there was another issue that ignored this config entry.

**Comment by jimpil** [comment]
Wow , I've spent close to two days trying to sort this exact problem out - turns out the solution is trivial, but not documented anywhere...

I think `:use-index-files` deserves at least one sentence in the [user-guide](https://shadow-cljs.github.io/docs/UsersGuide.html#dev-http). In addition, the `re-frame` leiningen template pulls in a version of shadow-cljs that is before `2.20.20`, so ideally, this should be tweaked too. 

Many thanks in advance :+1:

**Comment by rjsheperd** [comment]
@thheller would be great to see this in the User Guide!
