### ISSUE TITLE
Warning by `shadow-cljs check` when using hash set as a function

### ISSUE THREAD

**Issue by EugenDueck** [thheller/shadow-cljs#1078]
`shadow-cljs check` gives me a warning every time I use a hash set literal as a function.

Example:
```
 196 |               (let [is-intro (#{"i" "v"} c)
-----------------------------------------------^--------------------------------
 Function cljs.core.PersistentHashSet.prototype.call: called with 2 argument(s). Function requires at least 1 argument(s) and no more than 1 argument(s).
--------------------------------------------------------------------------------
```

**Comment by thheller** [comment]
`check` is an unsupported/undocument feature, which never turned out the way I wanted it to. It unfortunately produces huge amounts of false positives and other noise. In can be useful in a pinch, but you have to kinda know what you are looking at and filter accordingly.

At this point I do not have plans of working on it, since it requires too many hacks as it is now.
