### ISSUE TITLE
[feature] Add support to hook external build to shadow-cljs

### ISSUE THREAD

**Issue by markokocic** [thheller/shadow-cljs#1098]
It is often required to use an external build tool (for example webpack) to handle dependencies, in which cases `:js-provider :external` is used.

The issue with that is that one needs to make sure to have another console window and another tool open in order to use it.

It would be a nice addition, if that external tool would be run automatically as part of the shadow-cljs build. The syntax could look something like:

``` edn
{:js-provider :external
 :external-command "npx webpack watch"
```
If `:external-command` key is present, shadow-cljs would run this process as part of the build, if not, it will behave like now.
Also, it would be useful to be able to specify a separate external build command for release build.

**Comment by thheller** [comment]
Sorry, but this is a hard no. This would extremely quickly get out of hand due to the extreme amount of differences in build tools, e.g. one might watch, another might want to execute on every rebuild, another might want to use an actual web server.

You gain absolutely nothing by having shadow-cljs restrict the choices you have there. There are already many other solutions to running multiple things in one command. I use [npm-run-all](https://www.npmjs.com/package/npm-run-all) often, very simple to setup and use.
