### ISSUE TITLE
Import omitted when not used (`:esm`)

### ISSUE THREAD

**Issue by dehli** [thheller/shadow-cljs#1102]
From [Slack](https://clojurians.slack.com/archives/C6N245JGG/p1679490947546069):

I'm running into a bug with `:esm` and a side-effecting library. My shadow config looks like:

```
{:target :esm
 :js-options {:js-provider :import}}
```

and in my cljs, I have `(:require ["quill-mention"])` (the package executes a side-effect).

If I do `(:require ["quill-mention" :as foo])` and add `(js/console.log foo)` my code works, but when I remove the log, the library isn't included. Note, this change only started occurring after 2.20.12.

**Comment by thheller** [comment]
So, I just checked and this is working as intended. Well, the intention was to remove requires that are not actually used anywhere. Of course for side-effect only requires that is a problem.

I do not want to change back to the old behavior, so I think a config option instead is the better choice? Maybe add a log message if a require is removed as dead code, so that you at least know what is going on. Let me think about that for a bit.

**Comment by thheller** [comment]
As of `2.22.9` you can set `:force-imports #{"quill-mentions"}` in the module you want it in. that'll ensure it is always imported, even if never referenced or `:advanced` removing it.

```clojure
{:target :esm
 :modules
 {:foo
  {:exports {...}
   :force-imports #{"foo" "bar"}}}}
```

**Comment by dehli** [comment]
Thanks for the release! I made the change and confirmed that the excluded code is now included in the bundle. I am seeing a bug now where I'm getting `$default` is undefined (it looks to be referenced in only one spot). 

```
return Sf(new R(null,2,5,T,[w,new R(null,2,5,T,[$default,d],null)],null)
```

This bug only occurs when building with release mode, dev is still working fine.

If I add `window.$default = {};` I then get a subsequent error message about `$temp__5804__auto__` being undefined.

**Comment by KingMob** [comment]
FYI, this is not documented in the User's Guide yet. I searched for `:force-imports` and found nothing.
