### ISSUE TITLE
unable to resolve dynamic imports using ESM build

### ISSUE THREAD

**Issue by alidcast** [thheller/shadow-cljs#1105]
Running into this issue twice now, so wanted to report it for others; and see if there's a tenable resolution, despite bundlers being outside bounds of shadow-cljs.

The problem is that when `esm` build with other bundlers, many do not handle dynamic imports outputted by shadow-cljs.

Use-case: I am using `ESM` since I have JSX components that need to be compiled by a babel plugin.

Bundler problems:
* React Native Metro's bundler does not handle dynamic imports (https://github.com/facebook/metro/issues/52);
* Vite limits the dynamic imports that can be used 

End up with error like the following with RN:

```
dist/cljs-runtime/cljs_env.js: dist/cljs-runtime/cljs_env.js:Invalid call at line 1394: import(x.startsWith("./") ? "." + x : x)
```

Or in the case of Vite the following warning:

> The above dynamic import cannot be analyzed by Vite.
See https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations for supported dynamic import formats. If this is intended to be left as-is, you can use the /* @vite-ignore */ comment inside the import() call to suppress this warning.

**Comment by thheller** [comment]
Please provide a code snippet or repo showing the actual problem, otherwise I'm missing the context of the problem here.

> error out

what does this mean? I assume this is from the `shadow_esm_import` helper. Does vite choke on an unused function?

For react-native you are supposed to use `:target :react-native`. Given that metro doesn't support many things of ESM (ie. not even `const`), the lack of support for dynamic `import` is not a concern.

**Comment by thheller** [comment]
The point of that function is explicitely to enable runtime (i.e. not processed by bundlers) `import`. In this case it is also development only code, so that vite is warning about this is quite pointless. I guess adding the suggested comment is not a big deal, although I don't want to end up with a `import(/* @vite-ignore */ /* @webpack-ignore */ /* @esbuild-ignore */ /* @whatver-ignore */ ...)` type of function. :P

**Comment by thheller** [comment]
Nothing in the runtime uses dynamic import. The only place dynamic import is used is `shadow.esm/dynamic-import`, which exists as a hack since the closure compiler will also otherwise complain when trying to use `import()`. Its hacks all the way down, since `import()` is fundamentally something that bundlers struggle with. It is hard to decide whether the code meant actual runtime (post-bundling) `import()` or just wanted to load a lazy chunk as part of the build. Since there is no standard for any of this, each bundler just does something else.

I could add a flag that omitted that specific bit of code, if you care to explain what you are trying to do in the first place. Just using vite, or using it for something specific?

Making two bundlers play nice with each other is always going to be a struggle, given how differently they view the world. vite especially has a very different view of things than shadow-cljs. You might get a bit further with `:npm-module`. Or if this is just about letting something other than shadow-cljs bundle the JS dependencies you may use [`:js-provider :external`](https://shadow-cljs.github.io/docs/UsersGuide.html#js-provider-external).

**Comment by thheller** [comment]
As of `2.22.9` the problematic line is only actually included if `shadow.esm` is required. Which seems to solve that vite problem. Your repro still fails but I couldn't figure out why. At least shadow-cljs and vite seem to build properly. That stack makes me hate computers, so I didn't investigate further.
