### ISSUE TITLE
output of cljs compiler differs in shadowcljs compared to lein-cljsbuild

### ISSUE THREAD

**Issue by somecho** [thheller/shadow-cljs#1118]
Hello! **TLDR:** I'm exporting ClojureScript's `cljs.js/compile-str` to JS and the output from shadow-cljs's build differs from lein-cljsbuild's build. 

## Context
As a side project, I'm creating a web editor where you can write P5 sketches in ClojureScript. To do this, I exported CLJS's `compile-str` function to JS to compile source code client side. Currently, it is using lein-cljsbuild's build and using it as a global script. I'd really like to use the exported function as part of a module (`import {compile} from 'cljs'`) but I don't think cljsbuild can do this. Either that, or I don't know how to setup my `project.clj` properly. For this reason, I decided to turn to shadow-cljs.

## The problem
The output of `compile("(+ 1 1)")` is `((1) + (1));` using cljsbuild but `cljs.user._PLUS_.call(null,(1),(1))` using shadowcljs. The shadowcljs output is invalid, throwing this error: `core.cljs:20 WARNING: Use of undeclared Var cljs.user/+ at line 1`. I'm not sure what is going on here. Ideally, I'd like the output to be the same as cljsbuild's. I have created [a repo](https://github.com/somecho/shadowcljs-vs-cljsbuild) reproducing this bug. To run, call `yarn dev`. 

As you can see from the repo, I'm still not building corrently to be able to do something like `import {compile} from 'testlib'`, instead doing something like `import 'testlib.js'`. Still, this is better than cljsbuild because now you can write unit tests in JavaScript side that is browser independent.

Much thanks for shadow-cljs!

**Comment by thheller** [comment]
This is not a bug. For builds that want to use self-hosted features (i.e. `cljs.js`) you must use the bootstrapped mode as described [in this blogpost](https://code.thheller.com/blog/shadow-cljs/2017/10/14/bootstrap-support.html).

It is also incompatible with `:target :esm` as of this point and really can't be made compatible due to the nature of ESM. So, only `:target :browser` is an option. I'm afraid what you are trying to do is very limited by the nature of how self-hosted CLJS works.

**Comment by somecho** [comment]
Thanks for clarifying. After reading the blogpost, I understand what you mean.
