### ISSUE TITLE
Support multiple REPL connections simultaneously

### ISSUE THREAD

**Issue by YizhePKU** [thheller/shadow-cljs#1133]
I have multiple runtimes and would like to get a REPL for each of them (possibly with different nREPL ports). The use case is to evaluate ClojureScript inside a VSCode extension (by embedding a NodeJS runtime inside the extension), and provide a seperate REPL to the user for each active window. I could run a seperate server for each window, but I'd prefer not since I can't watch on the same build with multiple servers (plus being very inefficient).

In #314 it was mentioned:

> Everything for calling nrepl-select with a runtime-id is already in place it is just not easily accessible yet.

I wonder what's the current situation on that? I tried to piece things together myself with `shadow/select-cljs-runtime` and `shadow/nrepl-select` but couldn't figure it out.

Unlike #314, this should require no change in nREPL protocol, since each client gets its own nREPL port and don't need to worry about choosing a runtime.

**Comment by thheller** [comment]
It is not supported to talk to multiple connections at once, you may select any runtime and eval one at a time though.

You can check the connected runtimes either via http://localhost:9630/runtimes or the runtime id they log when connecting in the form of `shadow-cljs - #<runtime-id> ready!`. This data is also available via the CLJ api by calling `(shadow.cljs.devtools.api/repl-runtimes :your-build-id)`.

Once you have the `:runtime-id` you can `(shadow.cljs.devtools.api/repl :your-build-id {:runtime-id 123})` to select it and start evaluating code in that runtime. There is also `(shadow.cljs.devtools.api/cljs-eval :your-build-id "(js/console.log :yo)" {:runtime-id 123})` to quickly eval some CLJS code but from the CLJ nREPL session.

Technically the underlying REPL protocol (not nREPL) would allow broadcasting to every runtime, but you'd have to write your own client to do so since nREPL is unsuited for this.

**Comment by YizhePKU** [comment]
Thanks for the quick reply! That works for me.
