### ISSUE TITLE
Failed to inspect file when trying to use react-monaco-editor

### ISSUE THREAD

**Issue by 13kay** [thheller/shadow-cljs#1134]
```
Failed to inspect file
  node_modules\monaco-editor\esm\vs\editor\standalone\browser\standalone-tokens.css

Errors encountered while trying to parse file
  node_modules\monaco-editor\esm\vs\editor\standalone\browser\standalone-tokens.css
  {:line 8, :column 1, :message "primary expression expected"}
```

**Comment by thheller** [comment]
shadow-cljs does not support processing CSS files. You can use webpack as [described here](https://shadow-cljs.github.io/docs/UsersGuide.html#js-provider-external) if you need the CSS, if you want a setup a secondary tool for CSS you can set `:js-options {:ignore-asset-requires true}` in the build config so that shadow-cljs ignores them as builds as normal.
