### ISSUE TITLE
How does one use `npx shadow-cljs` without reusing a running shadow-cljs server?

### ISSUE THREAD

**Issue by zilti** [thheller/shadow-cljs#1141]
We have a shadow-cljs project with multiple different build configurations, and differing dependencies depending on the call. Now we noticed that, when there is a REPL running with a shadow-cljs server, the CLI tool will re-use that server, no matter what we want it to build - and that leads to it not respecting all options. Especially, it will re-use the classpath and the JVM args given to the process that runs the server.

Is there a way to call `npx shadow-cljs` and tell it to *not* re-use that running server?

**Comment by thheller** [comment]
shadow-cljs does not support different dependencies per build, so I'm not entirely sure what you are asking here. In general it is not useful or recommended to swap dependencies between builds, as the build will only use what is actually required. Having extra dependencies that are unused does not affect the build in any way.

The whole thing is designed so that one running server takes care of all your build needs. Therefore I strongly recommend NOT running multiple shadow-cljs instances in the project. If you really must you can use the `--force-spawn` flag, or when using `lein` or `deps.edn` run through their command directly as that will also bypass the server.

**Comment by zilti** [comment]
We need slightly different configuration for the environment in which the build is being done, so there is not really a way around it for us. But "--force-spawn" does the job nicely. 

One of them is a dev build, and the other the build needed for testing and release, with certain things (mainly re-frame-10x) disabled. I don't like much going for non-recommended solutions since there's usually good reasons against it, but I guess in this case I have to say "this is the easiest way to go for us", so we use that for the time being.

Thanks for the help!

**Comment by thheller** [comment]
There is also [--config-merge](https://shadow-cljs.github.io/docs/UsersGuide.html#config-merge) as a potential alternative to using env variables, with the added bonus of not requiring a new JVM. ;)
