### ISSUE TITLE
Cannot activate CIDER through tools.deps alias

### ISSUE THREAD

**Issue by vemv** [thheller/shadow-cljs#1155]
I'm seeking to create a project where CIDER is optional, that a variety of people can immediately use, no dotfiles required.

I've tried that in a variety of ways, following the shadow-cljs user manual, to no avail.

Repro with readme: https://github.com/reducecombine/shadow-cider-repro

Thanks - V

**Comment by thheller** [comment]
There are several things in that setup that are not ideal.

First of all, to answer your problem. `shadow-cljs` does not use `deps.edn`, unless specifically told to do so. Invoking it with `-A` is not the way to activate it. So, as [the docs](https://shadow-cljs.github.io/docs/UsersGuide.html#deps-edn) explain you set `:deps true` in `shadow-cljs.edn`, and remove `:source-paths` while you are at it. Once you have done that you also need to add the `thheller/shadow-cljs` dependency in `deps.edn`. Otherwise you are launching shadow-cljs without having shadow-cljs.

Then you have a `:dev` build, which sort of implies to me that you were planning on adding a `release` or `prod` build. This is not the way this is done in `shadow-cljs`. All builds have an implicit dev mode and a release mode. `shadow-cljs watch` and `shadow-cljs compile` always create a dev build, `shadow-cljs release` creates an optimized release build. `shadow-cljs release dev` sounds kinda weird, so I suggest picking a better build-id, e.g. `:app`.

Then you are setting `:output-feature-set :es6` for dev? Whats the point of that? Are you developing for IE8? And why `:dev` only? That makes no sense, just remove that setting entirely.

Then I recommend that all builds follow the init/start/(maybe stop) cycle, outlined in my blogpost about [Hot Reload in CLJS](https://code.thheller.com/blog/shadow-cljs/2019/08/25/hot-reload-in-clojurescript.html). Makes it easier for everyone and avoids some pitfalls. Thus you switch `:entries` to `:init-fn`.

Also, the http config in `:devtools` has been deprecated for like 5 or more years. Don't know where you got it, but remove it and use [:dev-http](https://shadow-cljs.github.io/docs/UsersGuide.html#dev-http) instead.

Also, single segment namespaces should not exist. I suppose that is due to the example nature, but use proper namespaces.

Then you use `npx shadow-cljs`. Don't use `npm` `"scripts"`, unless you add more args. `npm run shadow-cljs -- -A:cider watch dev` could just be `npx shadow-cljs -A:cider watch app`.

The final config could look like this:

```clojure
{:deps true
 :dev-http {8700 "public"}
 :builds
 {:app
  {:target :browser
   :output-dir "public/js"
   :asset-path "/js"
   :modules {:main {:init-fn my.app/init}}}}}
```

I removed the `public/dev` folder entirely since I strongly recommend keeping things simple and release as close as possible to development. So you can run `npx shadow-cljs release app` and try the release build without having to make any adjustments in the HTML. It just uses the same `.js` file, it just now has the release code.

And the final point is I guess that `:cider` IMHO doesn't belong in the projects `deps.edn`. What if you have multiple people working on the project but they are using different cider/emacs versions? IMHO it belongs in `~/.clojure/deps.edn` or `~/.shadow-cljs/config.edn` if not using `deps.edn` in the first place. I get that you are trying to avoid this out-of-project setup but in my experience forcing everything into the project causes more pain that it removes.
