### ISSUE TITLE
class shadow.undertow$fn$reify__11358 cannot be cast to class clojure.lang.Var$Frame

### ISSUE THREAD

**Issue by pesterhazy** [thheller/shadow-cljs#1160]
This exception happens rarely (about once a day) when running the dev env for our browser code

```
Exception in thread "async-dispatch-6" java.lang.ClassCastException: class shadow.undertow$fn$reify__11358 cannot be cast to class clojure.lang.Var$Frame (shadow.undertow$fn$reify__11358 and clojure.lang.Var$Frame are in unnamed module of loader 'app')
	at clojure.lang.Var.resetThreadBindingFrame(Var.java:103)
	at shadow.undertow$fn$reify__11358$fn__11482$state_machine__8296__auto____11521$fn__11524.invoke(undertow.clj:468)
```

I think this is related to websocket handling code

Reminiscent of https://github.com/thheller/shadow-cljs/issues/175

Full stacktrace here:
[stacktrace.txt](https://github.com/thheller/shadow-cljs/files/13297583/stacktrace.txt)

**Comment by thheller** [comment]
Which version mix is this? shadow-cljs? core.async? undertow?

My first, and really only, guess is some sort of version conflict. Or something else messing with classloaders.

This is the [websocket handling loop](https://github.com/thheller/shadow-undertow/blob/24db10c25553f7a1cb4266cf3ce18ae3da7a11b6/src/main/shadow/undertow.clj#L468C28-L468C28) which uses core.async.

If you have something to reliably reproduce this I'm happy to take a look, otherwise I'm afraid there is nothing much I can do.

**Comment by pesterhazy** [comment]
```org.clojure/clojure 1.11.1  (EPL-1.0)
org.clojure/clojurescript 1.11.60  (EPL-1.0)
org.clojure/core.async 1.5.648  (EPL-1.0)
thheller/shadow-client 1.3.3  (EPL-1.0)
thheller/shadow-cljs 2.25.5  (EPL-1.0)
thheller/shadow-cljsjs 0.0.22  (EPL-1.0)
thheller/shadow-undertow 0.3.1  (EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0)
thheller/shadow-util 0.7.0  (EPL-1.0)
io.undertow/undertow-core 2.2.4.Final  (Apache-2.0)```

I'll try and update core.async and see if that helps

**Comment by thheller** [comment]
Not necessary, this is the correct intended core.async version. The rest seems correct too.

That leaves anything messing with Classloaders, the JVM in general or maybe clojure itself such as tools.namespace. No real actual guess though from my end.
