### ISSUE TITLE
Error when attempting to import @ionic/react

### ISSUE THREAD

**Issue by sstraust** [thheller/shadow-cljs#1208]
Hi! I attempted to install @ionic/react via npm, and I'm getting the following error message. The error message reads "INTERNAL COMPILER ERROR. Please report this problem",

so:

--- I'm reporting it!

LMK what's going on or if you need any more info

Failed to inspect file
  /Users/sam/sstraust/eventplanner/eventplannerjs/node_modules/@ionic/core/node_modules/@stencil/core/internal/client/index.js

Errors encountered while trying to parse file
  /Users/sam/sstraust/eventplanner/eventplannerjs/node_modules/@ionic/core/node_modules/@stencil/core/internal/client/index.js
  {:line 1, :column 1, :message "The file could not be parsed as JavaScript."}

RuntimeException: INTERNAL COMPILER ERROR.
Please report this problem.

file uses import() with unsupported arguments and cannot be processed
  Node(DYNAMIC_IMPORT): /Users/sam/sstraust/eventplanner/eventplannerjs/node_modules/@ionic/core/node_modules/@stencil/core/internal/client/index.js:81:9
[source unknown]
  Parent(GETPROP then): /Users/sam/sstraust/eventplanner/eventplannerjs/node_modules/@ionic/core/node_modules/@stencil/core/internal/client/index.js:87:4
[source unknown]

**Comment by thheller** [comment]
Unfortunately this is an internal "error" of the Closure Compiler. Not much I can do about this from the shadow-cljs side.

It doesn't like this particular nonsense, which judging by the tool specific comments already required special tweaks to work in other tools. There is no such setting the Closure Compiler though.

```js
  /*!__STENCIL_STATIC_IMPORT_SWITCH__*/
  return import(
    /* @vite-ignore */
    /* webpackInclude: /\.entry\.js$/ */
    /* webpackExclude: /\.system\.entry\.js$/ */
    /* webpackMode: "lazy" */
    `./${bundleId}.entry.js${BUILD4.hotModuleReplacement && hmrVersionId ? "?s-hmr=" + hmrVersionId : ""}`
  ).then((importedModule) => {
    if (!BUILD4.hotModuleReplacement) {
      cmpModules.set(bundleId, importedModule);
    }
    return importedModule[exportName];
  }, consoleError);
```

You can use [:js-provider :external](https://shadow-cljs.github.io/docs/UsersGuide.html#js-provider-external) and use one the tools that supports this (e.g. webpack/vite) if you must use these packages.

**Comment by thheller** [comment]
FWIW I should have been more clear calling this an "error" in the Closure Compiler. I put it in quotes since it isn't actually an Error. It is just unsupported. It fails "early" in shadow-cljs, so that it doesn't fail later when the closure compiler is actually processing it, or even later when the runtime runs into it.

This is the error you'd otherwise get:
```
--- node_modules/@stencil/core/internal/client/index.js:168
Dynamic import expressions cannot be transpiled.
```

This is just overall a pattern that webpack invented so that it becomes able to bundle/process dynamc imports. I have no plans of adding support for it. So, even if some workarround/fix was added so the Closure Compiler ignores it, it would just fail at runtime.

The best option is to process it with something that actually understands what this is supposed to do. Hence my link to `:js-provider :external`.
