### ISSUE TITLE
Cannot require promesa promises library

### ISSUE THREAD

**Issue by trieloff** [thheller/shadow-cljs#136]
I've also filed this under funcool/promesa#54 but assume that this is a shadow-cljs problem.

I have a small program that depends (via funcool/httpurr) on promesa. Promesa [imports bluebird as org.bluebird](https://github.com/funcool/promesa/blob/547d01652f335df18d4f2950efc8e7caba416fbb/src/promesa/impl.cljc#L28), which is packaged [using externs](https://github.com/funcool/promesa/blob/0bd03db257dd95b520fe231eea62c46973be1481/assets/deps.cljs).

When requiring httpurr in my ClojureScript file:
```clojure
(ns onto.server
  (:require [httpurr.client :as http]
            [httpurr.client.node :refer [client]]))
 
(defn main [args]
  (println "hello")
  (+ 1 1))
```

and expressing the dependency in `shadow-cljs.edn`
```clojure
{:source-paths
 ["src"]
 :dependencies
 [
   [funcool/httpurr "1.0.0"]
 ]
 :builds
 {:app {
   :target :node-script
   :output-dir "target"
   :output-to "onto-server.js"
   :main onto.server/main
 }}}
```

the compile fails
```bash
$ shadow-cljs compile app  
shadow-cljs - config: /code/…/shadow-cljs.edn version: 2.0.77
shadow-cljs - starting ...
[:app] Compiling ...
The required namespace "org.bluebird" is not available, it was required by "promesa/impl.cljc".
```

because it can't find `org.bluebird`. Is there a way to alias `bluebird` as `org.bluebird` either in `package.json` or `shadow-cljs.edn`?

**Comment by thheller** [comment]
Promesa bundles a `:foreign-lib` but `shadow-cljs` no longer supports [`:foreign-libs`]
(https://code.thheller.com/blog/shadow-cljs/2017/09/15/js-dependencies-going-forward.html#breaking-change-removing-foreign-libs-support).

I added the ["migration"](https://github.com/thheller/shadow-cljsjs/blob/master/src/main/org/bluebird.cljs) to use the `"bluebird"` `npm` package instead. Things should just work if you use `shadow-cljs@2.0.87`. You will need to `npm install bluebird` since `promesa` does not declare the `:npm-deps` for it.

**Comment by trieloff** [comment]
Thank you!

**Comment by trieloff** [comment]
In the future, is there a way to write migrations myself and make a pull request?

**Comment by thheller** [comment]
Yes, I started the `shadow-cljsjs` project for this purpose.

https://github.com/thheller/shadow-cljsjs
https://github.com/thheller/shadow-cljsjs/blob/master/src/main/org/bluebird.cljs

You can also create those files in your project, they just need to be on the classpath. PRs are very welcome though.
