### ISSUE TITLE
[Discuss] several use cases different from a single server

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#147]
Continuing the discussion from https://clojureverse.org/t/tricks-to-make-clojure-faster/1176/8

> Why is that not one project with 2 builds? Which would mean one server.

[cumulo-workflow](https://github.com/Cumulo/cumulo-workflow) is a collection of code I used to make tiny realtime apps, which mean I need a server to sync data among all clients, based on the single source of truth on server. So there are two parts: 1. a webserver serving WebSockets and runs in Node.js , 2. a browser app. They are using most different dependencies on [server](https://github.com/Cumulo/cumulo-workflow/blob/master/server/shadow-cljs.edn) and on [browser](https://github.com/Cumulo/cumulo-workflow/blob/master/app/shadow-cljs.edn). So I started two shadow-cljs servers to watch/compile them.

> You can use shadow-cljs clj-run some.build/fn to run separate tasks one after the other which I also mentioned in my post. Again: one server, you just need to adopt the mindset of not having a command line do one thing after the other but instead calling clojure functions one after the other.

Currently shadow-cljs works as a compiler, rather than a task manager. And I was following some npm practices of writing npm scripts and use as a task manager tool, instead of using that from Clojure side:

```js
    "del": "rm -rf dist/*",
    "release": "shadow-cljs release browser",
    "compile-ssr": "shadow-cljs compile ssr",
    "html": "node target/ssr.js && cp entry/manifest.json dist/",
    "build": "yarn del && yarn release && yarn compile-ssr && yarn html"

    "cdn": "rsync -avr --progress dist/* tiye.me:cdn/coworkflow",
    "tiye": "rsync -avr --progress dist/{index.html,manifest.json} tiye.me:repo/mvc-works/coworkflow/",
```

If there is a task manager tool, I would like to migrate my scripts.

**Comment by thheller** [comment]
Without going into too many details the only "hard" part about a shared server is the classpath management related to macros. `.cljs` files themselves are very easy to handle but since `.clj` (and `.cljc`) files need to adhere to java classpath semantics things get weird when shared.

While it is generally recommended to "namespace" CLJS code some users appear not to do that and use generic names like `app`, `server` or `frontend` (eg. https://github.com/circleci/frontend). Names need to be unique on the classpath so this wouldn't work if shared.

I need to figure out if isolation is possible while code like clojure+cljs is still shared.

**Comment by thheller** [comment]
Not going to pursue a single shared server for all projects. It is a nightmare to deal with `:dependencies` and AOT as it is already.

**Comment by jiyinyiyong** [comment]
I'm fine with current performance.
