### ISSUE TITLE
`output-dir` vs `output-to`

### ISSUE THREAD

**Issue by pesterhazy** [thheller/shadow-cljs#159]
Reading the README, I was confused as to why some targets require a `output-dir` key, others an `output-to` key.

Both seem to be directories. Maybe rename to the same key (with an alias to retain backward compatibility)?

N.b.: these are my first 5 min with shadow-cljs - I'm just logging my "first timer" gotchas.

**Comment by thheller** [comment]
`:output-to` is used whenever the target output is a single file (eg. `:node-script`), it always points to a file.

Browser targets in general output many files (especially during development) so it requires `:output-dir` and derives further filenames from `:modules`. It does not even support `:output-to` (contrary to other CLJS tools).

spec does some minimal checks ensuring that at least the required config has been provided.

You'll probably run in to a few other gotchas since you have used other CLJS tools before and some things don't apply 1:1 to shadow-cljs. Each config key has a distinct meaning and should always do the same thing but the keys required for each `:target` may be different.

**Comment by pesterhazy** [comment]
Makes sense.

Perhaps what I'm looking for is a piece of documentation that states that this key means outputting to a file, not a directory — it's best not to leave users guessing.
