### ISSUE TITLE
dev profiles

### ISSUE THREAD

**Issue by kurtharriger** [thheller/shadow-cljs#166]
I know the build configuration can have :release profiles, but what about profiles for dependencies and source-paths? 

Can these be updated with profiles or overridden at the build level?  
I was thinking about adding dev/user.clj with commands like start-repl so I don't need to copy and paste (shadow.cljs.devtools.api/nrepl-select :browser) anymore.  

I also think cider-nrepl should go in a dev dependencies profile rather than just :dependencies.  Perhaps it doesn't matter that much since a release bundle wont have dependencies thus everything is a dev dependency, but I still find it somewhat useful to be explicit about which dependencies are included in the final artifact vs which are just there for development.

**Comment by thheller** [comment]
That is a Clojure/JVM idiom, we do not need it for CLJS. I even consider it an anti-pattern that some people abuse this to "swap" namespaces via the classpath. It does not matter if you have `dev` stuff on your classpath at all times since the CLJS build itself will not include them.

`:source-paths ["src/dev" "src/main" "src/test"]` etc. Just put it all in there, it does not matter for CLJS.

Profiles will be available via `deps.edn` once I add support for `tools.deps`. If you want you can "tag" your `:dependencies` via metadata. It doesn't have any effect on `shadow-cljs` but maybe helps the human eye?

```
{:dependencies
 [[re-frame "0.10.3-alpha2"]
  ^:dev [day8.re-frame/trace "0.1.14"]
  ^:dev [binaryage/devtools "0.9.8"]
  ^:dev [binaryage/dirac "1.2.24"]
  ^:dev [cider/cider-nrepl "0.16.0"]]

 :source-paths ["dev"
                "src/cljs"
                "src/cljc"]}
```

I might be open to adding a `:dev-dependencies` as a "simple" fix over full blown profiles as well.
