### ISSUE TITLE
strict mode

### ISSUE THREAD

**Issue by kurtharriger** [thheller/shadow-cljs#171]
I tried to require "viz.js" http://viz-js.com/ and got the following errors.  As a workaround I'll just throw the script tag and use js interop, but wondering if there is another solution? 

```
Closure compilation failed with 7 errors
--- node_modules/viz.js/viz.js:47
Object literal contains illegal duplicate key "stackAlloc", disallowed in strict mode
--- node_modules/viz.js/viz.js:47
Object literal contains illegal duplicate key "stackSave", disallowed in strict mode
--- node_modules/viz.js/viz.js:47
Object literal contains illegal duplicate key "stackRestore", disallowed in strict mode
--- node_modules/viz.js/viz.js:47
Object literal contains illegal duplicate key "establishStackSpace", disallowed in strict mode
--- node_modules/viz.js/viz.js:47
Object literal contains illegal duplicate key "setThrew", disallowed in strict mode
--- remaining errors ommitted ...
```

**Comment by kurtharriger** [comment]
It turns out I added the wrong library, viz.js is one of the graphviz for the web hack libraries I found but probably not the one I'm going to use as the one linked above vis looks like more of what I wanted.  After updating the dependency vis does seem to compile so I guess my problem is solved... but I suppose there is still an open question is strict mode required?

**Comment by kurtharriger** [comment]
I thought vis had a nicer api and appeared it would do the same thing, but after spiking I can't seem to configure the layout do what graphviz does by default and the results are unusable in my case so I probably will go back to using viz.js

**Comment by thheller** [comment]
I saw this before. The issue is that I currently process every file from `node_modules` via the Closure Compiler `:simple` to minify it. `viz.js` is already minified so this really isn't required.

The problem is that `viz.js` exports certain properties multiple times, as the error messages show.

Basically they

```
module.exports = {
  "stackAllow":...,
  ...,
  "stackAlloc":...,
};
```

Just as Clojure does not allow `{:foo 1 :foo 1}` the JS `strict` mode does not allow that either. The file however should not be in `strict` mode and I'm not sure why the Closure Compiler thinks it is.

Either I should add an option to disable further processing/minifying of certains `node_modules` files or figure out why its setting `strict` and whether I can disable it.
