### ISSUE TITLE
confusions on generated files and folders

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#18]
* compiled js in `node_modules/shadow-cljs` occasionally missing.
  Perhaps `yarn install` cleared those files. I encountered it for several times.

* unexpected new folders
 I saw `.shadow-cljs/` `target/shadow-cache/` `target/shadow-build/` generated automatically. Why isn't it only one file?

**Comment by thheller** [comment]
`yarn` seems to delete the entire `node_modules` folder when you change a dependency. Don't think there is anything we can do about that. I'll probably add a watch in `--dev` mode to re-compile when the `node_modules` folder disappears.

I need to find a better strategy for all those cache files. See https://github.com/thheller/shadow-cljs/issues/8. The `.shadow-cljs/lein-classpath.txt` is generated when there is a `project.clj` in your directory and the `lein` classpath is used.

I may put everything into `./.shadow-cljs/...` but could also use something like `~/.shadow-cljs/<projecthash>/...`. Need to check where `webpack` and other JS tools put their cache files.

It should only be one directory, preferably one you don't have to re-ignore every time.

I will also add a `"output-dir"` config option to `package.json` to make the `./node_modules/shadow-cljs/` path optional.

**Comment by thheller** [comment]
I was just running `shadow-cljs --dev` in an app created by `yarn create react-app hello-cljs`. It doesn't seem to reload code changes from `node_modules`. `webpack` picks it up nicely by default though.

**Comment by thheller** [comment]
#8 fixed the multiple paths issue

Still need to work around `yarn` nuking the `node_modules/shadow-cljs` folder.

**Comment by shaunlebron** [comment]
fyi, webpack allows [aliases](https://webpack.js.org/configuration/resolve/#resolve-alias) to allow virtual directories like this.  doesn't help the tool-agnostic case though

**Comment by thheller** [comment]
All cache files are written to `target/shadow-cljs/...` (currently not configurable).

All output is written to `:output-dir` or `"output-dir"` in `package.json`. For the `--npm` mode (implicit when using `shadow-cljs` CLI) it defaults to `node_modules/shadow-cljs`. You can use anything you'd like but it either requires configuration or using a relative path.

`require("shadow-cljs/demo.foo")` only works because and the node resolve rules. If `:output-dir` is a different directory you'd have to use `require("../../the-dir/demo.foo")`.
