### ISSUE TITLE
Watch doesn't work on Windows + docker volumes

### ISSUE THREAD

**Issue by Lokeh** [thheller/shadow-cljs#210]
The situation I'm dealing with:

I'm currently developing an app that needs to work on both Windows + Mac. To ease some of the friction getting the development environment setup, I've put it inside of a docker container running Linux.

The problem is that [on windows, filesystem events do not work with shared volumes on docker](https://github.com/docker/for-win/issues/56). Basically, the FS events are emitted on the host platform but not the container that has mounted the directory as a volume.

My current thinking is I should do one of two things:

1. Fork shadow-cljs and add a polling option to the watcher that I can enable for Windows
2. Create a separate client + server program that listens for the fs events on the Windows host and sends them to the server in the container, that triggers some action that will cause inotify to emit a proper event.

Any thoughts?

**Comment by thheller** [comment]
You are building an app for Windows + Mac but to make development easier you are introducing Linux to the mix? Wouldn't it be easier to just work on Windows or Mac directly? Why add another completely different system?

If I understand you correctly shadow-cljs is running inside the docker VM and you editing the files locally which are also mounted using a shared folder inside the VM?

It should be fairly simple to add a polling file watcher since there are already 2 different file watching implementations. Adding a config option to let you select a third would not be hard at all.

**Comment by thheller** [comment]
I currently have 2 different watch implementation since the default JDK watcher on OSX used polling and was way too slow. The hawk based version is currently the default on OSX/Linux. On Windows the JDK watcher works just fine so I'm using that. I never tested how well the JDK watcher works on Linux.

First we should confirm that the default JDK watcher works in your setup since it might just be hawk not working.

**Comment by thheller** [comment]
Please run `shadow-cljs clj-repl` inside the VM.

```
(require '[shadow.cljs.devtools.server.fs-watch-jvm :as fs-watch])
(require '[clojure.java.io :as io])

(def x (fs-watch/start [(io/file "src")] #{"cljs"} prn))
````

Then inside your usual editor edit/save a `.cljs` file. If something is printed inside the REPL window the watch seems to trigger?

**Comment by Lokeh** [comment]
I can confirm that running `fs-watch-jvm` inside the VM against a directory that is mounted using a shared folder, and then modifying the file on the host, does not trigger any message.

Poking the file on the container *does* elicit a message. In the container, I did ` chmod 777 dev.cljs` inside of the shared src folder and received the message:

```
[{:dir #object[java.io.File 0x6e878d82 "src"], :name "
web/experience/dev.cljs", :ext "cljs", :file #object[java.io.File 0x6ab8148a "s
rc/web/experience/dev.cljs"], :event :mod}]
```

**Comment by thheller** [comment]
Try setting `:fs-watch {:watcher :polling}` in your `shadow-cljs.edn` config.

You can also set this in `~/.shadow-cljs/config.edn` for CI only.

**Comment by Lokeh** [comment]
Works! :+1:
