### ISSUE TITLE
UMD dependencies

### ISSUE THREAD

**Issue by shaunlebron** [thheller/shadow-cljs#215]
I'm opening this issue to explore the idea, rather than posing a real solution.

motivated by https://github.com/thheller/shadow-cljs/issues/212#issuecomment-369668974

__Problem__: How do you specify dependencies on other UMD packages when exporting a UMD yourself?

__Example__: My `parinfer-codemirror` library is a UMD library that depends on another UMD library `parinfer`.  You can see this dependency specified in three different ways [here](https://github.com/shaunlebron/parinfer-codemirror/blob/1.4.2/parinfer-codemirror.js#L8-L22). THEN, the `parinfer` symbol is made available via a wrapped function parameter [here](https://github.com/shaunlebron/parinfer-codemirror/blob/1.4.2/parinfer-codemirror.js#L23).

__Proposal__: Add a `:umd-dependencies` build option? I think it can be injected into the template in a straightforward way.

__Open question__: How do we make those resolved UMD dependencies available to our CLJS code?  Something like a `goog.provide` to expose that in some way to cljs?

**Comment by thheller** [comment]
One of the assumptions `:node-library` makes is that it can `require` at runtime for any deps. This can't work in the browser which is why the UMD wrapper is usually providing these.

UMD in general is not a great idea for CLJS since each build will include its own `cljs.core` (and other duplicates). Having two CLJS UMD builds in one page would be very inefficient. I'm a little hesitant adding this since you really should not start combining multiples of theses on the same page. Writing jQuery-ish plugins that you just include via a `<script>` tag is just not a thing you can do properly with CLJS. Including multiple CLJS UMD builds via webpack would be equally bad. Its also bad for `:node-library` but since code size is usually not a factor there its not that bad.

Also I think UMD is pretty much a dead format and should be replaced by ES6 pretty soon (although the same problem still exists there).

What is your use case for this?

The only information we'd need for the configuration is which require maps to which global.

```
(ns parinfer.codemirror
  (:require
    ["codemirror" :as cm]
    ["parinfer" :as par]))

(par/doThing cm)
```

```
:umd-dependencies
{"codemirror" "CodeMirror"
 "parinfer" "parinfer"}
```

With this the compiler would have enough information to generate the proper UMD wrapper.

The same source file would build just fine in normal `:browser` or `node` builds where it could use the actual `npm` packages.
