### ISSUE TITLE
request for a change log

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#22]
easier to track updates, like https://github.com/anmonteiro/lumo/releases

**Comment by thheller** [comment]
I'll try.

I developed `shadow-build` and now `shadow-cljs` while using it. Every feature I implemented exists because I wanted it for "work". Initially I wanted the `code-splitting` though modules. The very first public commit of `shadow-build` already supported that (https://github.com/thheller/shadow-build/commit/ec47b063ed8e0f7f2dd2e5afd750d53de7a2a362) on `Dec 14 2013`. :)

I never talked much about it in public since since marketing is not something I like doing. It works really well for me and that is good enough.

Improving the usability is something I wanted to do for a while and `shadow-cljs` is my attempt at that. Documentation is currently the main issue and I am going to need help with that. I know how to use this thing, I don't know what questions people may have unless they are asked.

A change log makes sense but it is probably better to first document what is already there.

**Comment by jiyinyiyong** [comment]
Maybe a change log not in that kind of details. I'm following the npm package`shadow-cljs` these weeks and found it hard to track your updates. Probably A simple release notes with links to the major changes would be enough for current stable.

**Comment by jiyinyiyong** [comment]
> I never talked much about it in public since since marketing is not something I like doing. It works really well for me and that is good enough.

Thought for a while. I think this situation somehow hurt me. I'm living in Shanghai, which is far from the area Clojure Conf is held or where Clojure's author lives. However, ClojureScript documentation was kind of a disaster years ago for beginners like me.

SEO(or marketing) is somehow turning into part of the user experience of modern programming languages and frameworks. JavaScript is growing very rapidly despite the fact it **was** a poorly designed language, after so many developers involved. I just want to say marketing matters for a community.

**Comment by thheller** [comment]
I'm very aware that documentation is important but I'll need help with that.

Everyone can start by asking questions, I don't know what to document unless someone asks.

I started a [changelog](https://github.com/thheller/shadow-cljs/blob/master/CHANGELOG.md) and will try to maintain it.
