### ISSUE TITLE
provide conflict when renaming files

### ISSUE THREAD

**Issue by dum3ng** [thheller/shadow-cljs#231]
Say have two namespaces `app.one` and `app.two` and two responding files `app/one.cljs` and `app/two.cljs`, when I deleted the `one.cljs` file, and rename the `two.cljs` to `one.cljs` and also change the namespace,  shadow-cljs will report the warning 
```
provide conflict for #{app.two} provided by app/one.cljs and {"/app/two.cljs" nil}
```
 and finally compiled failed.

Is this related to how shadow-cljs do  build cache? And it also behave a little error-prone  when I save multiple files at the same time with newly created files.

**Comment by thheller** [comment]
Which OS are you running on? I noticed that deletes were not detected properly on OSX but never investigated why. This would cause such issues though.

**Comment by dum3ng** [comment]
yes on OSX.

**Comment by lwhorton** [comment]
So I bumped into (probably) this same issue today. The incident took place when I merged into a git branch into master after rebasing. That branch deleted and renamed quite a few files. Anyone who tried to pull down the newest master ran into a whole host of issues -- the `conflict` above, as well as a load of `cljs.core some.namespace.foo not found`. The only way we could resolve the issue was to delete entirely the repo and run a fresh git checkout. I'm not really sure still the actual root cause of the problem.

**Comment by thheller** [comment]
I [recently](https://github.com/thheller/shadow-cljs/commit/5e6dae3ec9143560c76ac6ddd565dc08e63879c5) finished a rework of the fs-watch stuff overall. Deletes and moves easily confused the compiler which should be fixed now. Will be in the next release.
