### ISSUE TITLE
Symbol conflict: module$node_modules$object_assign$index already provided

### ISSUE THREAD

**Issue by verma** [thheller/shadow-cljs#237]
I have a project with the following two dependencies(among others):

    create-react-class@15.6.3
        - object-assign@4.1.1

    react-dates@16.4.0
        - object.assign@4.1.0

When I try to compile this project, I get the following error:

```
[:dev] Compiling ...
symbol module$node_modules$object_assign$index already provided by [:shadow.build.npm/resource "node_modules/object-assign/index.js"], conflict with [:shad
ow.build.npm/resource "node_modules/object.assign/index.js"]
{:provide module$node_modules$object_assign$index, :conflict [:shadow.build.npm/resource "node_modules/object-assign/index.js"], :resource-id [:shadow.buil
d.npm/resource "node_modules/object.assign/index.js"]}
ExceptionInfo: symbol module$node_modules$object_assign$index already provided by [:shadow.build.npm/resource "node_modules/object-assign/index.js"], confl
ict with [:shadow.build.npm/resource "node_modules/object.assign/index.js"]
        clojure.core/ex-info (core.clj:4739)
        clojure.core/ex-info (core.clj:4739)
        shadow.build.data/add-provide (data.clj:71)
        shadow.build.data/add-provide (data.clj:66)
        shadow.build.data/add-provides/fn--16167 (data.clj:84)
        clojure.core.protocols/iter-reduce (protocols.clj:49)
        clojure.core.protocols/fn--7839 (protocols.clj:75)
        clojure.core.protocols/fn--7839 (protocols.clj:75)
```
The only reference to this that I could find is here (sorry for the cached link, this is the only working link I could find):

https://webcache.googleusercontent.com/search?q=cache:tRfbycHV8FAJ:https://clojurians-log.clojureverse.org/shadow-cljs/2017-11-02.html+&cd=2&hl=en&ct=clnk&gl=us&client=firefox-b-1-ab

As suggested in that text I tried:

```
:js-options {:resolve {"object.assign" {:target :npm :require "object-assign"}}}
```

This seems to allow my program to compile.  However, since I opted for one package over the other, I am not sure what other deps might go missing: something provided by `object.assign` but not by `object-assign`.

Here it seems quite harmless since these seem to be poly-fills and cannot vary too much, but a conflict in a larger context could be a problem?

**Comment by thheller** [comment]
The solution you found is currently the "best" solution IMHO.

One part of the problem is that Closure assigns the same variable name `module$node_modules$object_assign$index` to both `node_modules/object-assign/index.js` and `node_modules/object.assign/index.js`. I could work around that by changing the filename before handing it Closure so it picks a different name.

The other problem however is that both of these create `Object.assign` (if it doesn't exist). So if I was to "resolve" the naming conflict you'd end up in a situation where it isn't clear which polyfill gets picked since it then depends on which is loaded first.

Either way the problem is pretty annoying. Fixing the naming conflict just hides the underlying issue without warning and will just load both.

Polyfills at the library level is just a bad idea overall but I guess the JS world doesn't care. Closure actually has a neat way for polyfills built-in but that would just add a third polyfill since that is not aware of the others either ...

`¯\_(ツ)_/¯`

**Comment by verma** [comment]
Oh :(

This sounds terrible.  I agree with you that manual resolution that the suggested solution does is right now the "best" solution we have, at least we know which module is being loaded.

I guess we just need to wait for a more severe case of this problem and take it from there.

Thanks for getting back so promptly.
