### ISSUE TITLE
:module-hash-names for web worker module

### ISSUE THREAD

**Issue by mjmeintjes** [thheller/shadow-cljs#267]
**My situation:**
I'm trying to build an app using 2 modules - main and web worker.

I use `:module-hash-names true` to auto append a file hash to the final release files, which means I get main.HASH.js, and worker.HASH.js.

**My problem:**
To use the web worker, I include it in my project by calling (js/Worker. "/js/compiled/worker.js").

Unfortunately, this doesn't work for the release build, because the worker filename now has a hash appended to it.

**Possible solutions I've thought about:**
 - Replace the hash with a guid, and then include the generated module file names as closure-defines (I'm already doing this to get the asset-path for the worker file's path).
 - Allow to make certain modules not use module-hash-names

**Comment by thheller** [comment]
There is one problem with this that I haven't figured out how to solve yet.

> Writing a hash of something into another part of the code changes the hash of that code.

You write the hash of `worker` into `main`, this changes the hash of `main`. The hash of `worker` changes which then in turn also changes `main` although no other changes in `main` were done. This means that the whole point of the hash (caching) is now nullified.

Simply put there is no way to get the hash of the worker into the code without breaking the promise of `:module-hash-names`. It would then be better to not use hashed names at all but instead use the usual HTTP negotiation via either `if-modified-since` and/or `etag`.

So in theory the path to something must *always* come from outside the build but there is no super convenient way to get the info there. The `shadow.loader` has the same problem as well as the planned "assets" supports. Basically all of them always invalidate the base module cache. In practice however the base module will contain `cljs.core` and is likely to be the largest of them so caching is most desirable.

The most useful solution so far seems to be to build a "smaller" base module that only contains `shadow.loader` and the URIs for the other stuff. It then initiates loading of the others. This however makes the build config really complicated and I'm not sure this approach would actually be faster than doing the HTTP negotiation I mentioned above.

**Comment by thheller** [comment]
Yes, that is one way to do it. You find find the hashed name in the [manifest](https://shadow-cljs.github.io/docs/UsersGuide.html#BrowserManifest).

I typically have a `<script>my.app.init({worker:"/some/path.hash.js", anything: "else"});</script>` to initialize my app in the HTML context. Might work for you as well.

**Comment by thheller** [comment]
Closing since I thing using file hashes in output files is fundamentally flawed and cannot be fixed (ie. writing the hash into a file changes the hash of that file, cascading all the way until all hashes have changed).
