### ISSUE TITLE
Azure app and node REPL

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#312]
Hi Thomas!

I am working with the `:azure-app` target and if I understand right, I cannot use the REPL directly with it.
So ok I am now starting a `shadow-cljs node-repl`, I see the prompt in the terminal and try to connect to it with Cider.

This is what happens though when I try to select the worker:

```cljs
shadow.user> (do (require 'shadow.cljs.devtools.api) (shadow.cljs.devtools.api/nrepl-select :app))
shadow.user> 
[:no-worker :app]
```

Even at the terminal I have problems requiring things, with time outs and `TypeError: Cannot read property 'XYZ' of undefined`, which probably means that the runtime has not loaded my things in it.

I also tried the very wrong way of just adding

```clojure
(cond->
        (:worker-info state)
        (-> (repl/setup)
            (shared/inject-node-repl config)))
```

To the target directly but because no `:main` is set then nothing really happens. Any other advice on how to use the REPL?

**Comment by arichiardi** [comment]
This could be extended to all the `:target`s that do not have a `:main` entry point. I guess a developer would still want to have a REPL in those cases so maybe a `:repl` target could help setting it up by picking a `:main`?

Just one idea, following up also https://github.com/thheller/shadow-cljs/pull/307#issuecomment-396753815 and https://github.com/thheller/shadow-cljs/pull/307#issuecomment-396868878. /cc @kurtharriger.

**Comment by thheller** [comment]
I just enabled the REPL for `:azure-app` targets since they have clearly defined entry points that is not a problem. It is also only a node process that does not modify the code in any way so there should not be a problem at runtime.

`node-repl` is a *generic* REPL for `node`. It is identical to `clj` in that it has no code loaded by default. Your app will not be running and none of your could will have been compiled. It is independent of any build. You start a `node-repl` and `(nrepl-select :node-repl)`. You do not `(nrepl-select :your-app)` to use it since that has nothing to do with it. It has different purposes and it may or may not fit what you are trying to do.

**Comment by arichiardi** [comment]
Thanks!
