### ISSUE TITLE
tutorial deploying package to clojars/npm

### ISSUE THREAD

**Issue by zcaudate** [thheller/shadow-cljs#327]
I'm pretty new to shadow-cljs and it's amazing. I've been looking around trying to find a guide on how to deploy packages on npm and clojars.

Firstly, is it possible? and if so, how can I do it?

**Comment by thheller** [comment]
For `npm` you can follow the [npm publish](https://docs.npmjs.com/cli/publish) docs. You pretty much only need a `package.json` and some JS files produced via `shadow-cljs release`.

Publishing to Clojars is not currently supported. I currently use and recommend `lein` for this. It will be supported eventually but I didn't have time to work on it yet.

**Comment by zcaudate** [comment]
hmmm... well if you're interested, I've got a packaging library that's lightweight and independent of the pomegranate/leiningen stack:

https://github.com/zcaudate/lucidity/blob/master/src/lucid/package.clj

i use it mainly to deploy artifacts in repl.

**Comment by thheller** [comment]
I currently don't have time to integrate something like that but there is nothing stopping you from using your package from the `shadow-cljs clj-repl` directly.

You could also add a `(defn -main [...])` to your package and then call `shadow-cljs run lucid.package with some args`. Bonus points for that since it works directly via `clj -m lucid.package` as well.

**Comment by zcaudate** [comment]
It's not a trivial thing to do. I'm a little bit time poor as well but will have a go.

**Comment by arichiardi** [comment]
@zcaudate your lib is awesome btw.

I think shadow could provide a way to identify/select the files to zip up in the jar you will be deploying.
This is probably the only thing that I would not know how to get but probably shadow has that somewhere, just need to expose it. Maybe as result of `shadow/release` or something?

**Comment by zcaudate** [comment]
@arichiardi thanks =)

there's a couple of steps that's needed:

1. a list of files to zip up 
- this is done here: https://github.com/zcaudate/lucidity/blob/master/src/lucid/package/jar.clj#L22-L53 
- files need to be customised for the shadow directory format

2. creating a project map generating the pom.xml file:
- this is done here: https://github.com/zcaudate/lucidity/blob/master/src/lucid/package/pom.clj. 
- the major hurdle is  generating the project map. I'm reading the data from project.clj at the moment so that needs to be customised for shadow

3. signing and authentication
- this is done here: https://github.com/zcaudate/lucidity/blob/master/src/lucid/package.clj#L54-L69
- all security stuff is in one module https://github.com/zcaudate/lucidity/blob/master/src/lucid/package/privacy.clj
- this is the weakest module because it doesn't shell out to gpg and only supports gpg v2.0 and lower before they removed the the secret keyring file (https://www.gnupg.org/faq/whats-new-in-2.1.html)
- the good thing is, it's fairly straightforward to add in the features and it can be customised for cleartext keys (which is good for testing)

4. deploy/install
- this is done here: https://github.com/zcaudate/lucidity/blob/master/src/lucid/package.clj#L30-L52
- install is pretty straight forward, deploy needs the security stuff to work

**Comment by thheller** [comment]
`shadow-cljs` doesn't need to do anything regarding the packaging for `maven`. There is no compilation step involved when building a library jar as it only contains the sources.

`shadow-cljs` does not yet have any concept of profiles which would be required to at least separate dev-only dependencies from actual dependencies and source-paths. If the dependencies instead are listed elsewhere, together with all other .jar related metadata, the tool would be overall much more usable since it would work with `tools.deps` or even `lein`.

**Comment by zcaudate** [comment]
@thheller: If that's the case, then it's definitely better to make it independent. I was pretty happy with the leiningen project.clj format but I just couldn't stand how messy the pomegranate code was. now that there's boot, deps.edn, etc... it doesn't make sense to have another format.

@arichiardi: yeah... cljs adds a whole lot more complexity, especially if there is dependency resolution for both maven and npm.  Are you packaging to a jar?

**Comment by thheller** [comment]
When I find the time I'll eventually add support for this but priority wise its not very high on my list since there are solutions that are good enough. Adding a secondary `project.clj` to get access to `lein deploy clojars` is good enough for now. You don't actually have to use `lein` for anything else.

**Comment by arichiardi** [comment]
Agree it is good enough but in the spirit of using as less tools as possible I really like @zcaudate's idea.
One could you `clj` + `shadow` only which is awesome.

I could help with this, just need some hint on where to start.

**Comment by zcaudate** [comment]
@arichiardi: The easiest thing to do is to create some examples. Let me have a think.

**Comment by arichiardi** [comment]
It seems Clojure is fragmenting in many small tools that do each a little piece and that is good.

The problem of building an artifact is that then you need to collect all the pieces and zip/jar up.

Boot is great at this because of its filesystem abstraction. Whatever is on the classpath after the pipeline will be jarred by the uberjar task. You can see an analogy here - boot tasks are not `clj` processes that modify the filesystem. How can they share the file map? Well, ClojureScript now has the `-co` parameter which can read files and merge the compiler option maps you pass in input:

> -co, --compile-opts edn Options to configure the build, can be an EDN string or system-dependent path-separated list of EDN files / classpath resources. Options will be merged left to right.

This is a great approach and I feel it might be a good way for tools to communicate with each other - shadow could emit a `shadow-out.edn` map that this futuristic tool merges in.

Dunno, brainstorming here.

**Comment by zcaudate** [comment]
@arichiardi: I've been baited because this is something that I feel pretty strongly about. I've got my own opinion about fragmentation and it has to be balance with two factors: Upkeep, Interface

Upkeep:
- I used to maintain 15 repositories. Now I maintain 3 but use automation to generate well over 100 artifacts. 
- I don't like the fact that every developer has to come up with some `unique` name for a <100 line project. 
- I don't like the fact that because it's a small project, developers don't feel the need to add tests so the quality of the project is generally of a lower standard than the java library they are usually wrapping. In that case, I'd rather work with the java library and use my own tools.
- I really don't like the fact that for things like configuration, there are 50 different libraries that read in config files differently. In this case, I'll follow the trend write my own 51st config `library` (which is around 20 lines of code based around `read-string`. 
- However, the difference is that I'll pop it into one of my monorepos and let automation do the work of generating unit test scaffolding, docstrings, documentation and deployment artifacts, giving better quality of code at a lower cost of maintenance.

Interface:
Fragmentation that is good is when a widely used interface is respected by a lot of libraries,
- json
- clojure's edn
- ring spec
- clj-http spec
- leiningen spec

It's sickening when there's 2 or more competing standards:
- clj component frameworks
- clj schemas (I'm not even going there. I'm sticking to readability and unit tests)
- cljs react frameworks
- dependency tools (it's horrible in the js world and this issue I had recently https://github.com/zcaudate/hara/issues/40 makes me laugh. I think clojure is fragmenting again)

Anyways, in terms of the boot filesystem abstraction, it shouldn't be a boot thing, it should be a filesystem thing. I wrote `hara.io.file` to deal with the inadequacies of clojure fs, because it's a general problem, not a boot specific one:
- http://docs.caudate.me/hara/hara-io-file.html#simulate

In terms of dependency tooling, even though boot and lein have different configuration semantics, they share pomegranate as their aether library. I just don't like the library. Pomegranate works, but it's not as well written as it should be. Aether is a huge library and sticking everything into one file (even if it's just a wrapper) is not the proper way to do it.
- https://github.com/cemerick/pomegranate/blob/master/src/main/clojure/cemerick/pomegranate/aether.clj

With lucid.aether, it has the following advantages:
- the structure of the Aether java package is preserved: https://github.com/zcaudate/lucidity/blob/master/src/lucid/aether/
- printable aether objects: https://github.com/zcaudate/lucidity/blob/master/src/lucid/aether/request.clj#L171-L177
- Better code readability (though this is sometimes subjective)

**Comment by zcaudate** [comment]
@arichiardi: I'm not worried about other people adopting my code. I'm worried about making my life easier. There is a difference between what's popular and what's promising, and the latter term is completely subjective - just go talk to a ruby guy.

Anyways... it'll be interesting to see what happens with deps.edn. I don't think it's a big deal. The fact that it does resolve dependencies across jar files is kinda offputting for me. It's good for an uberjar I guess.

**Comment by thheller** [comment]
FWIW `shadow-cljs` uses `pomegranate` for dependency resolution as well. Might switch to `tools.deps` at some point but for now it works well enough.

My opinion on the matter is that everything should be as declarative as possible. You could for example put `:lucid.package {:name "foo" :include ["src/main/**/*.cljs"]}` into the `shadow-cljs.edn` or `deps.edn` and then use `shadow-cljs run lucid.package` to automatically "find" either file and look for relevant info. Or you create a `lucid.edn`. I dislike `boot` since its anti-declarative and incredibly hard to extract the data. `project.clj` is a tiny bit better but still pretty bad if you just want to extract things. `shadow-cljs.edn` just like `deps.edn` is a just a map that you can read and work with. Packaging CLJS is also a whole lot easier than CLJ since there will rarely be any `.java` files to compile and you don't need to AOT anything (yet).

Maybe there already is a function out there that I could call with some data and that gives me a `.jar` in return. I don't know. `lucid.package` sounds close, I saw something in `pomegranate` as well. CLJS packaging is far easier than CLJ packaging and if there was such a function it should be pretty simple to hook up.

I'm excited about `tools.deps` and `deps.edn` since it makes dependencies declarative. I'm not excited at all about `clojure` or `clj` and prefer `lein` over that. I hope the community standardizes on `deps.edn` and `lein` just gets native support for reading it. One major hurdle for `shadow-cljs` still is tool support. Everything is so used to `project.clj` that I still can't open projects in Cursive properly with just `shadow-cljs.edn` but it is getting `deps.edn` support. I'm fine with `deps.edn` as a baseline so if you build something build it around that. The amazing thing about this is that `deps.edn` is just data so if you do not like `tools.deps` for some reason you could just write a different library that just re-uses the same data structure.

`tools.deps` makes dependencies declarative. `shadow-cljs.edn` makes the build configs declarative and provides the few standard "tasks" you want for CLJS development (eg. `watch`, `compile`, `check` and `release` and of course the REPL) so you do NOT have to roll your own via `cljs.main`. Some people like tweaking makefiles endlessly just like tweaking `emacs` configs. I personally just want something that works out of the box that I don't have to worry about breaking. For me currently that is `Cursive` with `lein` for CLJ and `shadow-cljs` for CLJS.

**Comment by zcaudate** [comment]
Thanks for your thoughts. I'll definitely take a closer look at shadow when I get more time. I'm working with figwheel at the moment - it's been a while since I've done any cljs and so I'm really impressed by the state of the ecosystem -  the cider/clojurescript integration is almost on par with clojure but I'd prefer something more lightweight. 

> Or you create a lucid.edn
No way. I prefer just one config file.

> project.clj is a tiny bit better but still pretty bad if you just want to extract things
http://docs.caudate.me/hara/hara-io.html#io-project

> Maybe there already is a function out there that I could call with some data http://docs.caudate.me/hara/hara-io.html#io-archive

> My opinion on the matter is that everything should be as declarative as possible
Agreed.  (boot < lein , react < angular < reagent/rum)

>  I hope the community standardizes on deps.edn and lein just gets native support for reading it
(-> "deps.edn" slurp read-string). kidding. I don't know. To me, it looks like clojure is going the way of apple in terms of the walled garden approach for development. It's not exactly the same because open source libraries can't be banned but having an 'official' version takes much of the mindshare of the original library away. To be honest though, the last feature after clojurescript that I got really excited about were reader macros and that was back in 1.6. Actually, the work on analysers and core.async are pretty impressive too... but I *heart* reader macros.

**Comment by zcaudate** [comment]
I realised that the `src` directory is currently hardcoded in https://github.com/zcaudate/lucidity/blob/master/src/lucid/package/jar.clj#L42

though the code for install/deploy is currently pretty short and so can be customised:
https://github.com/zcaudate/lucidity/blob/master/src/lucid/package.clj#L30-L52

**Comment by thheller** [comment]
When adding things to `shadow-cljs.edn` please make sure to use namespaced keys. Non-namespaced keys are reserved and I want to avoid conflicts if I ever decide to add something official.

**Comment by zcaudate** [comment]
hmmm. I'll take note.
