### ISSUE TITLE
Machine readable output for `watch` and `release`?

### ISSUE THREAD

**Issue by the-kenny** [thheller/shadow-cljs#345]
I'm in a position where I would like to have machine readable output for `watch` and `release`. As far as I know this isn't supported right now.

Do you have any prior work on this, or would you accept a Pull Request? I'd be happy to implement this.

**Comment by thheller** [comment]
Can you define what you mean by "machine readable output"? And what is your intent with such data?

**Comment by the-kenny** [comment]
We are mostly interested in errors and warnings generated by `release` in our CI pipeline. We basically want to make sure that nothing breaks from missing externs. 

A simple implementation would just add a key `:build-report` or similar, which would generate a EDN file containing information about the build. Another option would be extending `manifest.edn` with such data.

A more extensive implementation could add an option which would make all information printed by shadow-cljs machine readable, for example by switching to structured logging (while keeping human readable output via a translation layer).

**Comment by thheller** [comment]
Everything starts out as data and is turned human-readable later so it would be pretty trivial to expose the data instead of the string. The translation happens here: https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/build/log.clj

To make sure nothing breaks from missing externs you have to actually run the code. The compiler can never fully guarantee that everything works or warn about everything so I'm not sure where shadow-cljs can help there.

Can you create a "sample" of the data you'd want? What should be included? It will be trivial to add via build hooks or a generic runner I'm just not sure what kind of data you exactly want.
