### ISSUE TITLE
dynamically add source-paths once watch has started

### ISSUE THREAD

**Issue by zcaudate** [thheller/shadow-cljs#356]
Is it possible to add an additional directory to the `:source-paths` entry without restarting?

**Comment by thheller** [comment]
No. `:source-paths` directly mirror the JVM classpath so they can't easily be modified at runtime.

**Comment by thheller** [comment]
I'm unsure what you mean by "search path" but no you can't modify any input paths dynamically.

**Comment by zcaudate** [comment]
Currently I'm using the `shadow-cljs.edn` instead of `project.clj`. It works really well - though what I'm finding is that I have to put both source and test paths in `:source-paths` in order for my clojurescript tests to compile, ie:

```
 :source-paths
 ["src" "test"]
```
if there is code that accesses the `resource` directory, it then looks like this:

```
 :source-paths
 ["src" "test" "resources"]
```

If I'm writing something that reads in `shadow-cljs.edn`, I would prefer to have separation of `test` and `source` code to be distinguishable:

```
 :source-paths
 ["src"]

 :test-paths
 ["test"]
```

Currently specifying `:test-paths` still ignore compilation of .cljs files. I thought the easiest way around it would be to to include an additional directory for `.cljs` tests to be found or

ps. The jvm classpath can be modified at runtime through reflection. In jdk 9 and 10, even though  `java.net.URLClassLoader` was replaced by `jdk.internal.loader.ClassLoaders.*`, the internal classloaders still contain the same exact structure.

**Comment by thheller** [comment]
I had some rather bad experiences messing with ClassLoaders in the past that I'd rather not repeat and it got lot harder with Java 9+ where any reflection on those is a no-no.

Since any `shadow-cljs` build will already only include the files that are actually relevant to the build it doesn't matter if the classpath always contains tests and such. As described [here](https://code.thheller.com/blog/shadow-cljs/2018/02/08/problem-solved-source-paths.html).

So as far as `shadow-cljs` is concerned separating the `:source-paths` is not relevant and all it would do is join them together anyways later. I'd rather avoid the extra confusion the extra paths add. `tools.deps` also doesn't make a distinction which path you are using, its all just paths. I'm not yet sure if thats a good thing or not. Don't get me wrong: Actually having multiple paths is absolutely a good thing, just making a distinction about their purpose is not super relevant.

When it comes to packaging libraries that is another story but for now my stance is to rather deal with this in the packaging library instead of making it the default. Instead of `:test-paths` you could just as easily do `:source-paths ["src" "test" "resources"]` + `:that.package/exclude-paths ["test"]` since its really just an optimization to exclude those files from the package. It would also be just as easy to just ignore `_test.cljs` files by default.

I'm open to adding `:test-paths` and `:resource-paths` but I'd rather experiment with some alternatives first.

**Comment by zcaudate** [comment]
I know what you mean. If you add in one, then `:java-source-paths`, `:android-source-paths`, `:cpp-source-paths` and `:asm-source-paths` might also be justified.

I'm not too concerned with `:resource-paths`. However, I think `:test-paths` should be a special case because the `:target :node-test` is compiling all the files, as opposed to the `:target :browser`, which compiles only the necessary files and it would be good to have that behaviour differentiated.

**Comment by thheller** [comment]
`:target :node-test` isn't compiling all the files (none of the builds do).

It compiles all the files matching the `:ns-regexp`, eg. all `-test$` namespaces. It doesn't care which path they are on. Sure it could also filter by source-path but I would do so as part of the build filter options and always assume that they are on the classpath already.

**Comment by zcaudate** [comment]
that's pretty awesome. is it possible to add more than one :ns-regexp?

**Comment by thheller** [comment]
Not yet. But there will be. Tracked here: https://github.com/thheller/shadow-cljs/issues/322
