### ISSUE TITLE
ideas about on-warning hook on files changes

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#363]
Usage might be rare. I have a situation my shadow-cljs runs `:target :node-script` and `:target :browser` in the meanwhile. When there is a warning for browser, we have HUD and I can see it when placed on the same screen. But I don't place terminal in the same screen, besides the error messages need spaces to display. At last I got several chances forgot I to check out warnings on the other screen.

So I'm thinking about if there's anyway I can capture warnings and error messages then throw them to somewhere I can see easier. For example calling a function in the Node.js script I working on and send it to my webpage with WebSocket, or even trigger some sounds?

**Comment by thheller** [comment]
`:build-hooks` are pretty flexible and you could use them to send a system notification for example. You could also play a sound. Its also possible to "broadcast" websocket messages, so the `:node-script` build could in theory notify the `:browser` build. However since that message won't be handled it won't have any effect. Showing warnings from the node build in the browser HUD would be pretty confusing I think.

In my workflow I have a REPL running next to me Editor 100% of the time. The `watch` is running inside the REPL so I see warnings there immediately. I don't think I looked at the browser HUD once since adding it. Maybe something like this would also work for you?

**Comment by jiyinyiyong** [comment]
I found this in the manual, but what's in `build-state` or what does it look like?

```clojure
(ns my.util)

(defn hook
  {:shadow.build/stage :flush}
  [build-state & args]
  (prn [:hello-world args])
  build-state)
```

**Comment by jiyinyiyong** [comment]
> In my workflow I have a REPL running next to me Editor 100% of the time. The watch is running inside the REPL so I see warnings there immediately.

My editor is different. I don't have a Clojure REPL in it.

> Showing warnings from the node build in the browser HUD would be pretty confusing I think.

I do HTML/CSS everyday. Not hard to add one by myself if I have the warning data I need.

**Comment by thheller** [comment]
I thought about it for a bit and `:build-hooks` is not suitable for this. They do not get called when the build fails which is probably important information you care about. You could instead use a subscription server-side but that is not yet part of the official API so it may change in the future.

```clojure
(ns demo.dev-setup
  (:require
    [clojure.core.async :as async :refer (go <!)]
    [shadow.cljs.devtools.api :as shadow]
    [shadow.cljs.devtools.server.worker :as worker]
    ))

(defn handle-watch-message [{:keys [type] :as msg}]
  (prn [:watch-msg type]))

(defn start
  {:shadow/requires-server true}
  [& args]
  (shadow/watch :browser)
  (shadow/watch :script)

  (let [worker (shadow/get-worker :script)
        watch-chan (-> (async/sliding-buffer 10)
                       (async/chan))]
    (go (loop []
          (when-let [msg (<! watch-chan)]
            (handle-watch-msg msg)
            (recur)
            )))

    (worker/watch worker watch-chan)))
```

You could run this with `shadow-cljs run demo.dev-setup/start` instead of `shadow-cljs watch browser script`. In addition to starting the watches it will subscribe to the `:script` build and receiving a bunch of messages. These messages are pure data and include `:build-start`, `:build-complete` or `:build-failure`.

Maybe you can build something out of that?

Besides that I definitely recommend hooking up a REPL properly. It will change the way you develop in a good way.

**Comment by jiyinyiyong** [comment]
Thanks for your script, I would like to try it.

My workflow relies heavily on [Calcit Editor](https://github.com/Cirru/calcit-editor/) which has a quite distance from your workflows of using a terminal in IDE. Kind like got myself trapped in my little editor. I can hardly handle large pieces of Clojure without my editor since it's [too powerful in managing parentheses](https://twitter.com/jiyinyiyong/status/1026033401596235776).

**Comment by jiyinyiyong** [comment]
Is there still an API I can use to send code to a connected runtime, which can be used to interact with the runtime code? Even send code to a browser runtime when the nodejs part finished a compilation?

**Comment by thheller** [comment]
I'm currently working on the public API which I'll be using for the UI itself. You'll be able to do what I think you want to do once that is done.

**Comment by jiyinyiyong** [comment]
Turned out I didn't even try the script since no any `shadow/get-worker` in my code.

I think probably my need will be met if shadow-cljs supports calling `say "build error"` on build errors. Since I usually running two watching builds, one for `:browser` and one for `:server`. It's harder for me to notice the errors happening on another desktop. If I got voices or notifications, then it will be enough, and no need to display errors on the client.

**Comment by thheller** [comment]
Did you ever try using the UI?

`shadow-cljs watch browser server` then open `http://localhost:9630` and the UI should show both active builds and show warnings/errors accordingly.

I could maybe add notifications to that UI as well.

**Comment by jiyinyiyong** [comment]
Nope. That would be some more place to read logs, just like the logs in the terminal, if I don't look at it, then I don't know errors in it.

**Comment by jiyinyiyong** [comment]
Thanks. The notifications is working after I upgraded.

I should say it only solved the problem partly. I have several considerations,

* I have two builds running in the meanwhile. That means there could be two notifications popping up together, which is not good experience. For the errors of the browser build, I don't want them to be popped up at all.
* The UI is less convenient compared to the CLI tools. To be specific, it's not customized based on my own workflow. There could be some distractions. It's interesting but I don't think it's going to replace my current scripts.
* Personal option but I don't like the styling of the UI... I would rather control the details with my own DOM and CSS if that's possible.
