### ISSUE TITLE
Runtime Error - Cannot instantiate an arrow function

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#365]
Require `["@absinthe/socket" :as absinthe]` and `(absinthe/create nil)` produces `Uncaught TypeError: Cannot instantiate an arrow function`.

Need to verify if this is a shadow-cljs only thing or happens in webpack as well. Might be related to how shadow-cljs loads JS deps but not a clue.

**Comment by jmarca** [comment]
What was the resolution to this?  I'm hitting the exact same issue, also trying to use @absinthe/socket

**Comment by thheller** [comment]
I can't remember sorry. Last time I tested it it compiled fine for me.

Although that may have been due to my babel config. So in the build config `:js-options { :babel-preset-config {:targets {:safari 11}}}`. See [babel preset-env](https://babeljs.io/docs/en/babel-preset-env#targets).

**Comment by jmarca** [comment]
Thanks for the reply, but I still can't make any headway.  

(I'm new to using shadow-cljs, with my last foray into clojurescript being 2 years ago, so forgive my incompetence in this.)  

I added :babel-preset-config as you noted, but no joy.  I also tried 
```
 :js-options {:babel-preset-config
              {:targets "> 0.25%, not dead, last 1 version"}}
```
but still it crashed with the arrow error function instantiate issue.  Working through the trace in the dev tools, it seems there is a check that `this` needs to be undefined, but it isn't

```
var _this$p = undefined;
...

var create = function create(phoenixSocket) {
  _newArrowCheck(this, _this$p);

...
function _newArrowCheck(innerThis, boundThis) {
  if (innerThis !== boundThis) {
    throw ...
```
(Putting in a breakpoint there, `this` is clearly defined (it shouldn't be), while `_this$p` is undefined).

Somehow the create function isn't getting passed as a pure function to clojurescript is my guess, but I've no clue why, or how to influence that.

Also, I'm not sure how babel enters into the shadow-cljs processing stages, as the documentation doesn't really mention it, aside from the bit on [javascript dialects](https://shadow-cljs.github.io/docs/UsersGuide.html#_javascript_dialects) that seems to discuss running babel on local source files, not on npm-supplied ones.

I appreciate any help you can provide, but also understand if you can't or don't want to deal with this.  I'm also willing to keep banging away trying different things and learning slowly.  
Do you have a successful example somewhere on github of using @absinthe/socket etc with clojurescript?  (I thought I was the only one crazy enough to use elixir back end, clojurescript front end).

**Comment by jmarca** [comment]
Figured out a fix that works for me.  Found this in the documentation: [output language options](https://shadow-cljs.github.io/docs/UsersGuide.html#_output_language_options).  I added `:output-feature-set :es8` to my compiler settings, as in:

```
...
:dev {:compiler-options
      {:closure-defines {re-frame.trace.trace-enabled?        true
                         day8.re-frame.tracing.trace-enabled? true}
       ;;:fn-invoke-direct true
       ;;:static-fns true
       :infer-externs :auto
       :output-feature-set :es8}}
```

(Still quite a bit of cargo-cult configuration there, but I know the invoke-direct and static-fns did not help, so keeping them there as a cautionary tale...)

After that, problem solved.

**Comment by jmarca** [comment]
Found this closed issue in Webpack: https://github.com/webpack/webpack/issues/7213

(Also, I deleted a comment--thought fixed it, but I was wrong)

**Comment by jmarca** [comment]
Is there a way to specify "use strict" at the top of the files generated by shadow-cljs.  Specifically, if I add the line "use strict"; to the top of `.../compiled/module$node_modules$$absinthe$socket$compat$cjs$index.js` so that it reads:

```
"use strict";
shadow$provide.module$node_modules$$absinthe$socket$compat$cjs$index=function(global,require,m...
```

Then I can get past this bug.

**Comment by thheller** [comment]
There is not. What does that fix?

**Comment by jmarca** [comment]
It makes the “this” reference inside of the function call refer to undefined, rather than the global context. 

In strict mode, if you bind a function to undefined (as is being done here) then `this` is undefined. That is what the arrow check function is checking for—making sure the function is not being instantisted (which I gather would mean `this` is something). 

In *not* strict mode, which apparently is where the code is running in my case, if a function is bound to undefined, then its `this` refers to the global context. Which then means the guard function fails, because `this` now refers to the global context (the `Window`), not undefined. 

I can’t find any good documentation of these layers of JavaScript cleaning and poly-filling tools, so I don’t know how to get the code to end up in a state in which “use strict” is the default. 


James

**Comment by jmarca** [comment]
I can't figure out where this happens, but a `'use strict';` is being removed from the required library, probably by the google closure compiler?

The original source code of the index.js file looks like:

```js
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }
...
```

After running through shadow-cljs, I get (manually breaking lines for readability):

```js
shadow$provide.module$node_modules$$absinthe$socket$compat$cjs$index=
    function(global,require,module,exports){
        function _interopDefault(ex){return ex&&"object"===typeof ex&&"default"in ex?ex["default"]:ex}Object. ...
```

Both the `'use strict';` and the `exports '__esModule',` bits are removed.  I've tried to tell the clojure compiler not to do that by setting the flag `:elide-strict false`:

```clojure
:dev {:compiler-options
      {:closure-defines {re-frame.trace.trace-enabled?        true
                         day8.re-frame.tracing.trace-enabled? true}
       ;;:fn-invoke-direct true
       :static-fns true
       :elide-strict false
       :infer-externs :auto
       :output-feature-set :es8}}
```

I can't see any other ways to tell the various compilers and processors to leave that 'use strict' alone.

If I manually edit the resulting file to put the `'use strict';` back in so that it looks like this (again, line breaks inserted for readability only):

```js
shadow$provide.module$node_modules$$absinthe$socket$compat$cjs$index=
    function(global,require,module,exports){
        'use strict';  
        function _interopDefault(ex){ ...
```

Then it makes it past the "Cannot instantiate an arrow function" error, and my problem would be solved.

**Comment by jmarca** [comment]
Actually, I hate this fix of a fix of a hack of polyfills for old browsers ugliness.  The root of the problem is that the absinthe/socket etc code all run an over aggressive pass of babel.  I just spent the morning forking that, learning lerna, and publishing a version with no arrow function replacement in the babel opts.  works for me now using shadow-cljs as is, with my version of absinthe code (@activimetrics/socket, etc)
