### ISSUE TITLE
Live reloading doesn't work correctly with `def` and caching

### ISSUE THREAD

**Issue by endenwer** [thheller/shadow-cljs#380]
When I change file shadow-cljs will reload it and all files what require it but if I use `def` in file what is not reloaded but uses reloaded files it will use old version. For example, there is this dependencies tree: `main.cljs` -> `sub/main.cljs` -> `sub/sub/main.cljs`. If I change `sub/sub/main.cljs` file `sub/main.cljs` also will be reloaded. But if I use `def` in `main.cljs` like this `(def some-def {:some-value (sub.main/some-fn)})` it will use old version of `sub.main/some-fn`. I hope I explained it clearly.

The only possible solution here is to reload all files in dependencies tree or just disable cache. I don't know how it is done in figwheel but it is working correctly.

And thanks for awesome project.

**Comment by endenwer** [comment]
Looks like disabling cache does not change anything. And I checked figweel. It reloads all dependencies tree.

**Comment by thheller** [comment]
This is tracked here: https://github.com/thheller/shadow-cljs/issues/349.

Generally this is not required since keeping references to defs from other namespaces in maps and such could be considered global state which you should avoid at all cost.

`shadow-cljs` does not reload everything by default because it can get rather slow in bigger projects.

Ideally you want to construct `some-def` on-demand since otherwise this pattern also prevents dead-code elimination for `:advanced` builds.

Instead of
```
(def some-def {:x some.other.ns/foo})
```
consider
```
(defn get-data [maybe-args]
  {:x some.other.ns/foo})
```
and calling this in your `after-load` hooks or wherever `some-def` would be used.

**Comment by endenwer** [comment]
Thanks for response. I'm closing it then.
