### ISSUE TITLE
losing access to namespaces while using `watch {:autobuild false}` with a browser REPL

### ISSUE THREAD

**Issue by mhuebert** [thheller/shadow-cljs#384]
Reproduction:

1. `(shadow/watch :browser {:autobuild false})`
1.  open browser window, should see `JS runtime connected.`
1. `(shadow/repl :browser)`
1. `(in-ns 'my-app.core)`
1. move to another namespace, `(in-ns 'my-app.other)`
1. perform some combination of editing & saving 2-3 namespaces, loading them via `Load file in REPL`, and entering them using `(in-ns the.ns)`. It doesn't always happen immediately, but very soon (within a couple of cycles) I get into a state where I am unable to enter some of the namespaces without getting `[:did-not-find the.ns]` errors which are not "cleared up" by reloading the file. Then, the only way I seem to be able to start using them again is by starting a new `watch` process.

**Comment by thheller** [comment]
I pushed half of a fix here: https://github.com/thheller/shadow-cljs/commit/4129249da938a7069b2564dc9868ee67af066aef

But there is still the issue of `(in-ns 'i.dont.exist)`. Need to find out what CLJS does. It is ok to do in CLJ but leaves the `ns` in a more of less unusable state since it doesn't have a reference to `clojure.core` thus you can't use any of it.
