### ISSUE TITLE
[discuss] deploy cljs code on npm

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#40]
Weeks ago I mentioned for js developers we put compiled js code in npm, and was told it has problems if the compiler is in a different version.

Now I think maybe we can put ClojureScript source code there, as long as the bundler recognize it. Suppose we have a project containing these entries:

```text
package.json
src/
   example/
          main.cljs
```

We will need an entry in `package.json` that specifies:

```js
  "clojure-package": true,
  "source-paths": ["src/"],
```

Good parts:

* js developers are familiar with npm. Releasing a ClojureScript package is very easy
* besides, some cljs developers(well, like me) would not need Lein or Boot anymore

Bad parts:

* the compiler would become complicated in order to resolve a new package format
* Clojure community already have Maven and Clojars, well...
* if other tools do not follow, people still need Clojars to share packages

I'm not sure about the implementations. Maybe it's also a bad idea on managing classpaths.

----

update: There's a case, nested dependencies would be installed in a nested `node_modules/` folder, which would make it hard for deciding classpaths https://docs.npmjs.com/how-npm-works/npm3

**Comment by thheller** [comment]
CLJS packages on `npm` is probably a bad idea. I could easily do this with `shadow-cljs` but it would hurt the ecosystem if only `shadow-cljs` supported it and I think `maven` is far better than `npm`. How `npm` handles version conflicts is absurd.

Clojars isn't any more complicated than `npm`. It is just more difficult to configure **ONCE**. When that is done it is just `lein deploy clojars`. I cannot remember how I ever configured it so that part definitely needs to become easier. It really only is complicated because of the signing process which is a very good idea but interfacing with `gpg` can be painful.

I may add a `shadow-cljs deploy clojars` option in the future so you don't need `lein` or `boot` for that but at the moment this is a bit out of scope. Maybe it is possible to use `lein` as a library, then this would be easy. Didn't look into that.

**Comment by jiyinyiyong** [comment]
npm's dependency resolving solution is clear enough to me. How does ClojureScript handle version conflicts? I have some bad impression on `classpath`. I run into problems when I was using Boot and Lumo. I guess it was because cache paths were also in the classpath, as a result I took very long time to fix my bugs. 

Another nice thing about npm is we have some handy tool like `npm search` `npm info` `yarn outdated`. Is there alternatives in the world of Clojars?

**Comment by thheller** [comment]
`npm` will just create nested versions as explained here: https://docs.npmjs.com/how-npm-works/npm3-dupe

`yarn` handles this a little better but still doesn't resolve conflicts fully.

That means that you can have multiple instances of the same dependency running.

```
node_modules/b/node_modules/a # b uses v1 of a
node_modules/c/node_modules/a # c uses v2 of a
```

`webpack` supports additional deduping but in CLJS this just can't work. There can only ever be one version loaded. `maven` ensures that only one version is used, usually the most recent one is used. `lein deps :tree` can show conflicts but you have to resolve them manually.

`npm` just pretends that there are no conflicts.

`lein ancient` is a plugin to show outdated dependencies just like `yarn outdated`. See: https://github.com/xsc/lein-ancient

I know nothing about `boot`. I'm sure they have something comparable.

Don't know if there is a `npm search` but https://clojars.org/ works well enough for me.


Maybe I'll add some basic package management to `shadow-cljs` in the future but this is out of scope for now. I will definitely not support CLJS `npm` packages unless this gets official support in core.

**Comment by jiyinyiyong** [comment]
"install order matters" does not guarantee consistency on our side.

I thought yarn handles nested dependency in the same way as npm, however it's not documented well.

**Comment by kurtharriger** [comment]
I actually think npm's strategy makes a lot more sense them maven in practice.  Maven just assumes that it is ok for all code to use only one version, but in practice this doesn't always happen:

Lets say I want to use two completely unrelated libraries, library A and library B.
Library A has an internal dependency of package C.  
Library B  also has an internal dependency on package C.
Library A large and mature they still use version 1 of package C. 
Library B is cool and hip they use the latest and greatest and are on version 2 of package C.
Turns out version 2 is of library C has breaking changes that are not backward compatible with version 1 of library C.

This usually means forking library A and updating it to use version 2 of library C. Sometimes this isn't trivial and even if you get it working there is no guarantee that the upstream maintainer of package A has any interest in updating his super mature library.  
When I was working with hadoop I would frequently run into this issue with packages like jackson for json serialization or logging frameworks...  As a user of package A and package B I shouldn't care which version of package C these libraries use providing that their usage is independent.  Java's solution to this problem is to use different classloaders or frameworks like OSGI! 

Its nice to have the option to run multiple versions, focus on business value validation, then go back later to fork and update packages when its the proper time to optimize download package size.
