### ISSUE TITLE
Have a convenience mechanism for creating deps.cljs

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#403]
Hi Thomas!

I am using a `deps.cljs` function in our libraries for propagating the JavaScript dependencies to client libs and I have a feature proposal: give that `shadow-cljs`'s source of truth for JS deps is `package.json`, it would be awesome to have some way to create automatically the `deps.cljs` file containing `:npm-deps` from there.

A command line argument would be good enough.

What do you think? Thanks a lot!

**Comment by thheller** [comment]
You could just write it as a library so that none shadow-cljs users can use it as well via `clj` for example.

If enough people are interested in it I could add it as a default shadow-cljs dependency but there is nothing in the code that would need to interface with shadow-cljs at all. `shadow-cljs run your.lib.create-deps-cljs` does all you'd need.

**Comment by arichiardi** [comment]
Yep, but it is such a small thing that reads deps and saves them to `deps.cljs`...I am going to write a lib if I have to but a command line convenience thing sounded better (which I can definitely contribute though).

**Comment by thheller** [comment]
Not going to do anything for this on my end. Can't reliably differentiate between `devDependencies`, `peerDependencies` or just `dependencies`. Just writing the `deps.cljs` is probably gonna be fast than trying to figure out an API call for this regardless.

**Comment by arichiardi** [comment]
I took the time for a small script today and it is pretty ugly for now:

```
echo -n '{:npm-deps {'

jq -r '.dependencies | to_entries | map(["            \"\(.key)\"", "\"\(.value)\""]) | map(join(" ")) | .[]' < package.json

echo '}}'
```

That's unfortunate

**Comment by arichiardi** [comment]
I ended up implementing a hook:

```clojure
(ns tools.build
  (:require [cheshire.core :as json]
            [clojure.java.io :as io]))

(def ^:private package-json-path "package.json")
(def ^:private deps-edn-path "src/deps.cljs")

(defn deps-cljs
  [package-json-edn]
  {:npm-deps (get package-json-edn "dependencies" {})})

(defn flush-hook
  {:shadow.build/stage :flush}
  [build-state & args]
  (println "[:flush-hook] Update deps.cljs from package.json:")
  (let [deps-cljs-content (deps-cljs (json/decode (slurp "package.json")))]
    (println "[:flush-hook]" deps-cljs-content)
    (spit deps-edn-path deps-cljs-content))
  build-state)
```

**Comment by thheller** [comment]
It seems a bit weird to do this as a hook.

A simple function invoked via `shadow-cljs run tools.build/generate-deps-cljs` wouldn't write this thing every single time a build completes (in `watch`). `shadow-cljs` watches the `package.json` so every time you write it you'll trigger a whole update cycle (which won't do anything since nothing changed but still).
