### ISSUE TITLE
does shadow-cljs support developing code with soft links?

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#448]
I splitted my code in to two repo and felt inconvenient. So I tried to soft link the library to the app, see if  shadow-cljs still reloads. Turned out shadow-cljs does not watch files inside the soft link of a folder. Is that a designed behavior? Or is there an simple way to develop library from another repo?

----

I'm also trying adding `../library/src/` to class-path. It seems to work... so is that correct...?

**Comment by thheller** [comment]
Can you give an example of one such link?

The extra classpath entry is the preferred method over links but I did some work a while ago so links should work fine?

**Comment by jiyinyiyong** [comment]
I have two repos https://github.com/Respo?utf8=✓&q=composer&type=&language=

One has code in 

```
/Users/chen/repo/respo/composer-app/src
```

and the other one has code in

```
/Users/chen/repo/respo/composer/src/respo_composer
```

So I created a link in `composer-app/src` like running

```bash
ln -s ../../composer/src/respo_composer
```

As I observed, shadow-cljs loaded the linked files correctly. But as I edited and saved files in `composer/src/respo_composer`, no change events happened.

And after I changed to classpath, files emitted change events correctly.

**Comment by thheller** [comment]
IIRC you are on macOS right? I'm on Windows which works fine.

Did you restart after creating the link?

I suspect that the `hawk` watcher used on macOS has issues with links. I'll see if can test this on macOS.

**Comment by jiyinyiyong** [comment]
yes. macOS.

no. never restarted.

**Comment by thheller** [comment]
Try creating the link and then starting `shadow-cljs`. It may just not pick up links when created while running?

**Comment by jiyinyiyong** [comment]
No. nothing happened even I rename the files. Also I confirmed I edited a file that was actually referenced in the app compiled by shadow-cljs.

**Comment by thheller** [comment]
As suspected this is in fact a problem in `hawk`. Unfortunately that library is unmaintained as far as I can tell and I only use it on macOS since file watching otherwise has a slight delay.

In `2.8.12` I made it possible to disable `hawk` on macOS by setting `:fs-watch {:hawk false}` which makes links work but file watching in general a bit slower. I don't think there is anything I regarding `hawk`. I could not find any options to tweak it. I'm not actually sure if file watching is still slow on macOS when using newer JDKs, will try to test that later. My macbook needs some updates. :P

**Comment by jiyinyiyong** [comment]
I'm fine with setting `classpath`.
