### ISSUE TITLE
"shadow-cljs --help" asks got a config file in 0.9.5

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#45]
I thought it would just print the help page?

```text
=>> ./node_modules/.bin/shadow-cljs --help
shadow-cljs - missing configuration file
- /Users/chen/repo/respo/respo-examples/shadow-cljs.edn
Create one? [y/n]: n
=>>
```

I was trying to see if I can use an option to specify the location of the configuration file. In a strange scenario I wanted to share one config file in several sub-folders.

**Comment by thheller** [comment]
Good point, `--help` shouldn't require a config. Currently `--help` is done by the JVM since the CLI script just passes the args along.

Sharing a config file how? The config file is intended to be kept in the project root directory, that is important since internally all paths are relative to that root. It does however check the parent directories. So it would find `/Users/chen/repo/respo/shadow-cljs.edn` in `/Users/chen/repo/respo/respo-examples/...`. Does that help?

**Comment by jiyinyiyong** [comment]
Not very sure if checking parent directories would work correctly. There may be two opinions, one based on `process.env.PWD`, one based on `__dirname` of the config. [In my case](https://github.com/Respo/respo-examples) I have several sub-directories following the same project structure, which means the configs files are the same. Currently I'm using soft links to share the configs, which is the `PWD` based solution. I think if there's an CLI option for that, then I don't have to create soft links.

**Comment by thheller** [comment]
I copied what `leiningen` does as it also checks the parent directories and it seems like the best solution to me. It also always uses the directory with the config file as the PWD.

I think symlinks are fine in your case, better than having to specify a config path and the PWD as the dir of the config would be incorrect in your case.

**Comment by jiyinyiyong** [comment]
I have to say such use cases are rare, which makes symbolic link an acceptable solution
