### ISSUE TITLE
Setup for vanilla .cljc Lein library

### ISSUE THREAD

**Issue by vemv** [thheller/shadow-cljs#484]
Hi!

One question:

say that I want to offer a clj/s library in coded as .cljc files, under a standard Lein structure.

Library consumers should not depend on a specific cljs compiler.

But the Lein project would need a dev-only cljs compiler setup, for being able to run the test suite for the JS target.

A good example would be [cljfmt](https://github.com/weavejester/cljfmt/blob/master/cljfmt/project.clj): it's cljc files, and it uses cljsbuild as a test runner (additional to the JVM one).

Is shadow-cljs capable of replacing :cljsbuild for such a use case?

Thanks - V

**Comment by thheller** [comment]
`:cljsbuild` is completely irrelevant to builing a library. A library is just uncompiled `.cljc` files in a `.jar`. CLJS compilation has no role in it.

```
(defproject your-lib "0.0.1"
  :description "..."
  :url "..."
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}

  :dependencies
  [[org.clojure/clojure "1.10.0" :scope "provided"]
   [org.clojure/clojurescript "1.10.520" :scope "provided"]]

  :resource-paths
  ["src/resources"]

  :source-paths
  ["src/main"]

  :test-paths
  ["src/test"]

  :profiles
  {:dev
   {:source-paths ["src/dev"]
    :dependencies
    [[thheller/shadow-cljs "2.8.31"]]}})
```

You can then either use `shadow-cljs` as normal OR use `:lein true` and let `:dependencies` and `:source-paths` be managed in `project.clj` instead of `shadow-cljs.edn`.

**Comment by vemv** [comment]
Hey there,

thanks for the hints!

I think the essence of my question is how to have a test runner that is Lein-integrated. In quite a few Lein libraries I can run `lein test` and:

* cljs compilation will be triggered
* JVM test suite will be run
* JS test suite will be run

I don't know if that's possible with shadow-cljs. Also one cannot trivially know the expected `shadow-cljs.edn` contents for such a setup.

I have the impression that the doc is currently oriented mostly towards SPAs and such. Would be very nice to have a 'library' entry in https://github.com/thheller/shadow-cljs#examples .

ps - you have a new Patreon patron! :)

**Comment by thheller** [comment]
Thanks for the Patreon support!

Library development is indeed a bit neglected at the moment as there is still no proper way to publish libraries without resorting to something like `lein`. I don't really want to touch the Clojure side of things since that is already handled well by `lein` (and others).

What I would recommend is just using a typical bash script or so:

```
lein test && shadow-cljs release your-tests && node path/to/output-to.js
```

You gain very little by trying to fit everything into `lein` IMHO, you can however use `:aliases` to setup the workflow you want.

**Comment by vemv** [comment]
I have adopted embraced the suggested separation between `lein test` and `node path/to/suite.js`.

In fact I found that `:hooks [leiningen.cljsbuild]` could interfer with Cloverage, CIDER etc so the whole approach of single-command-test-suite might be flawed.

https://shadow-cljs.github.io/docs/UsersGuide.html#target-node-test has some documentation related to my original issue, so I'm closing it.
