### ISSUE TITLE
support for alternate config file names as a paremeter

### ISSUE THREAD

**Issue by yogthos** [thheller/shadow-cljs#490]
I was wondering if it would be possible to specify the name of the config file explicitly when running shadow-cljs. The use case here is to generate the config via a lein plugin and then generate a `.shadow-cljs.edn` file that would be used to run shadow-cljs. Alternatively, would it be possible to provide a way to start shadow-cljs from within the plugin and pass it the config as a map.

**Comment by thheller** [comment]
Although I wouldn't rule out the possibility of adding this I have to ask why?

You can already use `shadow-cljs` with [lein](https://shadow-cljs.github.io/docs/UsersGuide.html#Leiningen).

- What would you gain by moving the "other" `shadow-cljs.edn` contents into `project.clj`?
- What would a `lein` plugin provide that isn't already possible without it?

I have thought about creating a `lein` plugin myself in the past but pretty much could never find a reason why I would? I covered some of my thoughts on the subject [here](https://code.thheller.com/blog/shadow-cljs/2017/11/18/the-many-ways-to-use-shadow-cljs.html).

Having a dedicated config file enables a couple nifty features since `shadow-cljs` can watch that file and user-edits can take immediate effect (eg. adding/changing a `:dev-http` is realized without requiring a server restart, a build config change automatically triggers a recompile if `watch` is running, ...).

**Comment by yogthos** [comment]
There isn't much reason to do so if you're working on a pure ClojureScript project. However, if you have a project that has both front-end and back-end configuration, I find that there are benefits to keeping it in one place. The `project.clj` in Luminus declares things like source and resource paths, and there are profiles such as `dev` and `uberjar` that use different paths. Using a separate config for shadow-cljs results in duplication which is error prone.

**Comment by thheller** [comment]
When using `lein` all classpath related aspects are managed via `project.clj`. So whatever `lein` does to construct a classpath will immediately affect `shadow-cljs` as well. Profiles already do what they are supposed to.

Can you provide an actual use-case you'd like to solve where you think moving the entire (non-classpath related) `shadow-cljs` config into `project.clj` would benefit?

**Comment by yogthos** [comment]
The way Luminus template is set up is currently is to keep all the build configuration in `project.clj`. Aside from pure functionality, I find this appealing from organizational standpoint. I find it easier to have a single file to manage all the configuration as opposed juggling multiple ones.

From functional standpoint, the user has to run `lein run` and `lein figwheel` during dev time, and `lein uberjar` to compile for production. Since all the config is in one place, it's easy to tell what sources are being compiled and what compiler options are used.

Overall, I think that it's better to provide the flexibility for the user to decide how to manage configuration if it's not too much work to facilitate. If the config was decoupled from the main function, then it would be possible to run shadow-cljs programmatically from the REPL as well making it possible to embed it.

**Comment by yogthos** [comment]
Also, if it was possible to start shadow-cljs programmatically, it would be possible to run it within the same runtime as the lein plugin. Right now if I want to run shadow-cljs from lein I have to wait for lein to start, and then for shadow-cljs to start as a separate process.

**Comment by nikolap** [comment]
The main benefit I see for this is to have all the config in one file, helping with organizing / keeping project config in one place. 

Yes, in that scenario, there's the cost of losing ability to hot reload the build config itself, but that can be a caveat of whatever external plugin uses it, not shadow-cljs.

Also, perhaps there's also some way to directly pass through the config to shadow-cljs via lein or programmatically instead of it having to load the shadow-cljs.edn config on initialization?

**Comment by thheller** [comment]
> Also, if it was possible to start shadow-cljs programmatically, it would be possible to run it within the same runtime as the lein plugin. Right now if I want to run shadow-cljs from lein I have to wait for lein to start, and then for shadow-cljs to start as a separate process.

It already is possible and you don't have to start it in a separate process. See the [embedded](https://shadow-cljs.github.io/docs/UsersGuide.html#embedded) docs. Argueably a bit light on the docs but there isn't much to it other than calling the `start!` function once and then using the `shadow.cljs.devtools.api` ns.

> The main benefit I see for this is to have all the config in one file, helping with organizing / keeping project config in one place.

I completely disagree and do not like the config luminus generates one bit. If there is only one way to configure `shadow-cljs` builds then all the docs always apply. If we start customizing that we need special docs for each custom setup which I'd like to avoid.

I ask again: Can you provide an actual example use-case/project? I'm fine with a sample `project.clj` of how the thing would look in your eyes?

If you don't care about the `shadow-cljs.edn` at the root of the project you can just generate that an `.gitignore` it for now. I can add making the path configurable "later". Just make sure the file exists before `(shadow.cljs.devtools.server/start!)` is called.

**Comment by yogthos** [comment]
Just to be clear, I'm not suggesting changing the format of the config. I'm simply suggesting making the source of the config configurable. Ideally, embedded version could be started as follows:

```clojure
(ns user
 (:require
  [shadow.cljs.devtools.server :as server]
  [shadow.cljs.devtools.api :as shadow]))

(def config
   {:id :app
   :target :browser
   :output-dir "public/assets/app/js"
   :asset-path "/assets/app/js"
   :modules
   {:main
    {:entries [my.app]}}})

(server/start! config)

(shadow/compile config :app)
```

I respect your personal preference for handling the config in a different way, however I have a different preference based on my experience and usage patterns. I think it's reasonable to provide the canonical solution, but to also allow people to configure their projects in their preferred way.

The way I would envision this working would be to have a `:shadow-cljs` key in `project .clj` config that the plugin would read. The key would point to a shadow-cljs config map that normally goes in the `shadow-cljs.edn` file:

```clojure
:shadow-cljs
{:id :app
 :target :browser

 :output-dir "public/assets/app/js"
 :asset-path "/assets/app/js"

 :modules
 {:main
  {:entries [my.app]}}}
```

When the plugin runs it would read the config and pass it to shadow-cljs, and everything would work the same way as it does now from that point on.

**Comment by thheller** [comment]
Your `user.clj` shows one problem with having config data in code (when it should be declarative). You'd need to quote `my.app` (and any other symbol).

Suppose this sample project setup:

shadow-cljs.edn
```clojure
{:lein true 
 :builds
 {:app {:target :browser
        ...}}}
```

The common REPL workflow could use a ns like
```clojure
(ns user
  (:require
    [your.app :as app]
    [shadow.cljs.devtools.server :as server]
    [shadow.cljs.devtools.api :as shadow]))

(defn start []
  (server/start!)
  (shadow/watch :app)
  (app/start))

(defn stop []
  (app/stop))
```

I don't see how that ns would gain anything but confusion by adding actual build configuration there. It is clearly defined where you can find the actual build config.

`project.clj` luminus generates remains pretty much the same, just all the CLJS related things removed. The `:uberjar` profile could adjust `:prep-tasks` like this. Not sure this warrants creating an extra plugin.

```clojure
:profiles
{:uberjar
 {:prep-tasks ["compile"
               ["run" "-m" "shadow.cljs.devtools.cli" "release" "app"]]
  :aot :all
  :uberjar-name "lumiapp.jar"
  :source-paths ["env/prod/clj"]
  :resource-paths ["env/prod/resources"]}}
```

Which again makes it clearly defined where the build config is.

The "common" CLJS related tasks could either be done in the UI, the REPL or via the `shadow-cljs` command.

There are other tasks which need a build config which you'd need to replicate if you move configs elsewhere. Build reports is one example:
```
shadow-cljs run shadow.cljs.build-report app report.html
;; which will probably get a dedicated command at some point
shadow-cljs build-report app report.html
```

Note that this will already use `lein` and support the server-mode instance which may be running already. If you move everything into `lein` you'd lose server-mode support.

I go back to the point I made before: If you add a custom way to run things you need to add a ton of docs on how to use shadow-cljs with luminus instead of using it the way everyone else does.

**Comment by yogthos** [comment]
I would agree with all your points if the discussion was about replacing the existing workflow. Everybody who finds the current approach to be optimal can continue using it. Adding the ability to have different workflows doesn't take anything away from anybody. I'm also not asking you to provide any additional documentation, this would be entirely my problem within Luminus.

I also understand that certain features wouldn't be available with this workflow, but if I'm not using these features it's a moot point. If I ever need things like hot loading the config I can trivially make a `shaodw-cljs.edn` file at any time.

Furthermore, it seems to me that purely from design perspective it's better to not couple business logic with hardcoded environment variables. Ideally, the config should be parsed at the edges into a data structure that's used internally. In my opinion, the core of the application shouldn't know or care where or how the configuration is generated.

**Comment by thheller** [comment]
> Furthermore, it seems to me that purely from design perspective it's better to not couple business logic with hardcoded environment variables. 

I don't know what you mean by this.

> In my opinion, the core of the application shouldn't know or care where or how the configuration is generated.

The core doesn't care. If you explore the code a bit you'll find one pattern that is repeated often.

https://github.com/thheller/shadow-cljs/blob/80528fb4439d58b15679ac3503d008485bef8fd3/src/main/shadow/cljs/devtools/server.clj#L409-L413

So if you call `(start!)` with no args it'll load the config from disc and call the 1-arg version. So you can already pass the entire config to `start!` if you chose to skipping the read of the file.

https://github.com/thheller/shadow-cljs/blob/80528fb4439d58b15679ac3503d008485bef8fd3/src/main/shadow/cljs/devtools/api.clj#L285-L290

`shadow.cljs.devtools.api/compile!` and `compile` are convenience methods so you can call `(shadow/compile :the-build-id)` easily from the REPL. You can instead call `(shadow/compile* the-actual-build-config {})` if you have the build config from somewhere else. This also works for `release*` and `watch*`.

Pretty much everything that accesses `shadow-cljs.edn` will delegate to another function that uses the actual data which you could in theory call directly instead.

> Adding the ability to have different workflows doesn't take anything away from anybody.

shadow-cljs is already usable in very many different ways and I'm not trying to force any workflow on anyone. I'm just trying to caution you against building something only because you want to combine 2 files into one. Things will be much much easier if you keep them separate.

**Comment by yogthos** [comment]
Sorry, I was lazy and went by the documentation but should've glanced through the source. It sounds like `shadow.cljs.devtools.server/start!` and `shadow.cljs.devtools.api/compile*` do exactly what I was looking for.

While I appreciate where you're coming from, I find that having a config file per tool has its own downsides. If every lein plugin becomes a standalone tool with it's own configuration strategy that adds cognitive overhead for me. Personally, I find it easier to have a single location for all the build configuration. It's a strong preference I've developed over the years working with different kinds of build tools.

And the effort involved seems minimal since all the plugin would do is call the two functions with the config read from `project.clj`.

**Comment by thheller** [comment]
I do agree with you that having one config file per tool seems like the wrong direction. I don't like the "new" `deps.edn` setups which create complex `:main-opts` aliases either.

BUT I think that is makes sense to have one tool per language. `lein` covers everything on the CLJ side of things for me. `shadow-cljs` is meant to do the same but for CLJS. I think treating CLJS like it is CLJ is "bad" in practice as the languages are sufficiently different that certain patterns that are "required" for CLJ do not apply to CLJS and make things harder.

For example you can either put all the CLJS deps into a dedicated `:cljs` profile or "misuse" the `:dev` profile but since `lein` is `lein` you will now have to deal with all the dependency conflicts the added CLJS deps cause. One common thing is that `shadow-cljs` tracks the latest Closure Compiler releases much more closely since they often fix important bugs. So if any of the deps listed before `shadow-cljs` happens to include `org.clojure/clojurescript`  you will end up with an "old" version with a conflicting closure-compiler version which causes issues at runtime. Another thing that was common was `datomic` adding an incompatible `guava` version the closure-compiler didn't like. Another one is datomic adding an old `transit` version which again breaks at runtime because `shadow-cljs` expects the current one. The list goes on ...

`shadow-cljs` with `shadow-cljs.edn` takes care of eliminating most of those conflicts and can also use AOT more aggressively to improve startup times quite substantially. Using a shadow-cljs AOT release in a lein "dev" setup with lots of other CLJ dependencies will cause many other issues which is why I would never recommend using AOT "libraries" with `lein`. `shadow-cljs.edn` without `lein` however starts at least 50% faster than with `lein`. This is quite noticeable in daily use.

Fundamentally I think we gain very little by combining CLJ+CLJS setups and things are much easier if you keep them separate IMHO. YMMV of course.

Combining the setups currently only seems necessary since tools like Cursive don't really know how to deal with the split setup properly and either won't find your CLJS deps or your CLJ deps.

**Comment by yogthos** [comment]
The projects my team works on largely treat clj and cljs as the same language. We have a lot of code in cljc, and we move code from front-end to back-end and vice versa. There are some gotchas there, as the dependency issues you mention, but they're not really different from any other dependency resolution gotchas in my opinion.

There are always going to be trade offs with every approach, and I agree with you on the defaults chosen for shadow-cljs. However, in my experience it's rare that I need to change the configuration much from what gets generated by the template. Luminus includes ClojureScript as an explicit dependency, it sets up all the source/resource paths, and so on. In most cases the only thing that I do in project.clj is change dependencies. Meanwhile, I tend to start up the compiler and keep it running for days on end. In this context, startup time is less interesting to me.

In cases where you're assembling the project by hand I completely agree that keeping tooling separate saves you time. On the other hand, if all the configuration is generated from a template in a repeatable way, you don't have to worry about it. And if it becomes a bottleneck, it's trivial to split out shadow-cljs config. If there was a lot of effort involved going from one workflow to the other, I'd be much more hesitant to consider lein integration.

**Comment by thheller** [comment]
I'm still not convinced that this is a good idea but I don't have to be. I'm curious to see what you build. Happy to help if you have questions.

**Comment by yogthos** [comment]
Sounds like a plan, and it's entirely possible I'll change my mind on this as well in the future. I'll let you know how things go. Sounds like we can close this specific issue then since everything necessary is already available.

And thanks for a thoughtful discussion. :)
