### ISSUE TITLE
Eval namespace before require cause incorrect compile result.

### ISSUE THREAD

**Issue by DogLooksGood** [thheller/shadow-cljs#530]
I create a repo to reproduce the problem.
https://github.com/DogLooksGood/shadow-cljs-reload-reproduce

**Comment by thheller** [comment]
Thanks for the repro. This is an interesting problem.

I found the cause but I'm unsure how to properly fix this. The behavior is kind of correct since the `ns` created is first at the REPL it is a "virtual" resource (meaning it has no file associated with it). Adding the extra require in `foo.core` will correctly use the version defined at the REPL since it is already loaded.

If instead the file is loaded you may change your REPL state without meaning to if this is done automatically. I think the proper way to fix this would be to issue a manual `(require 'bar.core :reload)` or `load-file` to force a load from disk (currently broken). This would match the Clojure behavior.

**Comment by DogLooksGood** [comment]
Hi, @thheller 
In Clojure few people use hot-reload so this won't be a problem. I'm not sure if this is the same behavior with Clojure. But when you are using editor like Emacs, Cursive, Atom this case will never happen(Not sure about how they load files).

I already knew few people run into this issue, the terrible thing is when this is happening, there's no error and warning. 

What is the down side to let the file namespace overwrite the virtual resource namespace?

**Comment by thheller** [comment]
I agree that the current situation is undesireable.

I'm curious how you'd even get to this point in regular workflow. I've never gotten to this point before so I'm curious how you and others get there. Maybe there is a clue in how to handle this better in there.

**Comment by DogLooksGood** [comment]
It's not a particular workflow. In general, eval is faster than reload. In regular workflow, you can eval where you change, it's much faster than saving the file to trigger a hot-reload.

**Comment by DogLooksGood** [comment]
Here I think I can provide a case when I run into this. It just happened again to me few minutes ago.

I'm trying to translate a `.clj` file to `.cljc` file, since I want to reuse some clojure code. So I change the file extension, add some reader conditional code and I want to know if it is still work in Clojure side. So I let editor reload this file, but the current repl(both clj and cljs repl are available for a cljc file, later visited will be used in my editor) buffer is a ClojureScript buffer. After evaluation, I realized I did the wrong thing, so I restart the shadow-cljs. What If I don't know this issue?
