### ISSUE TITLE
":ns* not supported ..." (when using `require` outside `ns`)

### ISSUE THREAD

**Issue by ro6** [thheller/shadow-cljs#536]
I hit [this error](https://github.com/thheller/shadow-cljs/blob/815ce0dc8caab05fedbec5d182b92a1c994b8308/src/main/shadow/build/compiler.clj#L92) when trying to use `require` outside the `ns` declaration in a `.cljc` file. 

I'm curious why the `:ns*` op isn't supported? I understand the Google Closure Compiler's model of modules and compilation units constrain ClojureScript's design/implementation, but [this blog post](https://anmonteiro.com/2016/10/clojurescript-require-outside-ns/) led me to believe it was possible.

I'm curious both for solving my own problem, and in case this is an opportunity to contribute ti Shadow-CLJS!

**Comment by thheller** [comment]
`:ns*` is not supported since you cannot do anything with it that you couldn't do with just doing it via `ns`. `require` still can't be used dynamically in any way.

`require` outside `ns` was added for "scripts" that don't have their own `ns`. Since `shadow-cljs` is a build tool for repeatable builds (requiring addressable namespaces) this isn't supported either.

The technical reason this isn't supported is that it complicates pre-parsing. shadow-cljs indexes the classpath for looks at all `.cljs` files and reads the `ns` form as pure data. While it would be possible to continue reading further it just makes things slower without gaining any new "features".

**Comment by thheller** [comment]
Closing this unless you have a compelling use case for `require` outside `ns` (and outside REPL).
