### ISSUE TITLE
REPL on :npm-modules target doesn't appear import `cljs.core`

### ISSUE THREAD

**Issue by aisamu** [thheller/shadow-cljs#550]
> Per your request on the slack channel: 

Hi!

Updating shadow-cljs from 2.8.39 to 2.8.45 (or .51) is unfortunately breaking our REPL setup on the final NPM build of our project. We checked for the usual culprits but nothing did the trick except reverting to 2.8.39. 

This is an `:npm-module` that's being consumed by a Webpack project. On a JS file we have:
```javascript
  window.CLOSURE_BASE_PATH = '/javascripts' // Should match our assets location
  require('cljs/shadow.cljs.devtools.client.browser')
```
After the update the REPL connects as usual but apparently `cljs.core` isn't loaded:
```clojure
cljs.user> 3
3
cljs.user> (first [1 2])
ReferenceError: cljs is not defined
    at eval (eval at shadow$cljs$devtools$client$browser$global_eval (webpack-internal:///./build/cljs/shadow.cljs.devtools.client.browser.js), <anonymous>:1:1)
    at eval (<anonymous>)
    at Object.shadow$cljs$devtools$client$browser$global_eval [as global_eval] (webpack-internal:///./build/cljs/shadow.cljs.devtools.client.browser.js:878:16)
    at eval (webpack-internal:///./build/cljs/shadow.cljs.devtools.client.browser.js:887:44)
[...]
```

Once more, thank you!

**Comment by aisamu** [comment]
Applying the proposed change (`global-eval` -> `js/eval` on `src/main/shadow/cljs/devtools/client/browser.cljs`) seems to fix it.

**Comment by aisamu** [comment]
Just confirming that this is still the case on `2.8.67`

**Comment by thheller** [comment]
I'm unsure what to do about this. I changed to the `global-eval` fn because using `js/eval` has other scoping issues and breaks in regular Browser builds. Usually all CLJS is loaded in the global scope so everything is fine.

However when using `:npm-module` and `webpack` all CLJS code will be wrapped in functions isolating their scopes, which means nothing lives in the global scope. So when the `eval` happens it can't find `cljs.core` because it is not in its scope.

The whole goal of `:npm-module` was to not rely on the global scope. I'll add a hacky fix until I can come up with a cleaner solution.

**Comment by aisamu** [comment]
Thanks! 
I suspect I'm way out of my depth here, but please let me know if I can help in any way (such as testing in our environment).

**Comment by thheller** [comment]
Please try `2.8.68`.

**Comment by aisamu** [comment]
Works like a charm!
