### ISSUE TITLE
Clear example for :node-library REPL setup?

### ISSUE THREAD

**Issue by rlhk** [thheller/shadow-cljs#552]
There are plenty of examples and setups for `:browser` target dev.

However I am confused on how to setup REPL for `:node-library`. I can start `cljs-repl` or `node-repl` (then switch to cljs). Problem is that I didn't find a way to access cljs namespaces. In `:browser` target, the namespaces are loaded by visiting from browser. How does the similar happen for `:node-library` target?

**Comment by thheller** [comment]
Maybe this helps? https://shadow-cljs.github.io/docs/UsersGuide.html#repl-troubleshooting

If you just want a REPL use `shadow-cljs node-repl`.

For `:node-library` you need to run a `node` process that actually loads your output.

Could by as simple as running `node` and then `var x = require("./out/lib.js");` (assuming `:output-to "out/lib.js"`).

**Comment by rlhk** [comment]
> Could by as simple as running `node` and then `var x = require("./out/lib.js");` (assuming `:output-to "out/lib.js"`).

This is only good for testing the compiled js but it's just a JS REPL. What if I want to do interactive CLJS dev like what we can do in the usual `:browser` setup with those CLJS namespaces loaded?

**Comment by thheller** [comment]
I repeat: If all you want is a REPL use `shadow-cljs node-repl`. `(require '[your.lib :as foo])` and done.

If you want more information you need to provide more info about what you are building. There are too many options and I can't describe all. What are you building and how do you expect users to consume it? which platform? node? electron? react-native? ... too many options.

**Comment by rlhk** [comment]
> I repeat: If all you want is a REPL use `shadow-cljs node-repl`. `(require '[your.lib :as foo])` and done.
Ah, that's what I need. Since we usually have all namespaces auto loaded and hot code reload enabled in target `:browser`, I thought `:node-library` has similar automation setup.

If such CLJS code snippet could be added to the part of: https://shadow-cljs.github.io/docs/UsersGuide.html#_single_static_default_export
like where at: https://shadow-cljs.github.io/docs/UsersGuide.html#_about_default_exports
things would be much clearer. 

Maybe with subtitle like: __REPL dev with `:node-library` target__

Thanks!

**Comment by thheller** [comment]
> I thought :node-library has similar automation setup.

It does have a similar automation setup. That just has nothing to do with the REPL and you specifically asked about the REPL.

Let me try to explain from another angle: `:node-library` is intended for builds that will be consumed by `node`-like platforms. So the intended users would do

```
var thatLib = require("your-lib");
thatLib.foo();
```

So if you want a REPL you need to emulate EXACTLY that behavior.

So the example I made earlier would probably be clear this way:

Build config is set to `:output-dir "out/lib.js"` (or anything else really).

You also create a simple `run.js`.

```
var x = require("./out/lib.js");
x.someThingFromYourLib(); // if that makes sense to call
```

You then run `node run.js`. That launches the `node` process and since it importet the library code it will connect back to the `shadow-cljs` server on startup and act as a REPL runtime.

You then use the REGULAR `shadow-cljs cljs-repl your-build` to get the actual CLJS REPL while `shadow-cljs watch your-build` is running. It will then do the usual hot-reload with some limitations due to the nature of node but most stuff works.

Typically it is enough to just use  `shadow-cljs node-repl` since that takes care of all the rest and runs the node process for you.

**Comment by rlhk** [comment]
> So the example I made earlier would probably be clear this way:
> 
> Build config is set to `:output-dir "out/lib.js"` (or anything else really).
> 
> You also create a simple `run.js`.

Think the config you intended should be:
```
:output-to "out/lib.js"
:output-dir "out/lib"
```

Now it makes much more sense to me (not knowing everything under the hood) that `node run.js` is equivalent to a browser process in `:browser` target.

So for my original purpose, 'shadow-cljs node-repl` and  `(require '[your.lib :as foo])` is good enough.

Thanks for the guidance!

**Comment by thheller** [comment]
Oh, yes `:output-to`. Sorry about that.
