### ISSUE TITLE
Feature request: send nREPL `:out` messages with the same `:id` as the results of the evaluation

### ISSUE THREAD

**Issue by PEZ** [thheller/shadow-cljs#563]
I'd like the `:out` nREPL messages to be sent to me with the same message `:id` as the evaluation results for the evaluation that triggered the side effect.

I have this issue on Calva:

* [With shadow-cljs, output from code evaluations don't show up in Calva](https://github.com/BetterThanTomorrow/calva/issues/320)

Here's an example: I get these messages after evaluating `(println "foo")`:

```
msg: {"id":"8","out":"foo\n","session":"0fa54fc3-d541-4dac-83f3-d2f8a7c2f356"}
msg: {"id":"20","ns":"cljs.user","printed-value":1,"session":"aa448e85-a118-4a1a-9e1c-f6ce839d2c1d","value":"nil"}
msg: {"id":"20","session":"aa448e85-a118-4a1a-9e1c-f6ce839d2c1d","status":["done"]}
msg: {"changed-namespaces":{},"id":"20","repl-type":"cljs","session":"aa448e85-a118-4a1a-9e1c-f6ce839d2c1d","status":["state"]}
```

Calva expects the `:out` message here to be sent with `:id` "20". This in order to know how to route the output in the UI.

**Comment by thheller** [comment]
The same `:id` as the evaluation might not be super reliable given the async nature of JS.

Suppose you fire off an async action that takes a while for some reason and you eval something else in the meantime

```
;; could be js/fetch or whatever, just an example here. async is everywhere
(js/setTimeout #(prn :foo) 5000) ;; eval id = 1
(prn :bar) ;; eval id = 2
```

Given that we can't use bindings in this case boths prints would return with id=2. It might be a better default so always use the "latest" message id instead of the first one but I'm not sure which problems this actually solves.

Wouldn't it be easier if the client takes care of this itself? It knows when it sent something to eval and when it received something back so you could order it however you prefer?

**Comment by PEZ** [comment]
Thanks! I tried this now and it works. Calva can route the messages just as it does with Clojure and Figwheel REPLs.

Async calls behave like you said it would. I don't think there is much we can do about that... But I'm happy it works for the sync ones!
