### ISSUE TITLE
shadow-cljs release app can not work with reagent 0.9.0-rc1

### ISSUE THREAD

**Issue by vinurs** [thheller/shadow-cljs#570]
this is a demo https://github.com/vinurs/TestApp/tree/master
```
git clone git@github.com:vinurs/TestApp.git TestApp
cd TestApp
yarn install
cd ios; pod install; cd ..
shadow-cljs release app
yarn run-ios
```
then modify shadow-cljs.edn, change reagent version to 0.9.0-rc1
```
shadow-cljs release app
yarn run-ios
```
the simulator shows this, but ```shadow-cljs compile app``` works ok
![image](https://user-images.githubusercontent.com/37489300/66262550-3bfe7580-e815-11e9-82b3-e39b115fe300.png)

**Comment by thheller** [comment]
This happens due to missing externs. Since `shadow-cljs` leaves the JS processing to metro it cannot collect the externs it usually collects. It also doesn't use the default externs shipped with `cljsjs/react` since they are typically not required.

`reagent` should ideally just add a few type hints where they are doing native JS interop.

You can fix this by creating a `externs/app.txt` in the project with just

```
props
```

**Comment by Deraen** [comment]
@thheller Do you have recommendations what is the easiest way to check where Reagent needs type hints? Can I do it with ClojureScript compiler and `*warn-on-infer*`, or would using Shadow-cljs provide better hints for this?

**Comment by thheller** [comment]
@Deraen `*warn-on-infer*` with `:infer-externs true` should be enough yes. `shadow-cljs` does a few enhancements to the externs inference to remove some false positives but otherwise it works the same.

Externs inference however might get a bit annoying for you since it will complain about all the JS interop you are doing.

```
(defn ^boolean reagent-component? [c]
  (some? (.-reagentRender c)))

(defn cached-react-class [c]
  (.-cljsReactClass c))

(defn cache-react-class [c constructor]
  (set! (.-cljsReactClass c) constructor))
```

You will get warnings for all of those although they are mostly fine. The Closure Compiler can safely rename those since only the CLJS code is going to access them anyways.

Same here, the `.-argv` is fine since it is not from React but the `.-props` needs a hint since it will otherwise be renamed.

```
(defn props-argv [c p]
  (if-some [a (.-argv p)]
    a
    [(.-constructor c) (shallow-obj-to-map p)]))

(defn get-argv [c]
  (props-argv c (.-props c)))

(defn get-props [c]
  (let [p (.-props c)]
    (if-some [v (.-argv p)]
      (extract-props v)
      (shallow-obj-to-map p))))
```

It would be enough to use `get-argv [^js c]` and `get-props [^js c]` here. You can still apply `^js` wherever it is complaining though. It'll just generate a few too many externs but those mostly don't hurt. CLJSJS packages often include a billion externs that aren't needed anyways.
