### ISSUE TITLE
nREPL

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-cljs#6]
I want to support nREPL since basically every tool uses nREPL. Cursive for example can only connect to a remote nREPL and not a Socket REPL (yet).

While developing I typically want a separate CLJ and CLJS REPL that don't interfere with each other. I may also be working on multiple CLJS builds at once where each needs its own CLJS REPL but they can share the CLJ one. One good example for this workflow are electron apps, you'd have one for the main app (`:node-library`) and one for the renderer (`:browser`).

I do not know how to best handle this in the UI side of things but for now I assume I have 3 different windows/tabs somewhere that I can switch between. One goes to the CLJ REPL and one for each CLJS REPL. Whatever I eval in the `renderer` CLJS should not affect the `main` in any way. The CLJ REPL can be used to control the CLJS build processes (ie. start/stop autobuild, test release build, launch cljs tests, etc).

I like verbose compilation output but it can get very annoying while working in a REPL and it constantly messing up the prompt. Ideally there would be an extra "log" section for each REPL window that shows the compiler output and detailed errors should a build fail.

The easiest path to get all this seems to be nREPL.

In order to achieve this there are 2 possible setups I can come up with:

- separate nREPL server per build
- special `cljs/*` commands that just use the default nREPL connection and provide a `:build` key that selects where commands should go.

## Server per build

Isolated `clojure.tools.nrepl.server` instances with their own private nREPL middleware stack specifically configured for CLJS. The server only knows how to talk to one build. The setup here seems simpler but juggling ports quickly gets annoying.

## `cljs/*` commands

This would basically just be a dedicated middleware injected into the main server. Extra care must be taken that all `:op` messages are targetted to a specific build. `piggieback` currently just hijacks `eval` when CLJS REPL is running so you cannot eval CLJ anymore. This sucks.

Adding commands is simple enough and this could be extended to allow tools to better work with the somewhat complex options CLJS builds may have.

- `{:op cljs/list-builds}` -> `[{:id :website :target :browser ...} ...]` as a quick way to let the client lookup all configured builds.
- `{:op :cljs/start-worker :build :website :autobuild true}` starts the development process for one of the configured builds.
- `{:op :cljs/sync :build :website}` wait for compilation to finish
- `{:op :cljs/eval :build :website :code "(+ 1 1)"}` eval the given `code` in the JS runtime connected to the build (TBD should be able to select which JS runtime is multiple are connected, ie multiple browser windows open for the same build)
- `{:op :cljs/stop-worker :build :website}` stop the worker
- `{:op :cljs/once :build :website}` compile dev build once (no REPL)
- `{:op :cljs/release :build :website}` compile release build 

Once one or more workers are started the nREPL server may start sending messages back to the client that weren't triggered by the client.

- `{:op :cljs/notify :build :website :type :build-log :message string?}`
- `{:op :cljs/notify :build :website :type :build-start}`
- `{:op :cljs/notify :build :website :type :build-complete :warnings [...]}` build finished, no errors, maybe warnings (may include more info)
- `{:op :cljs/notify :build :website :type :build-failure ...}` hard error that could not complete a build.

I'm not sure if it is worth capturing `prn` in the JS runtime. My logging in CLJS consists of `(js/console.log ...)` and nothing else but maybe there should also be a `:out` notify.

I started implementing some of it here:
https://github.com/thheller/shadow-devtools/blob/master/src/main/shadow/cljs/devtools/nrepl.clj

Now need to figure out if any editor would actually use this.  This should also be something the `figwheel` and `boot-cljs` want/can implement so we can find and agree on a standard for this. My sketch is pretty specific for `shadow-devtools` but should translate to any other build tool as well.

**Comment by thheller** [comment]
Ping @bhauman and @Deraen

Do you guys think something like what I described above is possible for your respective tools or are you happy to stick with `piggieback` and don't see a need for anything new?

**Comment by bhauman** [comment]
I've put a bunch of thought into this including thinking about a cljs only nrepl stack which also had a websocket nrepl server for browser communication.  The idea that you reuse the current nREPL "op"s is very appealing as well are reusing the nREPL transport for browser communication.

Reinventing the wheel here is going to provide dubious help to users at this stage.

Keeping piggieback or another tool like it seems important as it is supported at this point, it's supported by cider, reply etc. and is allows us to create a cljs build repl in an nREPL session.

It seems that real issue with Piggieback is two fold:
 * that after hijacking `op :eval` we are shut off from evauating clojure in the hijacked nREPL session.
 * this in turn prevents us from executing code in the context of the current cljs build and cljs repl (think `cljs.env/*compiler*` and `cljs/repl-env`) which is locked inside Piggieback nREPL session.

So it seems that the most "expressive" thing we can ask for, is arbitrary Clojure eval inside the Piggieback-ed nREPL session.  The key points that make this solution interesting, besides the fact that  PIggieback model is widely supported, is that arbitrary eval would have access to the Piggieback session's `cljs.env/*compiler*` so that we can compile etc, and we would have access the the `repl-env` for potential client communication. This would indeed offer a wide range of possibilities.

So, IMHO, a first step would be to add arbitrary Clojure `eval` in Piggieback or a piggieback like middleware.  Once you have arbitrary clojure eval the rest of the tooling needs (build start, build stop, notification, etc) can be implemented in a clojure library, again with the caveat that these library command will focus on the current `cljs.env/*compiler*`.

One way to get to easily try this out is to add a special-fn named  `clojure/eval` i.e. `(clojure/eval (figwheel/start-build))` in the cljs repl's `:special-fns`.

Another/better way is to add a flag `:piggieback/pass-through` to the eval "op" so that the eval passes through piggieback to the underlying nrepl interuptible-eval middleware. The evalled expression will now have access to the piggieback bound session vars, so the evaled clojure code can access the cljs.env/*compiler* that way.

Perhaps both are important additions.

But arbitrary clj eval in the cljs repl process seems like a big tooling win for cljs and for users of the cljs repl. Having the full expression of clj will give tooling authors options.  Limiting it to a set of ops for a particular middleware solution sounds challenging.

But the good news for you @thheller is that you would only need to write a library, and not a bunch of nrepl middleware.

cc/ @cemerick 
Above I talk about adding a `:piggieback/pass-through` flag to `op "eval"` messages sent to Piggieback which instruct Piggieback to forward nrepl-messages down to the underlying interuptable-eval middleware and ensure that the evaled Clojure code has access to the Piggieback session's current `repl-env` and the `cljs.env/*compiler*`

**Comment by thheller** [comment]
Hmm maybe we can actually just add an extra property to the `eval` op. So we get `{:op :eval :code "(+ 1 1)" :target :cljs|:clj}` and be done with it?

Although I feel that piggieback isn't really well equipped for handling multiple builds running in parallel. Also there is the issue of having multiple JS runtimes connected at once (ie. multiple browsers) that may have connected at different times. Do you broadcast to everyone? Which result do you use? What happens to the server side REPL state when the user reloads the page (ie. resets all REPL state).

The reason I wanted to use the the middleware with special `cljs/` commands was that it could serve as sort of the official interface/protocol which each tool can implement. So each IDE/Editor doesn't need to know about all possible tools (figwheel, boot, shadow, ...) but instead just have one client implementation.

**Comment by bhauman** [comment]
PIggieback/nREPL AFAIK is well equipped to one instance of piggieback per nREPL session.  So you create a session and upgrade it to piggieback.  

Piggieback is parameterized by the ReplEnv so you decide before you launch Piggieback which JS runtime you are going to be talking to.  The REPLEnv implementation determines the behavior of this communication like auto-reconnect, broadcast etc.  The interesting thing here is that the tooling library could be absolutely connection independent, between the repl-env and the nrepl transport all communication channels are taken care of, in fact the tooling is independent of nREPL.

You theoretically could use an "official" Clojure protocol library as an interface rather than a set of nREPL messages, but I think this stuff is still murky enough that there will be significant churn unless someone implements all the editors needs in one big very attractive library.

But I'm thinking first things first.

Once you have the `eval/passthrough` you can make a library that creates connection servers REPLEnvs and calls piggieback etc.

**Comment by cemerick** [comment]
Quoth @bhauman 

> Above I talk about adding a :piggieback/pass-through flag to op "eval" messages sent to Piggieback which instruct Piggieback to forward nrepl-messages down to the underlying interuptable-eval middleware and ensure that the evaled Clojure code has access to the Piggieback session's current repl-env and the cljs.env/*compiler*

This sounds fine to me, and would be very straightforward to implement (just a :passthrough flag on the eval request, I suppose). Fork it, experiment to make sure it satisfies your use case(s), then send over a PR.

**Comment by arichiardi** [comment]
Related to this, `unrepl` project is doing a good job at having an "upgradable" repl.

I stopped by to ask if @thheller currently uses `inf-clojure` for connecting to a `shadow-devtools` repl.
