### ISSUE TITLE
Externs must contain builtin for env BROWSER: whatwg_console.js using [viebel/klipse "7.9.1"]

### ISSUE THREAD

**Issue by strontian** [thheller/shadow-cljs#615]
Encountering the same error as this thread:

https://github.com/thheller/shadow-cljs/issues/576

But with [viebel/klipse "7.9.1"]. Will follow up if I can find out which dependency is causing it in that project.

Thanks!

**Comment by thheller** [comment]
The issue is the same as with `nubank/workspaces`. `klipse` contains too many direct dependencies that it shouldn't declare. See here: https://clojars.org/klipse

You can either add exclusions for all the dependencies (eg. google-closure-library, google-closure-compiler, ...) or klipse needs to fix it. Someone should really open an issue on the related `deps.edn` tooling causing this.
