### ISSUE TITLE
0 exit code on compilation error

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#63]
I use `a && b && b` in npm scripts a lot, which needs the correct exit code.

```
CLJS error in cirru_editor/comp/expression.cljs at 2:1
Invalid :refer, var respo.cursor/with-cursor does not exist
=>> echo $?
0
```

https://gist.github.com/jiyinyiyong/89745df80a8ef445ad7075fef87d6be7

**Comment by thheller** [comment]
Hmm this is surprisingly hard because of the server.

If `shadow-cljs server` is running and the `shadow-cljs compile foo` failed the JVM doesn't exit so we have no exit code.  Obviously can't call `(System/exit 1)` for the server. Need to figure out a way to convey exit info back to the CLI script when the JVM doesn't exit.
