### ISSUE TITLE
Pass recompiled ns data to test runner start function

### ISSUE THREAD

**Issue by dmitryn** [thheller/shadow-cljs#644]
When running test with test runner, i'm using [start](https://shadow-cljs.github.io/docs/UsersGuide.html#target-browser-test) function to trigger test run like:

```clj
(defn start []
  (clojure.test/run-tests 'foo-ns 'bar-ns 'baz-ns))
```

I'd like to know what namespaces were recompiled so i could run tests from that ns only. Would be useful to have it in args to `start` function.

**Comment by thheller** [comment]
FWIW this won't work with `cljs.test/run-tests` since that is a macro and cannot accept dynamic data. I'll get the data there first and then we will just have to figure out how to use it for tests :P

**Comment by dmitryn** [comment]
I may use `run-all-tests` which accepts regex to match namespaces https://clojuredocs.org/clojure.test/run-all-tests

**Comment by thheller** [comment]
If it only were that simple. Don't look at clojure docs for CLJS, things are different. `cljs.test/run-all-tests` is also also a macro and cannot take a dynamic regexp.

**Comment by thheller** [comment]
You might want to check out some recent changes I made in the testing department.

In particular

https://github.com/thheller/shadow-cljs/blob/5806c75bc9f84ab88eec135cf39e7a7caaf1e1fd/src/main/shadow/test/node.cljs#L44-L56

combined with `shadow.test/run-test-vars` which lets filter the vars it should run vs having a macro do that.

Note that there is still a macro that needs to run on every compile to gather all known test data. You could snapshot that data and compare it on the next go to find the changed tests.

So you need to have one ns that has

https://github.com/thheller/shadow-cljs/blob/5806c75bc9f84ab88eec135cf39e7a7caaf1e1fd/src/main/shadow/test/node.cljs#L2

and

https://github.com/thheller/shadow-cljs/blob/5806c75bc9f84ab88eec135cf39e7a7caaf1e1fd/src/main/shadow/test/node.cljs#L16-L18

Otherwise you new/removed tests won't be properly reflected anywhere.

**Comment by dmitryn** [comment]
@thheller thanks for mentioning it.

We're switching to https://github.com/lambdaisland/chui to run browser tests, i will check whether it'll be useful there.
