### ISSUE TITLE
Save origin URL of artifacts in classpath.edn

### ISSUE THREAD

**Issue by yenda** [thheller/shadow-cljs#645]
In our project we need to list all the dependencies used during compilation to generate some nix files and have a pure build.
classpath.edn seems like what we need but it is missing the URL of the artifacts.
Pomegranate may provide this https://github.com/clj-commons/pomegranate/blob/master/src/main/clojure/cemerick/pomegranate/aether.clj#L89 ?

**Comment by thheller** [comment]
It appears this isn't possible with the current `pomegranate`. It does not store the info in the dependency graph itself and it is only passed to the `:transfer-listener` when an actual download is triggered. This would make it a rather unreliable source in cases where some dependencies are already downloaded since there would be no URL info available.
