### ISSUE TITLE
Requiring with rename leaves local symbols with the same name undefined

### ISSUE THREAD

**Issue by p-himik** [thheller/shadow-cljs#653]
`reagent-playground/a.cljs`
```clojure
(ns reagent-playground.a
  (:require [reagent-playground.b :refer [f] :rename {f b-f}]))

(defn f [])

(js/console.log "A F" f)
```
`reagent-playground/b.cljs`
```clojure
(ns reagent-playground.b)

(defn f [])
```
`reagent-playground/core.cljs`
```clojure
(ns reagent-playground.core
  (:require [reagent-playground.a :as a]))

(js/console.log "A F2" a/f)
```
The JS console output is:
```
a.cljs:6 A F fnreagent-playground$a$f[]
core.cljs:5 A F2 undefined
```

**Comment by thheller** [comment]
This is essentially https://clojure.atlassian.net/browse/CLJS-1558.

The output is slightly different from normal CLJS because of the different `:refer` handling I guess but the underlying problem seems to be:
https://github.com/clojure/clojurescript/blob/6ed949278ba61dceeafb709583415578b6f7649b/src/main/clojure/cljs/analyzer.cljc#L1896.

Due to the resolve it'll end up overwriting `reagent_playground.b.f` in `a` since the `f` was resolved to `..b.f`. Not sure why it calls `resolve-var` in the first place.

CLJS sort of sidesteps this by removing the `:refer` when you `:rename` it. In `shadow-cljs` you can just leave out the `:refer`. But regardless the issue still exists in CLJS if you just refer without a rename.

```
(ns reagent-playground.a
  (:require [reagent-playground.b :rename {f b-f}]]))

(ns reagent-playground.a
  (:require [reagent-playground.b :refer [f]]))
```
