### ISSUE TITLE
HTTP and nREPL servers publicly accessible by default

### ISSUE THREAD

**Issue by Cnly** [thheller/shadow-cljs#660]
The primary HTTP server, development HTTP server and nREPL server all listen on `0.0.0.0` by default, which may raise some security concerns. Perhaps it's better if we only listen on localhost instead?

**Comment by thheller** [comment]
I'll leave this for the community to decide.

You should definitely not be running shadow-cljs without a firewall in an untrusted network.

I know that many people use setups that require `0.0.0.0` like `react-native` builds running on an actual device while developing. I also sometimes have `:browser` builds open on many devices to see changes hot-reloaded.

nREPL really has no reason to listen on `0.0.0.0` so I changed that default already in `master`.

It is probably better to be safe by default rather than convenient by default. The main concern probably is that the `:9630` websocket can eval stuff so you want to restrict access to it somehow without getting in the way too much.

**Comment by darwin** [comment]
Yes, let's do it. And add a new option which overrides default `localhost` to `0.0.0.0`. 
This way you can point people having issues to quickly try this "relaxed mode" if the issue persist there.

**Comment by thheller** [comment]
I added a basic restriction in 2.8.88 for now that only allows access to the "tool" websocket from localhost by default. Other IPs can be configured to be allowed via `:trusted-hosts #{"192.168.1.4"}` in `shadow-cljs.edn`.

That breaks the UI for anyone not trusted so it should probably just not allow opening the UI in the first place. Will think about this for a bit. I might just use a secondary port for the UI thats not accessible remotely.

**Comment by superstructor** [comment]
Speaking as someone who does need the development HTTP server on `0.0.0.0` to have builds running in virtual machines I still think the default should be `localhost` for security with listen on all interfaces as an opt-in via configuration. i.e. 'secure by default'.

**Comment by thheller** [comment]
With `2.10.0` I migrated everything to use the `shadow.remote` architecture. This means everything talks to one websocket endpoint which now does a security check. Basically the server generates a random UUID on each start and writes that into the build output when compiling code. The devtools websocket will use that token when connecting and the websocket will be rejected if its missing or incorrect. Therefore nothing can just randomly connect and start evaling stuff.

The webserver continues to listen on `0.0.0.0` but this is fine since it only serves static files and the websocket is secured. nREPL defaults to localhost. I removed the `:trusted-hosts` since its no longer required. Any client that has the correct server-token can connect and every client with code generated by the server will have it. This is of course all only relevent for dev builds.

I think this is much more secure than just IP checking. Still probably not a good idea to expose shadow-cljs on the public internet but should be much much safer than before.
