### ISSUE TITLE
Type inference warnings, externs inference gone when using `some->`

### ISSUE THREAD

**Issue by aisamu** [thheller/shadow-cljs#679]
(From clojurians, as requested)

We're running into an issue with the type inference warnings (and the automatic externs inference, it appears) when we thread js field accesses with some-> instead of ->:

```clojure
(def window (if (exists? js/window) js/window nil))
(def ^js jswindow (if (exists? js/window) js/window nil))

(js/console.log (-> js/window .-test))
(js/console.log (-> jswindow .-test))
(js/console.log (-> window .-test))

(js/console.log (-> js/window .-test .-identity))
(js/console.log (some-> js/window .-test .-identity))

(js/console.log (-> jswindow .-test .-identity))
(js/console.log (some-> jswindow .-test .-identity))

(js/console.log (-> window .-test .-identity)) ;; <---- Inference warning only here
(js/console.log (some-> window .-test .-identity))
```

It was observed on `2.8.68` and reproduced on `2.8.93`, both on `:browser` and `:npm-module` targets. 
Is it expected/unavoidable?

Thank you!

**Comment by thheller** [comment]
Oops, wrong id used in commit.

**Comment by thheller** [comment]
Don't think there is anything I can do from the shadow-cljs side.

I made the `^js` tag "sticky" in shadow-cljs so that when you access a property of something tagged with `^js` that return will also be tagged as `^js`. Maybe a little too generic but eliminates a whole lot of annoying interop issues.

Without the explicit tag the default CLJS rules apply which means `window` is tagged as `#{js clj-nil}`. `some->` seems to eliminate the `clj-nil` thus it becomes `js` only again. The `window.test` check does not eliminate `clj-nil` so it'll not be tagged at all and as such no inference is done.

When testing this with regular CLJS you'll get a lot more warnings, mostly because of the missing "sticky" logic.
