### ISSUE TITLE
[Random idea] can we emit ES6 import/export from cljs

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#702]
Current we have `:npm-module` which was added in 2017. And today most JavaScript users are switching to ES6 import/export, and Webpack added [tree shaking](https://webpack.js.org/guides/tree-shaking/) which removes unused code in code using ES6 import/export. I'm not sure if Webpack tree shaking really makes a big difference and especially for code from cljs. But speaking as a JavaScript user working with mostly TypeScript, code using ES6 import/export may be more usable. Even if someone wants to run code without Webpack, then [Chrome can make use of that](https://www.sitepoint.com/using-es-modules/).

**Comment by thheller** [comment]
It could use the same hack that `:npm-module` used and make it look like it was CommonJS when it wasn't. So I can make it use ESM import/export but they wouldn't be true modules so tree-shaking wouldn't work nothing would be "shaken" out.

I don't see a benefit in doing this as a hack. I've been thinking about make the CLJS compiler emit ES6 directly and I do see some benefit in that but that basically means re-implementing the entire analyzer/compiler and would likely not be compatible with a lot of code since the output would be much less dynamic in what it can do.

**Comment by jiyinyiyong** [comment]
Thanks for replying. I have no knowledge how ClojureScript compiler is implemented internally.

Seeing from appearance, a single ClojureScript file looks a lot like a ES6 import/export file since it uses mostly `ns`, `def` and `defn`s, if we not use macros. Yes the gain can be very little, and I don't know how people who are using `:npm-module` think about this. It's mostly an idea from the side a JavaScript user when many toolchains just switched to ES6 import/export.

**Comment by jiyinyiyong** [comment]
Taking a example:

```js
// Compiled by ClojureScript 1.10.758 {:target :nodejs}
goog.provide('app.main');
goog.require('cljs.core');
app.main.node$module$shortid = require('shortid');
app.main.main_BANG_ = (function app$main$main_BANG_(){
cljs.core.println.call(null,app.main.node$module$shortid.generate());

return cljs.core.println.call(null,"hello world");
});
app.main.main_BANG_.call(null);

//# sourceMappingURL=main.js.map
```

by 

> re-implementing the entire analyzer/compiler

did you mean all function calls like `goog.require` and all names like`app.main.node$module$shortid` need to be re-implemented?

**Comment by thheller** [comment]
Counter question: did you ever try https://github.com/angular/tsickle for turning TS code into JS consumble by the closure-compiler (and shadow-cljs)?

CLJS is built with the closure-compiler in mind and very liberal with using long names leading to large code-size because of the assumption that it is going to run through `:advanced` which takes care of all of that and makes it small (with many other optimizations of course).

If you instead run through webpack or any other "minifier" then you'll not get the same kind of reductions. So it would be absolutely possible to create look-like-ESM output but the code would be too large to be practical for any kind of website. It would be basically what you get by running with `:simple` optimiziations vs `:advanced`.

**Comment by jiyinyiyong** [comment]
> Counter question: did you ever try https://github.com/angular/tsickle for turning TS code into JS consumable by the closure-compiler (and shadow-cljs)?

nope..

Can't think in details but yes it could be hard problems trying a new one as project evolves in old ways. ClojureScript contains too many strange features compared to CoffeeScript I used before.

By browsing tsickle I noticed Closure Compiler already supports ES6 import in 2018 https://github.com/google/closure-compiler/wiki/JS-Modules as well as CommonJS. Itself is changing as JS community migrates. Does it have anything to do with our current implementation?

**Comment by thheller** [comment]
The CLJS output and the Closure Library assume they share one common global scope so everything can access everything with goog.provide/require ensuring that things are loaded in the proper order and so on.

With ESM or CommonJS there is no shared global scope but instead each file has its own scope. So you to either emulate that shared global scope which `:npm-module` does or actually change the code output to account for not having a shared global scope (which requires touching the analyzer/compiler).

Emulating the shared scope is trivial and does not require touching the compiler in any way, which is why `:npm-module` was "easy" to add.

PS: Oops, hit the wrong button.

**Comment by thheller** [comment]
Closure has good support for ESM these days yes. That does not change the restrictions that ESM brings with it though. It is too strict and makes hot-reload and REPL harder, not impossible but harder and possibly less dynamic.

**Comment by jiyinyiyong** [comment]
Sounds they are really different in design.

For the "shared global scope" thing, personally I debug ClojureScript with "Sources" in Chrome DevTools and barely connect app with REPLs. DevTools is also available for Node.js apps. Not sure about hot-reload since cljs seems to have extra features than Webpack..

Thanks for explanations.
