### ISSUE TITLE
Add an option for react native builds using tiny js "loader" file on startup 

### ISSUE THREAD

**Issue by flexsurfer** [thheller/shadow-cljs#704]
https://clojurians.slack.com/archives/C6N245JGG/p1588770846255500

yenda: it seems like shadow-cljs make a much bigger bundle than what we had before with clj and figwheel, is there some fundamental differences? It is only a problem on a specific device where the bundle crashes the js engine 90% of the time the problem is in dev

thheller(opens in new tab)  4:13 PM
well technically the same but for development all files are combined into one, re-natal loads many small files dynamically

thheller(opens in new tab)  4:33 PM
FWIW it would be trivial to provide a secondary approach like re-natal/krell do that only load a tiny js "loader" file on startup and that then loads everything else dynamically

I opted not to do that because of the async layer it introduces, ie. making "loading" async in dev but not in production

also takes a lot longer to load initially if done async in my tests

but yeah I imagine the file can become quite big in larger projects

**Comment by thheller** [comment]
I'd like to have a bit more data before actually doing that. The amount of JavaScript loaded by this method is basically identical. It is just loaded in many file xhr/fetch requests instead of one big file. So the amount of javascript executed is identical.

- What is the size of the big file that causes failures?
- What is the device? Is it just one or do others fail?
- How does it fail?
- When does it fail?
- Does it fail while the file is loaded or when their contents are eval'd? The code is included as a string and eval'd at runtime to bypass metro processing the sources in any way.
- Does the problem occur with `releasse` builds?

The reason I went with this method is simply because shadow-cljs does not need to become part of your loading process. With re-natal/krell you need to use their provided entry points so that they can register their own root component to show a "placeholder" and then replace when they are done loading all files. That limits options since expo does things differently than react-native etc.

While the code to provide the alternate loading method is minimal its implications are not and I'd like to first investigate why it is a problem in the first place.

**Comment by flexsurfer** [comment]
ping @yenda @rasom

**Comment by flexsurfer** [comment]
not an issue anymore with latest  RN and source-map turned off https://github.com/thheller/shadow-cljs/commit/683a4fe564e434abd2c8c514841263dd553c66db
