### ISSUE TITLE
Cider hangs, cannot recognize prompt and wait on output

### ISSUE THREAD

**Issue by arichiardi** [thheller/shadow-cljs#72]
Hi again, just reporting the discoveries so that we can keep track of them:

I bootstrapped `cljs/dev` on the same project of the other issue and this is the console output:
```
shadow-cljs - starting ...
shadow-cljs - server running at http://localhost:34065
shadow-cljs - socket repl running at localhost:43473
shadow-cljs - nrepl running at localhost/127.0.0.1:40017
shadow-cljs - starting node-repl
[:node-repl] Configuring build.
[:node-repl] Compiling ...
[:node-repl] Build completed. (28 files, 1 compiled, 0 warnings, 1.04s)
[0:0]~cljs.user=> JS runtime connected.
[:app] Configuring build.
[:app] Compiling ...
[:app] Build completed. (27 files, 13 compiled, 0 warnings, 3.03s)
```

However, `cider` cannot recognize and font-lock the prompt, plus it prints a `Stdin:` thingie at the bottom, probably some `cider` settings to tweak.

Here is a pic:

![2017-07-13-012304_951x648_scrot](https://user-images.githubusercontent.com/1724788/28157307-e9cf3c36-676a-11e7-9f90-09bf04f054e0.png)

Thanks for your work on `shadow-cljs` as usual! :+1:

**Comment by thheller** [comment]
`(cljs/dev :app)` launches a new REPL which reads from `stdin`. So that probably only works well with `inf-clojure` as `nREPL` has its own `needs-input` mechanism. `cider` seems to do the `Stdin: ` thing then.

Try running
```clojure
(cljs/watch :app)
(cljs/nrepl-select :app)
```

Which would switch the current nREPL session to the CLJS REPL of :app.

`:repl/quit` or `:cljs/quit` would reset the nREPL session back to CLJ.

`(cemerick.piggieback/cljs-repl :app)` also works, so in theory the CIDER piggieback stuff should just work. I don't know how CIDER handles this usually but I tried emulating all the necessary bits. IIRC Cider usually has 2 buffers, one for CLJ one for CLJS. The same should just work.
