### ISSUE TITLE
Gnome gjs compile target

### ISSUE THREAD

**Issue by titonbarua** [thheller/shadow-cljs#724]
Hi,
I have been looking into interacting with Gnome desktop with Clojure. Apparently, there is a Javascript engine for Gnome: https://gitlab.gnome.org/GNOME/gjs

I have done some research with Clojurescript compiler with custom `:target-fn` and had some limited success(I was able to generate the glue js code, but import mechanism hooking was not working, as I am yet to understand how to pass a proper `env`. ). Now, shadow-cljs looks like a better venue, as it already provides a variety of compile targets. I would appreciate if anyone gives me some brief pointers on how to do it in shadow-cljs.

**Comment by thheller** [comment]
Writing custom targets is rather undocumented so only thing I can point to is the official targets that I wrote.

- https://github.com/thheller/shadow-cljs/tree/master/src/main/shadow/build/targets

I don't know what `gjs` is capable off so you might not be able to use certain features (eg. Websockets are required for hot-reload/REPL).

The [:graaljs](https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/build/targets/graaljs.clj) target might be simplest example. You can just swap out the [bootstrap](https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/build/targets/graaljs.clj#L33) file with something gjs specific if needed. Otherwise the output is just a single self-contained file.

Happy to help if you have specific questions.

**Comment by titonbarua** [comment]
Thanks for the pointer. :) I modified the node-script target to implement a new one for gjs at PR #730. 

Note that I'm yet to add any tests/demo related to gjs. But the demo code attached to the PR documentation runs without any issues ( except some ugly undefined property warnings ).

**Comment by thheller** [comment]
Fixed via https://github.com/titonbarua/shadow-cljs-gjs-target
