### ISSUE TITLE
shadow-cljs watch produces broken compilation files when upgrading npm dependencies

### ISSUE THREAD

**Issue by nickpell** [thheller/shadow-cljs#727]
I'm using ```shadow-cljs watch``` successfully. However when I upgrade certain npm dependencies the compiled javascript contains errors like those I've reproduced here: 
https://github.com/nickpell/shadow-cljs-watch-error#shadow-cljs-watch-error

I've been able to run ```shadow-cljs release``` with the updated dependencies and run the compiled javascript without issue.

@martinklepsch @acmcc

**Comment by thheller** [comment]
Thanks for the repro. I can reproduce with this. Most likely a cache problem, wiping `.shadow-cljs/builds/frontend/dev` makes it work again as well. I'll investigate.

**Comment by thheller** [comment]
I honestly don't know what to do about this. This seems to exhibit a couple different issues all related to the same underlying root cause. At least as far as I can tell.

The issue seems to be that the watcher for `node_modules` gets into a confused state since npm modifies too many files and sometimes seems to write files before writing all the dependencies that package may need.

If there is a delay between updates (eg. downloading a package takes a bit) then the `watch` will trigger a compile although `node_modules` is not in its final state. Depending on the state it is in you might get build errors or packages compiling against the previously installed versions but expecting a newer one.

I wonder if npm or yarn create some kind of "hey I'm working here" file one could detect? Wonder what webpack does?

I guess I'll just throw away all cache when `node_modules` change but that doesn't seem ideal.

**Comment by thheller** [comment]
Please try `2.10.8`. I think I fixed the cache bug. At least I couldn't reproduce any more failures even after constantly installing different versions.

**Comment by nickpell** [comment]
Thanks, that fixed the issue.
