### ISSUE TITLE
Websocket connection once again closed on sleep

### ISSUE THREAD

**Issue by mtruyens** [thheller/shadow-cljs#728]
Similar to https://github.com/thheller/shadow-cljs/issues/582, I get a _"The Websocket connection was closed!"_ error when sleeping (even if just for a second) and then waking my Mac.

This happens since the latest version of Shadow (2.10.5, previously I used 2.9.6). It only happens in the Chromium-based browsers, not in Firefox.

**Comment by thheller** [comment]
Ah right. When I rewrote the ws code I forgot to add the reconnect logic. I'll see if I can make it more reliable this time. It was a little annoying before.

**Comment by mtruyens** [comment]
Thanks for the quick turnaround! 

Unfortunately, 2.10.6 does not seem to solve the problem...

**Comment by thheller** [comment]
Never said it would. ;)

I spent 3 hours yesterday trying to figure out how to do this without constantly doing it. I didn't like the previous solution since there were too many cases were it got really annoying. Constantly trying to connect although the server was cleary gone, etc.

The problems I observed and can't figure out how to fix are the following:

- On macOS Chrome (my macbook) the websocket connection immediately closes when closing the lid. I get the ws close event and if I reconnect immediately the connection actually goes through and connects and works properly for a couple seconds. Then after 20sec the ws ping/pong times out and the relay kicks the connection. Chrome never realizes it was disconnected though. If I open the lid again too quickly (eg. after 30sec) it will continue too think it is connected but never receive or send anything. It will timeout eventually after 5min or so and reconnect but it takes way too long for anything practical.

- On Firefox or Win Chrome the behavior is somewhat better. The websocket just stops responding after a while to ping request and the relay will terminate. On wakeup the client gets to the close event and can properly reconnect. In Firefox it errors out sometimes with something about illegal state during page load. Can't figure out why it sometimes works and sometimes doesn't.

- I can't rely on any kind of DOM related events since this also needs to work with Workers. Can't have the main thread reconnect but the Worker sit there forever doing nothing.

The usual `goog.net.WebSocket` impl has reconnect logic with exponential backoff. This sort of works ok-ish but still has this annoying reconnect in Chrome that is essentially useless because it will die rather soon anyways. Depending on where it backed off to it also takes too long.

I'm trying to figure out how you are supposed to do this properly but its really hard to find any info on that topic. It may just be a bug in Chrome on macOS. The Firefox behavior is way more consistent.

**Comment by mtruyens** [comment]
You clearly have investigated this a lot deeper than I ever have. 

I can only say that I have been using Sente without any problem for over 3 years in my own commercial product (incl. waking up over sleep, even with a different IP address)...

**Comment by thheller** [comment]
Yeah its easy enough if it just constantly tries to reconnect. I just don't like that approach very much ... there must be a better way. Just can't find it .. maybe there isn't. If all else fails I will just do it but I haven't given up just yet.

**Comment by chenyong** [comment]
> I can't rely on any kind of DOM related events since this also needs to work with Workers. Can't have the main thread reconnect but the Worker sit there forever doing nothing.

if it's not reliable to detect on browsers, would be it be better to detect on shadow-cljs server and expose the state via HTTP?

**Comment by thheller** [comment]
Not sure what you mean. The server already knows that the client disappeared. It just doesn't know why. If it knew that it went to sleep and woke up it still can't tell the client.

I think I'll probably just settle on trying to reconnect constantly and just stop after a couple failures. Still can't believe there is way to detect sleep mode though.

**Comment by chenyong** [comment]
I was trying so say shadow-cljs may detect computer sleep on its server. Since there is not a constant and viable way to detect computer sleep from every client, maybe we just give up detecting on client and detect by asking the server via HTTP requests.

> I think I'll probably just settle on trying to reconnect constantly and just stop after a couple failures. Still can't believe there is way to detect sleep mode though.

Sounds good to me.

Usually I retry my own websockets on visibilitychange event. Can I still tell shadow-cljs to retry reconnecting with my own code when I got visibilitychange events?

**Comment by thheller** [comment]
> I was trying so say shadow-cljs may detect computer sleep on its server. 

Yes, but it can't tell the client so it doesn't really solve anything.

There are no hooks for you to call to force a reconnect. Don't plan on adding any.

I don't think visbilitychange is that useful either. Quite often I'll have tabs in the background not actually visible but still talking to them via REPL. Want the behavior to be a bit more consistent than that.
