### ISSUE TITLE
hot reload npm linked packages 

### ISSUE THREAD

**Issue by alidlorenzo** [thheller/shadow-cljs#759]
I'm not sure if this was ever an intentionally a feature, but in version 2.8 of shadow-cljs, I could make changes to a linked npm package and hot reloading would work. After upgrading, I'm noticed this stopped working.

I've verified this works in version 2.8.62, it does not work in the latest 2.10.14 version, nor in other 2.10 and 2.9 versions that I tested.

**Comment by thheller** [comment]
I removed that feature because it was using far too many resources in builds using thousands of files from `node_modules` which could just come from a single package. It also frequently broke when running `npm install` because of the amount of files modifications that does. It will not be coming back.

However shadow-cljs still checks the `package.json` files of the packages and if those are modified will trigger a re-compile. So it will still detect new `npm install` versions. So you could `touch node_modules/your-package/package.json` after making changes in your JS?

What is the reason however that you are building a npm package this way? Can't you just include the code directly via 
https://shadow-cljs.github.io/docs/UsersGuide.html#classpath-js

**Comment by alidlorenzo** [comment]
I use / work on some standalone Javascript libraries, so the JS files are not in the same Clojurescript project. 

I wouldn't mind touching the package's package.json if that's what works, much better than having to restart the entire shadow-cljs server 😅

**Comment by idhowardgj94** [comment]
touch is not work.

I'm give up typescript react component + clojurescript shell idea...
it seems not possible to have a good dev environment.
