### ISSUE TITLE
Integration with ProtoREPL

### ISSUE THREAD

**Issue by shaunlebron** [thheller/shadow-cljs#76]
Ryan (@rgdelato) has written an [Atom guide for cljs](https://clojurescript.org/tools/atom), and has expressed a desire for [ProtoREPL](https://github.com/jasongilman/proto-repl) to add support for cljs _auto-completion_ and _jump-to-definition_ , as it is currently only supported for clojure.

Is this something shadow-cljs can help with?

**Comment by thheller** [comment]
I did a quick test to confirm that ProtoREPL work with shadow-cljs.
https://github.com/thheller/shadow-cljs-examples/tree/master/proto-repl

Beyond that it is really up to the ProtoREPL developers. I assume they want to support `figwheel` which means they probably want to use `piggieback`. `shadow-cljs` provides `piggieback` emulation so it should just work.

`cider-nrepl` should work if the `:middleware` is configured.

**Comment by thheller** [comment]
See #62.

This was the last thing I tried with `emacs` and `cider-nrepl`.
```
 :dependencies
 [[cider/cider-nrepl "0.14.0"]]
 :nrepl
 {:port 8202
  :middleware
  [cider.nrepl.middleware.apropos/wrap-apropos
   cider.nrepl.middleware.classpath/wrap-classpath
   cider.nrepl.middleware.complete/wrap-complete
   cider.nrepl.middleware.debug/wrap-debug
   cider.nrepl.middleware.format/wrap-format
   cider.nrepl.middleware.info/wrap-info
   cider.nrepl.middleware.inspect/wrap-inspect
   cider.nrepl.middleware.macroexpand/wrap-macroexpand
   cider.nrepl.middleware.ns/wrap-ns
   cider.nrepl.middleware.pprint/wrap-pprint
   cider.nrepl.middleware.pprint/wrap-pprint-fn
   cider.nrepl.middleware.refresh/wrap-refresh
   cider.nrepl.middleware.resource/wrap-resource
   cider.nrepl.middleware.stacktrace/wrap-stacktrace
   cider.nrepl.middleware.test/wrap-test
   cider.nrepl.middleware.trace/wrap-trace
   cider.nrepl.middleware.out/wrap-out
   cider.nrepl.middleware.undef/wrap-undef
   cider.nrepl.middleware.version/wrap-version]}
```

**Comment by thheller** [comment]
It appears that ProtoREPL uses manually generated bits of CLJ code for autocompletion [1]. Instead of the `nrepl` `complete` command which `cider-nrepl` would provide.

One could certainly also just send a bit of CLJ code what returns the completions for CLJS code.

The CLJS compiler env for a given build can be obtained by calling (I can add an "official" function to the api if anyone actually wants to use this)

```
(def x (-> (shadow.cljs.devtools.api/get-worker :app)
           (:state-ref)
           (deref)
           (:compiler-state)
           (:compiler-env)))
```

Be careful not to print `x` since it can get quite huge. cljs-complete [2] should work by just calling `(cljs-tooling.complete/completions x "al" 'cljs.core)`.

[1] https://github.com/jasongilman/proto-repl/blob/master/lib/completion-provider.coffee
[2] https://github.com/clojure-emacs/cljs-tooling

**Comment by rgdelato** [comment]
@thheller It'll definitely take me a bit to get up to speed with all of this, but I really appreciate all of this info, so thank you! I agree that most (if not all) of the changes to support this would need to be on the ProtoREPL side.

**Comment by thheller** [comment]
@rgdelato most tools seem to take the `nrepl+piggieback` route which has middleware for most commands and that middleware handles what it applies to (CLJ or CLJS) by looking  at the nrepl session object.

So you'd send a `{:op "complete"}` message instead of `"eval"` and if the session is CLJ (default) you get CLJ autocomplete. If `piggieback` is active you'd get CLJS completion results.

I personally hate this approach and would have done `{:op "clj/complete"}` and `{:op "cljs/complete"}` or something similar. However if you want `figwheel` or `boot` support I'd probably stick to `piggieback`.

I think `cider-nrepl` has documentation for the various nREPL ops it supports, not sure where though.

**Comment by arichiardi** [comment]
The documentation for the nRepl middleware is in the middleware itself, an example: for completion it is here: https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/complete.clj#L49-L68

**Comment by thheller** [comment]
Closing this since there isn't much `shadow-cljs` can provide unless it did so in a way that breaks every other CLJS tool which is not ideal.

**Comment by arichiardi** [comment]
@thheller sorry to reopen a closed discussion but I did not understand if shadow includes and answers to completion nRepl messages. If not I would be interested in understanding how to do it. If yes, that's great!

**Comment by thheller** [comment]
`shadow-cljs` answers nothing related to completions. This is handled entirely by nrepl middleware which you need to provide/configure yourself. If `cider-nrepl` is on the classpath those will be automatically. `cider-jack-in` adds `cider-nrepl` automatically but when running the process manually you need to add them to your `:dependencies` manually.

cider also recently switched the `piggieback` namespaces and my emulation does not yet account for the new namespaces. I'm not sure if the old version is still supported?
