### ISSUE TITLE
A suggestion for UI enhancement for inspect

### ISSUE THREAD

**Issue by mjmeintjes** [thheller/shadow-cljs#768]
I've been using shadow.inspect (http://localhost:9630/inspect/1/tap) pretty heavily and it works really well.

However, it would be nice to be able resize/maximize/minimize the different panels. When navigating into a object, I sometimes get deep enough that I can't see the data:

![image](https://user-images.githubusercontent.com/72253/89520408-eaa68480-d831-11ea-9c4f-6034f705bc44.png)

It would be great if I can click a button to maximize each of the panels. 

Maybe something like this:
https://github.com/STRML/react-grid-layout

**Comment by thheller** [comment]
I'm aware of the issues and have run into those myself. Can't use `react-grid-layout` since the UI doesn't use `react` anywhere but I also don't really think that rearranging stuff is very useful and resizing shouldn't be necessary at all when built correctly. So a lib like that seems like overkill.

I have several UI tweaks planned though. The "path" taken into the object doesn't really need to be always visible and could easily just stay one line that expands on click/mouseover. The Eval window also doesn't need to be always visible. I'm also not quite sure always showing the history is necessary so the Object Inspect view may just become "fullscreen". I hope to get a bunch of stuff done in this area in the next few weeks.

**Comment by mjmeintjes** [comment]
Thanks. It would be great to have some improvements to the inspect UI, as it is such a useful tool. Have you thought about moving it into it's own project? Or is it too linked to shadow-cljs?

**Comment by thheller** [comment]
The underlying [shadow.remote](https://github.com/thheller/shadow-cljs/blob/master/doc/remote.md) architecture will likely become standalone at some point when it is more stable. Its all built on that open protocol so in theory anyone can builds UIs for this but the UI I build will likely stay coupled to shadow-cljs. Basically the only thing missing is a lightweight way to get CLJ talking to the relay remotely since that is only implemented locally currently. The CLJS impls are coupled to shadow-cljs but could be implemented for other tools as well.

**Comment by thheller** [comment]
In `2.10.22` I slightly changed how things stack when navigating. It honestly isn't much better than before but I spent waaaaaaaay to much time trying to find a good solution and came up empty. Any suggestions are welcome.
