### ISSUE TITLE
2.11.21 does not recognize #shadow/env when env is not set

### ISSUE THREAD

**Issue by Wegi** [thheller/shadow-cljs#779]
Since upgrading to 2.11.21 the following error happens when we use the `#shadow/env` macro inside the config:

 `No dispatch macro for s.`

This disappears as soon as the environment variable is set or a default value other than nil is provided. 
The behavior is the same with `#env`.

**Comment by thheller** [comment]
This was a bug in `tools.reader`. See https://clojure.atlassian.net/projects/TRDR/issues/TRDR-62

It is fixed in master. Hopefully with a release today.

Until then you can use `#shadow/env ["FOO" "defaultValue"]` which uses either the `FOO` env or `"defaultValue"` if not set. `#shadow/env ["FOO" ""]` would be the equivalent of previous releases.

**Comment by Wegi** [comment]
Thank you for the quick answer. Looking forward to it. :)

**Comment by thheller** [comment]
Fixed in `2.10.22`.
