### ISSUE TITLE
2.11.8 / c8acc440babe592b2c422b383cce5588ae4fd340 broke date-fns usage

### ISSUE THREAD

**Issue by hoxu** [thheller/shadow-cljs#806]
`:entry-keys` change in c8acc440babe592b2c422b383cce5588ae4fd340 seems to have broken date-fns usage in our project with the following exception:

> Uncaught RangeError: locale must contain localize property

I verified c8acc440babe592b2c422b383cce5588ae4fd340 is the issue by adding the following to `shadow-cjs.edn`:

```clojure
{:builds {:app {:js-options {:entry-keys ["browser" "main"]}}}}
```

This fixes the issue, and removing it reintroduces it.

Here is the relevant require:

```clojure
(:require
  ["date-fns/locale/fi" :as fi]
```

With the `:entry-keys` change, this makes `fi` become an object with `__esModule: true` and `default` property.

I can change the require to:

```clojure
(:require
  ["date-fns/locale/fi" :default fi]
```

which _seems_ to return similar object to what used to work, and it contains `localize` property, but it still causes the exception!

Any ideas what is going wrong?

FWIW, we are using date-fns with react-datepicker.

**Comment by thheller** [comment]
That is unfortunate but somewhat expected.

Some packages are shipping ESM code under the "browser" entry while others ships the "old" CommonJS and use "module". There really isn't anything to do from the shadow-cljs side. Some packages work while others break, changing the default will just change which. There will always be a few bumps in the way as more and more things move towards shipping ESM. You can either change your code or add the old `:entry-keys` back.

**Comment by hoxu** [comment]
> which _seems_ to return similar object to what used to work, and it contains `localize` property, but it still causes the exception!

Turns out that `:require` change was the only one required - the exception came from another location that still used the old version. Apologies for the confusion.

> There really isn't anything to do from the shadow-cljs side. Some packages work while others break, changing the default will just change which. There will always be a few bumps in the way as more and more things move towards shipping ESM.

I can appreciate the hardship with Javascript module systems, but respectfully I think making this default configuration change in a patch version (2.11.7 -> 2.11.8) of shadow-cljs was a bad idea, as things can be expected to break, and patch versions are not usually expected to make breaking changes.

Also, regarding [the documentation on js-entry-keys / CommonJS vs ESM](https://shadow-cljs.github.io/docs/UsersGuide.html#js-entry-keys):

> You can configure shadow-cljs to prefer the module entry via the :entry-keys JS option. It takes a vector of string keys found in package.json which will be tried in order. The default is "["browser" "main" "module"].

My understanding from this is that the first found key in the package's `package.json` is used?

If so, why does changing this in `shadow-cljs.edn`:

```clojure
:js-options {:entry-keys ["browser" "main" "module"]}
```

to this:

```clojure
:js-options {:entry-keys ["browser" "main"]}
```

change the resulting object of [`date-fns/locale/fi`](https://github.com/date-fns/date-fns/blob/master/src/locale/fi/index.js) require?

date-fns [`package.json`](https://github.com/date-fns/date-fns/blob/master/package.json) contains both `main` and `module` keys:

https://github.com/date-fns/date-fns/blob/38f727ba038a62d4c514033e5dde815c077ff5f9/package.json#L20-L21

My limited understanding is that because `browser` is first in the list, the change should not affect date-fns requires.

**Comment by thheller** [comment]
```
["date-fns/locale/fi" :default fi]
;; resolves to
;; https://unpkg.com/date-fns@2.16.1/locale/fi/index.js
```

FWIW this doesn't use `:entry-keys` at all so I'm guessing you maybe just bumped the version of the package and they changed it? Make sure you keep your `package-lock.json` in git so you don't get unexpected updates.

The reason this is a minor change is because it shouldn't change how any packages behave. It is out of my control whether or not packages themselves suddenly switch the "browser" entry from commonjs to ESM. Sorry if I expressed that incorrectly. The only thing the code change did is adding "module" at the end because more packages started popping up that had neither "browser" nor "main" and only used "module". So they just went from not working to working but all other packages should be unaffected.

**Comment by hoxu** [comment]
I'm confused.

If I add or comment out `"module"` in `[:builds :app :js-options :entry-keys]` (`["browser" "main" "module"]`), it definitely changes what `date-fns` requires return.

Without `module`:

`["date-fns/locale/fi" :as fi]` => expected `locale` object
`["date-fns/locale/fi" :default fi]` => undefined

With `"module"`:

`["date-fns/locale/fi" :as fi]` => object with `__esModule: true` and `default`
`["date-fns/locale/fi" :default fi]` => expected `locale` object

And `date-fns` version does not change, as I'm not even running `npm install`.

```
$ npm list date-fns
...
├── date-fns@2.16.1
└─┬ react-datepicker@3.2.2
  └── date-fns@2.16.1 deduped
```

Are you saying this should not be the case? Am I missing something?

**Comment by thheller** [comment]
I'm just as confused as you.

If you look at the `node_modules/date-fns/locale/fi` folder you'll find a `package.json` with
```
{
  "sideEffects": false,
  "module": "../../esm/locale/fi/index.js",
  "typings": "../../typings.d.ts"
}
```

`shadow-cljs` reads that file according to the "spec" and finds `module` and follows it. For whatever reason that "redirects" to the ESM file. Without `module` it won't find an "entry" in `package.json` and follow the next logic which is looking for `node_modules/date-fns/locale/fi/index.js` which it finds and uses.

In this package adding `module` will change the behavior, because the `package.json` only has `module`. There are so many different ways things are packaged it seems impossible to support them all at the same time.

**Comment by hoxu** [comment]
> In this package adding `module` will change the behavior, because the `package.json` only has `module`. There are so many different ways things are packaged it seems impossible to support them all at the same time.

Thanks for the explanation, now I understand what happens! I can only imagine how difficult writing logic for this is when compounded by all the various javascript packages.

I guess this is a good opportunity to thank you for all the work you put into shadow-cljs! 💁‍♂️🏅❤️

**Comment by hoxu** [comment]
Did shadow-cljs behavior regarding this change between 2.11.9 and 2.11.18 again, possibly because of 8b7f3964e732bc13a9981ba390908dd90f70f2e0?

`shadow-cljs.edn` contains (the same as default currently):

```
{:builds {:app {
...
                 :js-options {:entry-keys ["browser" "main" "module"]}
```

And now it seems `["date-fns/locale/fi" :default fi]` started returning `null`. `["date-fns/locale/fi" :as fi]` works again. So in essence the behavior seems to be the same as before c8acc440babe592b2c422b383cce5588ae4fd340.

Can we expect this behavior to stay now in the future?

Also, I'm repeating my earlier point that instead of doing compiler-related changes in patch versions, please bump the minor version. Even though there is no changelog of breaking changes, it would give a better heads up when to expect potential breakage!

**Comment by thheller** [comment]
> Also, I'm repeating my earlier point that instead of doing compiler-related changes in patch versions, please bump the minor version.

**I will also repeat: It is out of my control whether or not packages themselves suddenly switch the "browser" entry from commonjs to ESM.** Or how they bundle in general.

There has been no change in `shadow-cljs` regarding this behavior. I setup a test project and tested against `2.11.9` and `2.11.18` both with or without `:entry-keys` config. The result is the same.

I suspect that you changed your `date-fns` version and they changed something. I cannot possibly test against that.

> Can we expect this behavior to stay now in the future?

I don't have a clue. Ask the package authors.

I have never made an intentional breaking change in a minor version bump. The break you observed was due to adding new behavior that accidentally covered a behavior that I didn't even know existed before that. I cannot possibly test against all possible npm packages to judge whether any change I made warranted a major bump or not.

The behavior regarding `shadow-cljs` WILL have to change at one point since more and more packages are moving towards using "package exports" that `shadow-cljs` does not support that yet. Changing that behavior will likely be a major bump.

If I know there will be breaking changes I will mark them as such. Don't ask me to warn you about breaking changes I don't know exist please.

**Comment by hoxu** [comment]
Apologies for my comment that came off as rude, and for blaming shadow-cljs! You are correct; it turns out I didn't notice `date-fns` changed from [2.16.1 -> 2.17.0](https://github.com/date-fns/date-fns/compare/v2.16.1...v2.17.0). And indeed with 2.16.1 `:default` works, while with 2.17.0 `:as` works.

As there is nothing to fix in shadow-cljs, I'm closing this issue.

Thank you for your help!
