### ISSUE TITLE
uberjar not building

### ISSUE THREAD

**Issue by johannesloetzsch** [thheller/shadow-cljs#823]
Trying to build an uberjar by 
```shell
lein uberjar
```
fails complaining, that `src/main/shadow/cljs/devtools/cli.clj` misses `(:gen-class)`.

Would be great if this could be fixed or if you explain another way how to build an uberjar of shadow-cljs.

I love the [idea of publishing the uberjar for every release](https://github.com/thheller/shadow-cljs/issues/160#issuecomment-355819940). It would ease the use in CI/CD tasks and packaging for distributions like nixos, allowing reproducible builds without having the need of downloads in the compilation stage of the target project.
If it's fine for you, I could provide the changes to `.circleci/config.yml` for the release task.

**Comment by thheller** [comment]
`uberjar` is not useful. I experimented with it and it is far too problematic because of dependency issues.

You really do need proper dependency manangement and nobody is going to use `java -jar shadow-cljs-uber.jar` to do things. There is currently a normal variant and the AOT variant published to clojars. lein/deps.edn users default to using the regular thing and shadow-cljs.edn (via npm) defaults to using the AOT version.
