### ISSUE TITLE
Display actual address instead of localhost

### ISSUE THREAD

**Issue by deas** [thheller/shadow-cljs#878]
Appears the system "always" displays `available at ... localhost...` which might not be accurate (can be verified with `netstat` amongst other things).

This got me pretty confused as `localhost` does not work for me in some scenarios, so I tried to "fix" a phantom issue because I actually had the behavior I was after. The reverse may apply in other scenarios. You think you are exposing locally only when in fact you are exposing on the "real" network.

Saw this using `shadow-cljs 2.11.23`

**Comment by thheller** [comment]
I'm unsure what you are referring to here. There are many different networks addresses that'll be bound?

The default unless otherwise configured is to bind to `0.0.0.0` for the UI/websocket stuff. For display purposes this is displayed as `localhost`. Stuff like nrepl/socket-repl binds to `127.0.0.1` by default since they can be more restricted.

**Comment by deas** [comment]
Yes, the addresses.

"available at ... localhost" is actually correct but it was still confusing me. I was expecting the service to listen at 127.0.0.1:<port>

Hence, I was trying `:host "0.0.0.0"` in `shadow-cljs.edn` and expected "available at http://0.0.0.0:...". Whatever I tried, it always gave me `available at ... localhost ...`.

Been working quite a bit with jetty lately, and it says:

```
Started ServerConnector@4847fe15{HTTP/1.1}{0.0.0.0:8080}
```

which likely contributed to my confusion.

Personally, I prefer the network address beeing displayed.

**Comment by thheller** [comment]
It doesn't display `http://0.0.0.0:9630/` since clicking that does not work. I usually start `shadow-cljs server` and then click the URL in the terminal to open the UI. So it literally has this piece of code to replace it with `localhost`.

https://github.com/thheller/shadow-cljs/blob/e2196c2d14ea206b40a1f2078dc851a940ffae72/src/main/shadow/cljs/devtools/server.clj#L491

It won't be displaying `0.0.0.0`. If you set a custom IP via `:http {:host "whatever"}` it'll display that. You are free to change that.
