### ISSUE TITLE
object property replaced in advanced compilation that shouldn't be

### ISSUE THREAD

**Issue by bago2k4** [thheller/shadow-cljs#885]
I am not sure this is the right place, if not please let me know who I should be bothering and i'll leave you alone 😄 

I have recently updated shadow-cljs to 2.12.5 version and I have an issue with `goog.net.cookies`.

If I build my project with optimizations none it works just fine, that's why I'm writing here and not in `google/closure-library`.

The problem is that `goog.net.Cookies/set` is always setting a session cookie instead of using the provided expiration time.
It happens in the advanced build since the `maxAge` property is replaced with a compiled symbol.

Here is a piece of compiled code:
```
if ("object" === typeof c) {
      var e = c.sl;
      d = c.secure || !1;
      var f = c.domain || void 0;
      var h = c.path || void 0;
      var m = c.lk
  }
```
that correspond to this piece of code: https://github.com/google/closure-library/blob/master/closure/goog/net/cookies.js#L180-L186

The last line `var m = c.lk` should be `var m = c.maxAge`, instead the property is replaced with a compiled symbol and the corresponding value is lost.

Is that my fault? Maybe I am using a bad build configuration or other?

I tested the advanced build on my personal mac and on a staging server with ubuntu, same result on both.

Thanks!

**Comment by thheller** [comment]
It is completely fine for the `:advanced` optimizations to rename this. Since it is part of the code that is available during compilation, all the instances should be renamed to the same shorter property name.

Please share the code where you are actually setting maxAge? I suspect that you are providing that option in an incorrect way.

**Comment by bago2k4** [comment]
Thanks @thheller for the quick reply.

So I tried creating the object in more than one way, here is the current (I think that's how `goog.net.Cookies.SetOptions` is meant to be used):
https://github.com/open-company/open-company-web/blob/4c322402122365047eb53a84c22ebf58a171f204/src/main/oc/web/lib/cookies.cljs#L63

But I have tried setting that object properties with `oops.core/oset!` and also tried passing a plain js object (created with js-obj):
```
(js-obj "secure" (boolean c-secure)
            "domain" (or c-domain ls/jwt-cookie-domain)
            ...)
```

But the transpiled code for `goog.net.Cookies.set` is always this:
```
g.set = function(a, b, c) {
        var d = !1;
        if ("object" === typeof c) {
            var e = c.sl; // <---------------------------- These is not c.sameSite
            d = c.secure || !1;
            var f = c.domain || void 0;
            var h = c.path || void 0;
            var m = c.lk // <---------------------------- These is not c.maxAge
        }
        if (/[;=\s]/.test(a))
            throw Error('Invalid cookie name "' + a + '"');
        if (/[;\r\n]/.test(b))
            throw Error('Invalid cookie value "' + b + '"');
        void 0 === m && (m = -1);
        c = f ? ";domain\x3d" + f : "";
        h = h ? ";path\x3d" + h : "";
        d = d ? ";secure" : "";
        m = 0 > m ? "" : 0 == m ? ";expires\x3d" + (new Date(1970,1,1)).toUTCString() : ";expires\x3d" + (new Date(Date.now() + 1E3 * m)).toUTCString();
        this.re.cookie = a + "\x3d" + b + c + h + m + d + (null != e ? ";samesite\x3d" + e : "")
};
```

Only the `sameSite` and the `maxAge` are replaced, but I am setting them in the same way of the others.

I think it has something to do with goog.net.Cookies externs.

**Comment by thheller** [comment]
You are looking at the completely wrong piece of code. The problem is in your code. Not in the shadow-cljs, the Closure Library, the Closure Compiler or Externs.

Both `js-obj` or `oops` are the problem here. You must not use those for code that is part of the `:advanced` optimizations. Instead use `#js {:maxAge ... :secure ... :domain ...}`, that'll create a proper object without renaming issues. In fact it'll still be renamed, just properly in all places.

You are running into the problem described [here](https://developers.google.com/closure/compiler/docs/api-tutorial3#propnames).

**Comment by bago2k4** [comment]
Yeah, sorry for bothering you here.

I got that I was in the wrong place but I wanted to get to the bottom.

I used the #js literal initially but that wasn't working. Not sure if it was a problem related to how I was passing the object.

My main confusion came from the fact that some property names were replaced and some other were not. I thought it was a compilation problem.

Thanks for your help, and sorry again..

**Comment by thheller** [comment]
The fact that `domain`, `path` and `secure` aren't renamed is just due the presence of some externs existing for those from other places (eg. `document.location.path`). You could add externs for `maxAge` to skip the rename too, but it is fine for this getting renamed since it is only used by "internal" code.
