### ISSUE TITLE
`:target :karma` tests are failing when `shadow.load` is used

### ISSUE THREAD

**Issue by Valdermeyder** [thheller/shadow-cljs#889]
Karma throws "Exception: Error: shadow.loader API was called before shadow.loader.init!" when `shadow.lazy` modules are used inside a tested function

# Example
https://github.com/Valdermeyder/karma-modules-support

# Workaround
Add js file with next content
```
(function () {
  goog.global.shadow$modules = {infos: {test: null}, uris: {test: []}}
  shadow.loader.init("");
})();
```
to `karma.conf.js -> files` configuration
You can find exact code changes [here](https://github.com/Valdermeyder/karma-modules-support/pull/1)

# Probable solution
`:target :karma` should support `:module-loader true` configuration in the same way as `:target :browser-test` does:
* It shouldn't load modules if their configuration is not provided by it should init `shadow.loader` when `:module-loader true`

# Versions

- "karma": "^6.3.2"
- "karma-chrome-launcher": "^3.1.0"
- "karma-cljs-test": "^0.1.0"
- "shadow-cljs": "2.14.1"

**Comment by thheller** [comment]
In `2.14.2` I added a new `:closure-defines {shadow.loader.TEST true}` option you can set to put the loader into test mode. That will just treat all modules as already loaded and any `load` call will always succeed. It assumes that you will require the code that would otherwise be loaded dynamically directly in your test.

**Comment by Valdermeyder** [comment]
@thheller thanks for the fix, it works fine. I have updated the demo repo with a fix
