### ISSUE TITLE
Macros that expand to require forms (CLJS-3276)

### ISSUE THREAD

**Issue by mtruyens** [thheller/shadow-cljs#913]
I tried to use macros that expand to (require) forms — as recently added by CLJS-3276 (to which you yourself contributed, if I understand correctly). 

This is a *very* welcome addition for my own project (where I dynamically have to require namespaces for certain types of builds), but I could not get it to work with Shadow-CLJS. It seems to work fine with regular lein-cljs-build, however.

**Comment by thheller** [comment]
I didn't contribute to CLJS-3276. I very much tried to veto it in fact. I think it was a mistake adding it. There are already a couple regressions caused by this: [CLJS-3311](https://clojure.atlassian.net/browse/CLJS-3311), [CLJS-3312](https://clojure.atlassian.net/browse/CLJS-3312) and it broke a few tools as well.

It is not yet supported by shadow-cljs as it'll require a fairly substantial change in how `ns` is handled. It'll also most likely cause caching to be completely disabled for namespaces doing this. I'll add it eventually but I might wait till all the regressions are sorted out.

**Comment by mtruyens** [comment]
I just read the entire discussion regarding the patch. Quite enlightening, I now understand your concerns. Thanks!

**Comment by thheller** [comment]
For future reference [CLJS-3276](https://clojure.atlassian.net/browse/CLJS-3276) was reverted in CLJS `1.10.879`. I'll keep an eye on it, should it ever come back.
