### ISSUE TITLE
Warning from expo about deprecated .expo.* file extension

### ISSUE THREAD

**Issue by bpringe** [thheller/shadow-cljs#917]
In a recently created Expo app, in which I'm using shadow-cljs, I get this warning when starting the project with `npm run android`:

```
Starting project at /home/brandon/development/honestdeed/honestdeed-app
Developer tools running on http://localhost:19002
Project is using deprecated .expo.* file extensions.
Please refactor the following files accordingly:

- /home/brandon/development/<org-folder>/<project-folder>/app/shadow.expo.js

Dangerously disable this check with EXPO_LEGACY_IMPORTS=1
Learn more: http://expo.fyi/expo-extension-migration

✔ Would you like to continue anyways? … yes
```

I have to select `yes` in order to continue, or I can set that environment variable mentioned.

I noticed that shadow file is named that way due to the namespace being `shadow.expo` (I think) and it doesn't seem like it's being used as described in [that link](http://expo.fyi/expo-extension-migration), so I'm thinking it's just a naming coincidence.

Another file, `shadow.expo.keep_awake.js`, might also trip that warning, though the warning doesn't include that file, so maybe not.

Shadow-cljs version: 2.14.6
Expo CLI version: 4.7.3

**Comment by thheller** [comment]
Doh. Yeah, its just the CLJS namespace output so really just a `.js` files that ends in `.expo.js` without being an actual `.expo.js` "special" file.

**Comment by bpringe** [comment]
Do you think it would be a good idea to change the namespaces to avoid this warning? I'll submit a PR if you want. I'm not sure what a good namespace would be, though. Maybe `expo` could be replaced with `expo-framework` or `expo-platform`? From their docs:

> Expo is a framework and a platform for universal React applications.

:man_shrugging:

**Comment by thheller** [comment]
No, I think this is silly. :P

I don't use expo or react-native myself so I have no real opinion on this. I'll certainly not remove it since I don't want to break stuff already using it. Given that this isn't really doing the thing they deprecated setting the env var should be fine too?

I have considered deprecating these namespaces entirely and maybe let someone else create them as a library. I'm actually surprised that the file still works after 3 years not touching it.

**Comment by bpringe** [comment]
Oh, I was probably wrongly assuming these namespaces were just used internally.

> I have considered deprecating these namespaces entirely and maybe let someone else create them as a library.

Okay, I'll close this. The env var will be fine. Thanks for the response!

**Comment by bpringe** [comment]
> I'll certainly not remove it since I don't want to break stuff already using it. 

Oh, of course, the namespace is used by my own app :man_facepalming:. I wasn't paying enough attention, I guess. :smile:

**Comment by thheller** [comment]
Do you not use `:target :react-native`? I'm surprised you even have the `shadow.expo.js` file? That shouldn't exist? If you are still on `:target :npm-module` you should consider switching.

**Comment by bpringe** [comment]
I'm using `:target :react-native`, but since I'm using Expo, I'm calling `shadow.expo/render-root`, which calls `registerRootComponent` from the expo lib. However, I do see this in their docs for `registerRootComponent`:

> Prior to SDK 18, it was necessary to use registerRootComponent directly, but for projects created as of SDK 18 or later, this is handled automatically in the Expo SDK.

So, maybe I don't need to use `shadow.expo`. I'll have to look further into it.

**Comment by thheller** [comment]
Hmm I can't quite remember why the target still outputs that file (and all the other files) since they aren't used. All the required code is in the `:output-dir` `index.js`. Using `shadow.expo` is fine, that is what it was made for. You can easily copy the code into your project or so too. Its not much and just handles the setup to hot-reload works.

**Comment by bpringe** [comment]
Yeah, that may be what I end up doing.

**Comment by PEZ** [comment]
I run into this when bumping RN in https://github.com/PEZ/rn-rf-shadow

It even stops expo from starting until the user has confirmed the warning.

I am not quite following what is a good way to deal with it. If I manually just delete `shadow.expo.js` things seem to work, and there are no warnings.

**Comment by bpringe** [comment]
@PEZ What I did was copy the code from [this namespace](https://github.com/thheller/shadow-cljs/blob/master/src/main/shadow/expo.cljs) into my project, and stopped requiring the namespace.

Using that namespace will cause the warning, so the choice is to either not use it, or set the env var as the warning mentions. As Thomas said, maybe that namespace should be deprecated.

**Comment by PEZ** [comment]
Thanks, @bpringe. I did the same.

**Comment by thheller** [comment]
Renaming the namespace is the "silly" fix. I'm not going to do that.

The problem here is that I made the decision a while ago to have shadow-cljs output files in a flat format. So `shadow.expo` ends up in a `shadow.expo.js` in the `:output-dir`. This was done so source maps become easier because they don't have a deal with relative paths and `:npm-module` looked "pretty" (eg. `require("my-lib/some.ns")` vs `require("my-lib/some/ns")`).

The `:npm-module` part is no longer relevant since thats going away anyway and never mattered much anyways. So the proper fix is removing the "flat" output format and the output file in this case will be `shadow/expo.js` which should no longer confuse expo.
