### ISSUE TITLE
Allow `dump-core` compiler-flag to be overriden

### ISSUE THREAD

**Issue by ZabelTech** [thheller/shadow-cljs#922]
Hi, 
as far as I can tell the `dump-core` compiler flag is hardcoded to `false` ( https://github.com/thheller/shadow-cljs/blob/03b2ed06a755afb7599a2f73ac7b5dc77dcf8285/src/main/shadow/build/cljs_bridge.clj#L57)

I agree that this is a sensible default and I also noticed the self hosted examples. 
Still it would be better if the user could override this, If he really desires to do so.

**Comment by thheller** [comment]
To achieve what exactly? In my arguably limited test you dont get very far with just cljs.core? So :bootstrap adresses that in a generic flexible way that makes :dump-core obsolete?

**Comment by ZabelTech** [comment]
Switching from a different build system is a problem. Some dependency somewhere in the tree might silently produce non-working code, when compiled with shadow-cljs.  Its' not always easy nor desirable to incorporate that :bootstrap mechanism of yours.

**Comment by thheller** [comment]
> Some dependency somewhere in the tree

You just don't randomly add the self-hosted coimpiler through a dependency? `:dump-core` is ONLY relevant when producing a self-hosted build running the compiler via `cljs.js`. You don't accidentally add that. It has many other build implications (ie. no more `:advanced`) and you should be carefully thinking about how to bootstrap the compiler at that point.

`:dump-core` is not supported because it dumps a huge amount of EDN data (which is then expressed as JS code) into your build, making it quite a bit larger than just loading the data separately from your JS. Which is what `:bootstrap` is for. When or how is that not desirable?

**Comment by ZabelTech** [comment]
You misunderstand the Issue. 
I'm not arguing for hardcoding the flag to `true`. I argue for not having it hardcoded to `false`.

> You just don't randomly add the self-hosted compiler through a dependency?

Ofc not, you might very well do that fully intentionally.
The rest of your reply is clear as per the clojurescript documentation.
The problem here is, that there is a default way of bootstrapping self-hosted environments and there is an alternative way. 
You make the alternative the new default, and rule out the old default entirely.

I wanted to make you aware of this.

Then there is certainly the other line of reasoning about 'the user is always right', and not silently ignoring compiler-flags, not having that documented and so forth.

**Comment by thheller** [comment]
> I wanted to make you aware of this.

I'm very well aware of this.

The `:bootstrap` however solves a problem that many people had (eg. nextjournal.com, maria.cloud) with the "old default". In my observations actually BUILDING a self-hosted build always required a customized build setup (eg. https://github.com/arichiardi/replumb or something entirely custom).

An example would help this discussion. What is the actual problem here? The only issue I see so far is the "silenlty ignoring compiler-flags". The blogpost I linked has served many people as documentation enough to get going. PR welcome anytime to add more docs.

I have no intention of staying compatible with "official" build documentation otherwise since pretty much all build configuration is intentionally different.

**Comment by ZabelTech** [comment]
> I have no intention of staying compatible with "official" build documentation

why the quotes? I'm refering to this https://clojurescript.org/guides/self-hosting
I do think that shadows-cljs should respect all official compiler flags and the official compiler documentation, 
since it does use the official compiler. To me this is an all or nothing kind of thing, i.e. respecting some flags and other not that's almost criminal. But alright, I think I have already made my point. 

>PR welcome anytime to add more docs.

Are you open to a PR that adds a check and drops a warning, when using one of the ignored options?

>An example would help this discussion

I'm onto adding shadows-cljs support to https://github.com/viebel/klipse, so that one depends on https://github.com/viebel/klipse-clj. This one expects that core-dump works as per documentation and it already has a mechanism to load dependencies over the network, where cljs.core has been specfically excluded from. 
Ofc I can add cljs.core there an modify a couple oft checks etc. and have it working aswell. 

Basicly, I just want to add a new build tool and now I need to touch logic in the code.
Sure, that can be done easily , but I don't think it's ideal. 
So that's why I let you know.

**Comment by thheller** [comment]
I'm open to adding support for `:dump-core` back in. I just need arguments why doing that would be a useful thing. "Because" is not enough. FWIW `:optimize-constants` also does nothing since shadow-cljs handles that differently (and more efficiently IMHO). "Official" was in quotes because I have no idea what you were working with.

What you are after is building klipse with `shadow-cljs`, which already has one of those custom build things I mentioned. You are not interested in removing all that and relying on the shadow bootstrap. Fair point. Please note however that even the official page describes a method of dumping the analyzer data and loading it on demand and setting `:dump-core false` to avoid the "bloat". 

> This simple optimization eliminates about 2.7mb of generated JavaScript.

This would benefit klipse directly as well since that is significant. You could even use the `:target :bootstrap` stuff just to automate extracting the analyzer data and loading that yourself without the shadow bootstrap loader. Nothing in the `:bootstrap` output assumes or requires you actually use the `shadow.cljs.bootstrap.browser` loader.

**Comment by ZabelTech** [comment]
I understand the first part.

Second part:
> You are not interested in removing all that and relying on the shadow bootstrap. 

Right, the application code should be independent of the build tool.

> and setting :dump-core false to avoid the "bloat"

Good use of quotes, because this is not junk. It's necessary data. 
When do you want self-hosting but don't want core? 
Seems intuitiv to me to shove those 2.6 megs in right away, cause they are needed anyway.
Or are you telling me that advantage is there even after the loading core? 

Also, do I get your comment from above right, that using this after-load, I can have self-hosting with advanced optimisations turned on?

I agree, those two points are indeed very significant. And also right, klipse should allready be able to leverage this out of the box.

**Comment by thheller** [comment]
`:advanced` is not possible with self-hosted builds. No matter how.

The bloat however is real when using `:dump-core`. That dumps the data into the code and turns it into code. So `foo` becomes `new cljs.core.Symbol(null, "foo", hashcode)` and so on. You can see how this will get significantly bigger quickly. I don't remember all the numbers but lets use the 2.7mb mentioned in the article. The analyzer data for `cljs.core`  produced by `:bootstrap`  is instead 640kb-ish transit encoded EDN. Right away thats about 2mb less for the same end result, only difference it that you have to load it at runtime in a "bootstrap/init" like way. he benchmarks I did were a long time ago but loading it dynamically is significantly faster for the initial page load (even with gzip for everything). Time to actual first `eval` was also better and being able to render something while you are loading improves the UX a lot.

It also cuts down on the build times since it doesn't have to optimize an extra 2.7mb of JS code. Less important but still noteworthy.

**Comment by ZabelTech** [comment]
wow, I was not aware of that. tanks, that is really good info!

**Comment by ZabelTech** [comment]
alright, thanks for this discussion again. so I am going forward with the hosted analyzer cache, instead of the 'core-dump'.
This means we could close this.  
My take on this is, that the technical benefits by hosting the cache should outweigh the added complexity in all but toy-cases.
(And I understand that this was your point the whole time).
The points about the docs etc. stand, but that is besides this ticket.
