### ISSUE TITLE
Errors that occurred during `env.load` or `env.evalLoad` don't have any info but the stack trace

### ISSUE THREAD

**Issue by p-himik** [thheller/shadow-cljs#936]
As can be seen in this issue https://github.com/thheller/shadow-cljs/issues/909#issue-932298151 there's just a stack trace.
The error itself is not reported.
Indeed, the relevant code:
```js
} catch (e) {
  console.error("An error occurred when loading", uri);
  console.error(e.stack);
}
```

Would it make sense to report the error itself, e.g. by replacing the last statement with `console.error(e)`?

**Comment by thheller** [comment]
The reason it only logs `e.stack` is precisely to make the error more usable and it does report the actual error? I did just tweak the first message a little bit but here is what I get with `e` and `e.stack`.

## e
![2021-09-22--10-43](https://user-images.githubusercontent.com/144930/134311988-39c42f3b-6b6c-4d2c-85c1-fd5479b5899e.png)

## e.stack
![2021-09-22--10-44](https://user-images.githubusercontent.com/144930/134312095-ac20296b-0654-4103-a095-4ecfd7eb2b6e.png)

For testing this is with just `(throw (ex-info "foo" {}))` or `(throw (js/Error. "foo"))` in the `demo.browser` ns from the `:browser` test build directly in the shadow-cljs repo. As you can see you get an additional stacktrace that is otherwise missing?

Unfortunately many reports don't contain all actual information which is why I tweaked the message that was logged first and turned it into a warning only so it doesn't hide the error. Firefox in general does not like `evalLoad` so much and doesn't source map as much as Chrome does.

**Comment by thheller** [comment]
Actually scratch that. The behavior is entirely different depending on what type of exception is thrown. Regular `js/Error` looks worse while `ex-info` looks better. Guess I'll add some detection or something.
