### ISSUE TITLE
How do I include Transit in my shadow-cljs.edn?

### ISSUE THREAD

**Issue by WorldsEndless** [thheller/shadow-cljs#938]
With version based on their official repo, I have added to my dependencies 

`[com.cognitect/transit-cljs "0.8.874"]`

I've tried it with all the permutations of transit-js, not referring to com.cognitect, etc. Every time I get "artifact not found"

**Comment by thheller** [comment]
Technically you don't need to include it since shadow-cljs already depends on it and provides it. Otherwise just

I'm guessing you just picked the wrong version? [transit-cljs](https://github.com/cognitect/transit-cljs) latest is `[com.cognitect/transit-cljs "0.8.269"]` whereas [transit-js](https://github.com/cognitect/transit-js) is `0.8.874`. Can't depend on a version that doesn't exist.

**Comment by WorldsEndless** [comment]
Perfect! Thanks. I discovered that Transit was in the box with Shadow first, so that worked, and I suppose I spoiled by other libraries and never considered that transit-cljs and transit-js had different versions.
