### ISSUE TITLE
Why the cljs source file need include in production compile js file？

### ISSUE THREAD

**Issue by xlisp** [thheller/shadow-cljs#942]
![image](https://user-images.githubusercontent.com/6021537/136428571-32e60502-695a-4ec3-a79e-e9203e1360ba.png)

@thheller  😊

**Comment by thheller** [comment]
I do not understand what you are asking. The screenshot is from the build report for the shadow-cljs UI and everything is supposed to be there?

**Comment by thheller** [comment]
The CLJS files are not included. The JS output created for them is. The build report just shows how much of that converted JS code remains for each file after `:advanced` optimizations. There is never any actual CLJS source included anywhere.

**Comment by chanshunli** [comment]
The whole is my cljs project, packaged out 7.2M, the `shadow.cljs.build-report` ask me.

![image](https://user-images.githubusercontent.com/6021537/136430914-7f79c167-56df-4468-af19-11882fb1181e.png)

**Comment by thheller** [comment]
Without knowing what you are doing in your code I cannot comment on that.

Did you set `:optimizations :simple`? That'll be much larger than `:advanced` and 2.2mb would be quite normal for that. Otherwise it should be smaller but it all depends on what you are doing.

As an example datapoint the JS code generated for `shadow/cljs/ui/components/inspect.cljs` is `156.71 KB` without optimizations and `16.54 KB` in the `release` build with `:advanced` as seen in the UI report.

**Comment by chanshunli** [comment]
I use a lot of clojure `comment` functions, will it have a big impact?
like this:
```clojure
(comment 
  (aaa 1) ;;=> 1
  )
(defn aaa [a] a)

```

**Comment by thheller** [comment]
No, `comment` doesn't generate any JS at all so that will have 0 impact.

Just at the `Project Files` and pick the largest one. Then look at the code in that file and what it is doing. If the optimized size is much larger than the original source files then it likely is some macro generating a whole lot of code.
