### ISSUE TITLE
Using "#_" macro on certain forms results in compilation error

### ISSUE THREAD

**Issue by GutZuFusss** [thheller/shadow-cljs#953]
As far as I understand it the "#_" macro should behave like a comment, and the next form should not be evaluated.

Namespace bound keywords seem to cause a problem here:
`#_(::invalid/keyword)`
Causes the compilation to fail, other errornous forms are ignored as expected... Pretty annoying, if you try to comment out forms from copy and pasted forms.

**Comment by thheller** [comment]
This is not a shadow-cljs issue. If anything this is a problem in the [reader](https://github.com/clojure/tools.reader) but given that the problem also exists in Clojure itself I doub't it'll see a fix anytime soon.

The problem also has nothing to do with the `#_` reader macro. It still needs to read as valid Clojure code but since the `::invalid` alias cannot be resolved it is not valid strictly speaking. I know this is frustrating but nothing I can fix from the shadow-cljs side of things.
