### ISSUE TITLE
node-jre or Java?

### ISSUE THREAD

**Issue by jiyinyiyong** [thheller/shadow-cljs#97]
```
=>> yarn build
yarn run v1.1.0
$ yarn del && yarn release && yarn webpack && yarn compile-ssr && yarn html
shadow-cljs - config: /Users/chen/repo/mvc-works/coworkflow/shadow-cljs.edn version: 1.0.20170803
No Java runtime present, requesting install.
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It pops `java` command not found. Then I tried to install `node-jre`, it does not help. So I'm installing Java.

So how to use `node-jre`? Or is Java required?

**Comment by thheller** [comment]
I never actually tested `node-jre`. Did you install it manually? `shadow-cljs` itself does not depend on it.

Properly installed java is preferred anyways.

**Comment by jiyinyiyong** [comment]
I tried to install it locally. It did not help.

**Comment by thheller** [comment]
`No Java runtime present, requesting install.` is a OSX thing. It might prevent the `node-jre` from working since usually `shadow-cljs` should output a message that `java` failed and it tried `node-jre`. I might remove `node-jre` support completely, last time I tried it it was getting re-installed every time I ran `yarn` which was pretty annoying.

**Comment by jiyinyiyong** [comment]
Installing Java is not a big thing compared to writing Java. 🤓

**Comment by thheller** [comment]
Indeed.

**Comment by thheller** [comment]
Dropped `node-jre` support, it never really worked AFAICT.
