### ISSUE TITLE
@react-three/drei can't go through shadow-cljs since v4.0.0

### ISSUE THREAD

**Issue by itarck** [thheller/shadow-cljs#971]
r3f+drei, version since 2021-03-30

        shadow-cljs - watching build :r3f-and-drei
        [:r3f-and-drei] Configuring build.
        [:r3f-and-drei] Compiling ...
        [:r3f-and-drei] Build failure:
        Closure compilation failed with 2 errors
        --- node_modules/three-stdlib/index.cjs.js:2
        Illegal variable reference before declaration: i
        --- node_modules/three-stdlib/index.cjs.js:2
        Illegal variable reference before declaration: t

some BREAKING CHANGES of @react-three/drei
, https://github.com/pmndrs/drei/releases?page=17 

- "@react-three/drei": "^4.0.0", // (2021-03-29) three-stdlib is now the defacto pacakge over three/examples. minimum supported version of react-three/fiber is ">=6.0"
- "@react-three/fiber": "^6.0.0", // (2021-03-30), rename react-three-fiber to @react-three/fiber

I think it's because of three-stdlib, but I'm not very familiar with js ...
Here is my testing code,  tested more versions , https://github.com/itarck/r3f-for-testing

**Comment by thheller** [comment]
Those are errors from the Closure Compiler. It sometimes doesn't like JS code that is otherwise valid. Unfortunately there is no easy way to fix it, besides skipping the Closure Compiler completely for the JS processing. You could use webpack as described in this [blog post](https://code.thheller.com/blog/shadow-cljs/2020/05/08/how-about-webpack-now.html#option-2-js-provider-external).

**Comment by itarck** [comment]
Thanks, @thheller. I have tested, the solution works for latest version of r3f+drei.

-  "@react-three/drei": "^8.3.1",
-  "@react-three/fiber": "^7.0.24",

btw, a small paren typo in the blog post, :js-options should in  {:builds {:app {:js-options {...}}}}
