### ISSUE TITLE
No matching clause IllegalArguementException

### ISSUE THREAD

**Issue by CambodianCoder** [thheller/shadow-cljs#974]
I have a clojurescript / shadow-cljs project using version 2.16.10 (previously tried 2.16.8). Recently, when I start a ClojureScript repl, and then attempt to evaluate functions from any namespace (via C-x C-e), I have started getting the following error. 

![image](https://user-images.githubusercontent.com/35553625/147863556-1ada4e61-db0d-451b-bf84-46bc02d9acab.png)

I traced it to https://github.com/thheller/shadow-cljs/blob/5654aaac86168510837e9b1100f5f25887a0dab6/src/main/shadow/build/cljs_hacks.cljc#L981, but I'm not sure what the correct approach would be to mitigate this exception in my code. 

I am using the following dependencies, 
![image](https://user-images.githubusercontent.com/35553625/147863700-571f4650-9716-439b-91b4-4483e59dc982.png)

and starting with the following repl configuration. 

![image](https://user-images.githubusercontent.com/35553625/147863690-8d309938-2bbd-47db-8076-cfedd01c87ad.png)

I'm not exactly sure what is causing the exception, considering I don't have any indication of syntax errors from the joker or clj-kondo linters, and the code/project itself works fine when deployed in a production environment. 

Is this an issue with shadow-cljs and how it interacts with the cider repl, or is it some misconfiguration in my project? If it's an issue with my configuration, do you have any suggestions on how I can resolve this exception?

**Comment by thheller** [comment]
Your cider setup appears to be incorrect? This should have never worked regardless of version? The last screenshot showing the `ClojureScript REPL init form` is what you'd be using for a normal CLJS node REPL? I don't use emacs so I don't know how you change that. Did you follow https://shadow-cljs.github.io/docs/UsersGuide.html#cider? It should be something like `(shadow.cljs.devtools.api/repl :your-build-id)` which I believe `cider` will do automatically if you tell it you want a shadow-cljs REPL?

The stacktrace itself is just an indication that you are calling things in incorrectly since the default CLJS REPLs cannot work with the shadow-cljs code.
